/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { accountsApis } from './apis/accounts.ts'
import { authenticationApis } from './apis/authentication.ts'
import { billingCostsAnalysisApis } from './apis/billing-costs-analysis.ts'
import { deploymentTemplatesApis } from './apis/deployment-templates.ts'
import { deploymentsApis } from './apis/deployments.ts'
import { deploymentsTrafficFilterApis } from './apis/deployments-traffic-filter.ts'
import { extensionsApis } from './apis/extensions.ts'
import { organizationsApis } from './apis/organizations.ts'
import { stackApis } from './apis/stack.ts'
import { trustedEnvironmentsApis } from './apis/trusted-environments.ts'
import { userRoleAssignmentsApis } from './apis/user-role-assignments.ts'
import type { CloudApiDefinition } from './types.ts'

/** All Cloud control plane API definitions. */
export const allCloudApis: CloudApiDefinition[] = [
  ...accountsApis,
  ...authenticationApis,
  ...billingCostsAnalysisApis,
  ...deploymentTemplatesApis,
  ...deploymentsApis,
  ...deploymentsTrafficFilterApis,
  ...extensionsApis,
  ...organizationsApis,
  ...stackApis,
  ...trustedEnvironmentsApis,
  ...userRoleAssignmentsApis,
]
