/**
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { elasticsearchProjectsApis } from './apis/elasticsearch-projects.ts'
import { linkedCandidateProjectsApis } from './apis/linked-candidate-projects.ts'
import { linkedProjectsApis } from './apis/linked-projects.ts'
import { observabilityProjectsApis } from './apis/observability-projects.ts'
import { regionsApis } from './apis/regions.ts'
import { securityProjectsApis } from './apis/security-projects.ts'
import { trafficFiltersApis } from './apis/traffic-filters.ts'
import type { CloudApiDefinition } from './types.ts'

/** All Serverless API definitions. */
export const allServerlessApis: CloudApiDefinition[] = [
  ...elasticsearchProjectsApis,
  ...linkedCandidateProjectsApis,
  ...linkedProjectsApis,
  ...observabilityProjectsApis,
  ...regionsApis,
  ...securityProjectsApis,
  ...trafficFiltersApis,
]
