/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { agentBuilderApis } from './apis/agent-builder.ts'
import { alertingApis } from './apis/alerting.ts'
import { apmAgentConfigurationApis } from './apis/apm-agent-configuration.ts'
import { apmAgentKeysApis } from './apis/apm-agent-keys.ts'
import { apmAnnotationsApis } from './apis/apm-annotations.ts'
import { apmServerSchemaApis } from './apis/apm-server-schema.ts'
import { apmSourcemapsApis } from './apis/apm-sourcemaps.ts'
import { connectorsApis } from './apis/connectors.ts'
import { dataStreamsApis } from './apis/data-streams.ts'
import { dataViewsApis } from './apis/data-views.ts'
import { elasticAgentActionsApis } from './apis/elastic-agent-actions.ts'
import { elasticAgentBinaryDownloadSourcesApis } from './apis/elastic-agent-binary-download-sources.ts'
import { elasticAgentPoliciesApis } from './apis/elastic-agent-policies.ts'
import { elasticAgentStatusApis } from './apis/elastic-agent-status.ts'
import { elasticAgentsApis } from './apis/elastic-agents.ts'
import { elasticPackageManagerEpmApis } from './apis/elastic-package-manager-epm.ts'
import { fleetAgentlessPoliciesApis } from './apis/fleet-agentless-policies.ts'
import { fleetCloudConnectorsApis } from './apis/fleet-cloud-connectors.ts'
import { fleetEnrollmentApiKeysApis } from './apis/fleet-enrollment-api-keys.ts'
import { fleetInternalsApis } from './apis/fleet-internals.ts'
import { fleetOutputsApis } from './apis/fleet-outputs.ts'
import { fleetPackagePoliciesApis } from './apis/fleet-package-policies.ts'
import { fleetProxiesApis } from './apis/fleet-proxies.ts'
import { fleetServerHostsApis } from './apis/fleet-server-hosts.ts'
import { fleetUninstallTokensApis } from './apis/fleet-uninstall-tokens.ts'
import { maintenanceWindowApis } from './apis/maintenance-window.ts'
import { messageSigningServiceApis } from './apis/message-signing-service.ts'
import { miscApis } from './apis/misc.ts'
import { mlApis } from './apis/ml.ts'
import { observabilityaiassistantApis } from './apis/observabilityaiassistant.ts'
import { rolesApis } from './apis/roles.ts'
import { savedObjectsApis } from './apis/saved-objects.ts'
import { securityAiAssistantApiApis } from './apis/security-ai-assistant-api.ts'
import { securityAttackDiscoveryApiApis } from './apis/security-attack-discovery-api.ts'
import { securityDetectionsApiApis } from './apis/security-detections-api.ts'
import { securityEndpointExceptionsApiApis } from './apis/security-endpoint-exceptions-api.ts'
import { securityEndpointManagementApiApis } from './apis/security-endpoint-management-api.ts'
import { securityEntityAnalyticsApiApis } from './apis/security-entity-analytics-api.ts'
import { securityExceptionsApiApis } from './apis/security-exceptions-api.ts'
import { securityListsApiApis } from './apis/security-lists-api.ts'
import { securityOsqueryApiApis } from './apis/security-osquery-api.ts'
import { securityTimelineApiApis } from './apis/security-timeline-api.ts'
import { sloApis } from './apis/slo.ts'
import { spacesApis } from './apis/spaces.ts'
import { streamsApis } from './apis/streams.ts'
import { systemApis } from './apis/system.ts'
import { taskManagerApis } from './apis/task-manager.ts'
import { workflowsApis } from './apis/workflows.ts'
import type { KbApiDefinition } from './types.ts'

/** All Kibana API definitions for the `kb` command group. */
export const allKbApis: KbApiDefinition[] = [
  ...agentBuilderApis,
  ...alertingApis,
  ...apmAgentConfigurationApis,
  ...apmAgentKeysApis,
  ...apmAnnotationsApis,
  ...apmServerSchemaApis,
  ...apmSourcemapsApis,
  ...connectorsApis,
  ...dataStreamsApis,
  ...dataViewsApis,
  ...elasticAgentActionsApis,
  ...elasticAgentBinaryDownloadSourcesApis,
  ...elasticAgentPoliciesApis,
  ...elasticAgentStatusApis,
  ...elasticAgentsApis,
  ...elasticPackageManagerEpmApis,
  ...fleetAgentlessPoliciesApis,
  ...fleetCloudConnectorsApis,
  ...fleetEnrollmentApiKeysApis,
  ...fleetInternalsApis,
  ...fleetOutputsApis,
  ...fleetPackagePoliciesApis,
  ...fleetProxiesApis,
  ...fleetServerHostsApis,
  ...fleetUninstallTokensApis,
  ...maintenanceWindowApis,
  ...messageSigningServiceApis,
  ...miscApis,
  ...mlApis,
  ...observabilityaiassistantApis,
  ...rolesApis,
  ...savedObjectsApis,
  ...securityAiAssistantApiApis,
  ...securityAttackDiscoveryApiApis,
  ...securityDetectionsApiApis,
  ...securityEndpointExceptionsApiApis,
  ...securityEndpointManagementApiApis,
  ...securityEntityAnalyticsApiApis,
  ...securityExceptionsApiApis,
  ...securityListsApiApis,
  ...securityOsqueryApiApis,
  ...securityTimelineApiApis,
  ...sloApis,
  ...spacesApis,
  ...streamsApis,
  ...systemApis,
  ...taskManagerApis,
  ...workflowsApis,
]
