/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { AsyncSearchStatusRequest } from './schemas/async_search_status.ts'
import type { EsApiDefinition } from '../types.ts'

export const asyncSearchStatusApis: EsApiDefinition[] = [
 {
   name: "status",
   namespace: "async-search",
   description: "Get the async search status.",
   method: "GET",
   path: "/_async_search/status/{id}",
   input: AsyncSearchStatusRequest,
 },
]
