/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { AsyncSearchDeleteRequest, AsyncSearchGetRequest, AsyncSearchStatusRequest, AsyncSearchSubmitRequest } from '@elastic/es-schemas/async_search.js'
import type { EsApiDefinition } from '../types.ts'

export const asyncSearchApis: EsApiDefinition[] = [
 {
  name: "delete",
  namespace: "async-search",
  description: "Delete an async search.",
  method: "DELETE",
  path: "/_async_search/{id}",
  input: AsyncSearchDeleteRequest,
 },
 {
  name: "get",
  namespace: "async-search",
  description: "Get async search results.",
  method: "GET",
  path: "/_async_search/{id}",
  input: AsyncSearchGetRequest,
 },
 {
  name: "status",
  namespace: "async-search",
  description: "Get the async search status.",
  method: "GET",
  path: "/_async_search/status/{id}",
  input: AsyncSearchStatusRequest,
 },
 {
  name: "submit",
  namespace: "async-search",
  description: "Run an async search.",
  method: "POST",
  path: "/{index}/_async_search",
  input: AsyncSearchSubmitRequest,
 },
]
