/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { AsyncSearchGetRequest } from '@elastic/es-schemas/async_search_get.js'
import type { EsApiDefinition } from '../types.ts'

export const asyncSearchGetApis: EsApiDefinition[] = [
 {
  name: "get",
  namespace: "async-search",
  description: "Get async search results.",
  method: "GET",
  path: "/_async_search/{id}",
  input: AsyncSearchGetRequest,
 },
]
