/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { AsyncSearchDeleteRequest } from './schemas/async_search_delete.ts'
import type { EsApiDefinition } from '../types.ts'

export const asyncSearchDeleteApis: EsApiDefinition[] = [
 {
   name: "delete",
   namespace: "async-search",
   description: "Delete an async search.",
   method: "DELETE",
   path: "/_async_search/{id}",
   input: AsyncSearchDeleteRequest,
 },
]
