/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { AsyncSearchGetRequest } from './schemas/async_search_get.ts'
import type { EsApiDefinition } from '../types.ts'

export const asyncSearchGetApis: EsApiDefinition[] = [
 {
   name: "get",
   namespace: "async-search",
   description: "Get async search results.",
   method: "GET",
   path: "/_async_search/{id}",
   input: AsyncSearchGetRequest,
 },
]
