/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { AsyncSearchSubmitRequest } from './schemas/async_search_submit.ts'
import type { EsApiDefinition } from '../types.ts'

export const asyncSearchSubmitApis: EsApiDefinition[] = [
 {
   name: "submit",
   namespace: "async-search",
   description: "Run an async search.",
   method: "POST",
   path: "/{index}/_async_search",
   input: AsyncSearchSubmitRequest,
 },
]
