/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { CatAliasesRequest, CatComponentTemplatesRequest, CatCountRequest, CatHelpRequest, CatIndicesRequest, CatMlDataFrameAnalyticsRequest, CatMlDatafeedsRequest, CatMlJobsRequest, CatMlTrainedModelsRequest, CatTransformsRequest } from './schemas/cat.ts'
import type { EsApiDefinition } from '../types.ts'

export const catApis: EsApiDefinition[] = [
  {
    name: 'aliases',
    namespace: 'cat',
    description: 'Get aliases.',
    method: 'GET',
    path: '/_cat/aliases/{name}',
    input: CatAliasesRequest,
    responseType: 'text'
  },
  {
    name: 'component-templates',
    namespace: 'cat',
    description: 'Get component templates.',
    method: 'GET',
    path: '/_cat/component_templates/{name}',
    input: CatComponentTemplatesRequest,
    responseType: 'text'
  },
  {
    name: 'count',
    namespace: 'cat',
    description: 'Get a document count.',
    method: 'POST',
    path: '/_cat/count/{index}',
    input: CatCountRequest,
    responseType: 'text'
  },
  {
    name: 'help',
    namespace: 'cat',
    description: 'Get CAT help.',
    method: 'GET',
    path: '/_cat',
    input: CatHelpRequest,
    responseType: 'text'
  },
  {
    name: 'indices',
    namespace: 'cat',
    description: 'Get index information.',
    method: 'GET',
    path: '/_cat/indices/{index}',
    input: CatIndicesRequest,
    responseType: 'text'
  },
  {
    name: 'ml-data-frame-analytics',
    namespace: 'cat',
    description: 'Get data frame analytics jobs.',
    method: 'GET',
    path: '/_cat/ml/data_frame/analytics/{id}',
    input: CatMlDataFrameAnalyticsRequest,
    responseType: 'text'
  },
  {
    name: 'ml-datafeeds',
    namespace: 'cat',
    description: 'Get datafeeds.',
    method: 'GET',
    path: '/_cat/ml/datafeeds/{datafeed_id}',
    input: CatMlDatafeedsRequest,
    responseType: 'text'
  },
  {
    name: 'ml-jobs',
    namespace: 'cat',
    description: 'Get anomaly detection jobs.',
    method: 'GET',
    path: '/_cat/ml/anomaly_detectors/{job_id}',
    input: CatMlJobsRequest,
    responseType: 'text'
  },
  {
    name: 'ml-trained-models',
    namespace: 'cat',
    description: 'Get trained models.',
    method: 'GET',
    path: '/_cat/ml/trained_models/{model_id}',
    input: CatMlTrainedModelsRequest,
    responseType: 'text'
  },
  {
    name: 'transforms',
    namespace: 'cat',
    description: 'Get transform information.',
    method: 'GET',
    path: '/_cat/transforms/{transform_id}',
    input: CatTransformsRequest,
    responseType: 'text'
  }
]
