/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { CatAliasesRequest } from './schemas/cat_aliases.ts'
import type { EsApiDefinition } from '../types.ts'

export const catAliasesApis: EsApiDefinition[] = [
 {
   name: "aliases",
   namespace: "cat",
   description: "Get aliases.",
   method: "GET",
   path: "/_cat/aliases/{name}",
   input: CatAliasesRequest,
   responseType: 'text',
 },
]
