/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { CatTransformsRequest } from '@elastic/es-schemas/cat_transforms.js'
import type { EsApiDefinition } from '../types.ts'

export const catTransformsApis: EsApiDefinition[] = [
 {
  name: "transforms",
  namespace: "cat",
  description: "Get transform information.",
  method: "GET",
  path: "/_cat/transforms/{transform_id}",
  input: CatTransformsRequest,
  responseType: 'text',
 },
]
