/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { CatComponentTemplatesRequest } from './schemas/cat_component_templates.ts'
import type { EsApiDefinition } from '../types.ts'

export const catComponentTemplatesApis: EsApiDefinition[] = [
 {
   name: "component-templates",
   namespace: "cat",
   description: "Get component templates.",
   method: "GET",
   path: "/_cat/component_templates/{name}",
   input: CatComponentTemplatesRequest,
   responseType: 'text',
 },
]
