/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { CatNodesRequest } from '@elastic/es-schemas/cat_nodes.js'
import type { EsApiDefinition } from '../types.ts'

export const catNodesApis: EsApiDefinition[] = [
 {
  name: "nodes",
  namespace: "cat",
  description: "Get node information.",
  method: "GET",
  path: "/_cat/nodes",
  input: CatNodesRequest,
  responseType: 'text',
 },
]
