/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { CatPendingTasksRequest } from '@elastic/es-schemas/cat_pending_tasks.js'
import type { EsApiDefinition } from '../types.ts'

export const catPendingTasksApis: EsApiDefinition[] = [
 {
  name: "pending-tasks",
  namespace: "cat",
  description: "Get pending task information.",
  method: "GET",
  path: "/_cat/pending_tasks",
  input: CatPendingTasksRequest,
  responseType: 'text',
 },
]
