/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { CatTransformsRequest } from './schemas/cat_transforms.ts'
import type { EsApiDefinition } from '../types.ts'

export const catTransformsApis: EsApiDefinition[] = [
 {
   name: "transforms",
   namespace: "cat",
   description: "Get transform information.",
   method: "GET",
   path: "/_cat/transforms/{transform_id}",
   input: CatTransformsRequest,
   responseType: 'text',
 },
]
