/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { CatHealthRequest } from '@elastic/es-schemas/cat_health.js'
import type { EsApiDefinition } from '../types.ts'

export const catHealthApis: EsApiDefinition[] = [
 {
  name: "health",
  namespace: "cat",
  description: "Get the cluster health status.",
  method: "GET",
  path: "/_cat/health",
  input: CatHealthRequest,
  responseType: 'text',
 },
]
