/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { CatHelpRequest } from './schemas/cat_help.ts'
import type { EsApiDefinition } from '../types.ts'

export const catHelpApis: EsApiDefinition[] = [
 {
   name: "help",
   namespace: "cat",
   description: "Get CAT help.",
   method: "GET",
   path: "/_cat",
   input: CatHelpRequest,
   responseType: 'text',
 },
]
