/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { CatMlJobsRequest } from './schemas/cat_ml_jobs.ts'
import type { EsApiDefinition } from '../types.ts'

export const catMlJobsApis: EsApiDefinition[] = [
 {
   name: "ml-jobs",
   namespace: "cat",
   description: "Get anomaly detection jobs.",
   method: "GET",
   path: "/_cat/ml/anomaly_detectors/{job_id}",
   input: CatMlJobsRequest,
   responseType: 'text',
 },
]
