/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { CatMlDatafeedsRequest } from './schemas/cat_ml_datafeeds.ts'
import type { EsApiDefinition } from '../types.ts'

export const catMlDatafeedsApis: EsApiDefinition[] = [
 {
   name: "ml-datafeeds",
   namespace: "cat",
   description: "Get datafeeds.",
   method: "GET",
   path: "/_cat/ml/datafeeds/{datafeed_id}",
   input: CatMlDatafeedsRequest,
   responseType: 'text',
 },
]
