/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { CatTemplatesRequest } from '@elastic/es-schemas/cat_templates.js'
import type { EsApiDefinition } from '../types.ts'

export const catTemplatesApis: EsApiDefinition[] = [
 {
  name: "templates",
  namespace: "cat",
  description: "Get index template information.",
  method: "GET",
  path: "/_cat/templates/{name}",
  input: CatTemplatesRequest,
  responseType: 'text',
 },
]
