/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { CatMlTrainedModelsRequest } from './schemas/cat_ml_trained_models.ts'
import type { EsApiDefinition } from '../types.ts'

export const catMlTrainedModelsApis: EsApiDefinition[] = [
 {
   name: "ml-trained-models",
   namespace: "cat",
   description: "Get trained models.",
   method: "GET",
   path: "/_cat/ml/trained_models/{model_id}",
   input: CatMlTrainedModelsRequest,
   responseType: 'text',
 },
]
