/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { CatMlTrainedModelsRequest } from '@elastic/es-schemas/cat_ml_trained_models.js'
import type { EsApiDefinition } from '../types.ts'

export const catMlTrainedModelsApis: EsApiDefinition[] = [
 {
  name: "ml-trained-models",
  namespace: "cat",
  description: "Get trained models.",
  method: "GET",
  path: "/_cat/ml/trained_models/{model_id}",
  input: CatMlTrainedModelsRequest,
  responseType: 'text',
 },
]
