/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { CatThreadPoolRequest } from '@elastic/es-schemas/cat_thread_pool.js'
import type { EsApiDefinition } from '../types.ts'

export const catThreadPoolApis: EsApiDefinition[] = [
 {
  name: "thread-pool",
  namespace: "cat",
  description: "Get thread pool statistics.",
  method: "GET",
  path: "/_cat/thread_pool/{thread_pool_patterns}",
  input: CatThreadPoolRequest,
  responseType: 'text',
 },
]
