/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { CatTasksRequest } from '@elastic/es-schemas/cat_tasks.js'
import type { EsApiDefinition } from '../types.ts'

export const catTasksApis: EsApiDefinition[] = [
 {
  name: "tasks",
  namespace: "cat",
  description: "Get task information.",
  method: "GET",
  path: "/_cat/tasks",
  input: CatTasksRequest,
  responseType: 'text',
 },
]
