/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { CatCountRequest } from './schemas/cat_count.ts'
import type { EsApiDefinition } from '../types.ts'

export const catCountApis: EsApiDefinition[] = [
 {
   name: "count",
   namespace: "cat",
   description: "Get a document count.",
   method: "POST",
   path: "/_cat/count/{index}",
   input: CatCountRequest,
   responseType: 'text',
 },
]
