/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { CatRecoveryRequest } from '@elastic/es-schemas/cat_recovery.js'
import type { EsApiDefinition } from '../types.ts'

export const catRecoveryApis: EsApiDefinition[] = [
 {
  name: "recovery",
  namespace: "cat",
  description: "Get shard recovery information.",
  method: "GET",
  path: "/_cat/recovery/{index}",
  input: CatRecoveryRequest,
  responseType: 'text',
 },
]
