/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { CatIndicesRequest } from './schemas/cat_indices.ts'
import type { EsApiDefinition } from '../types.ts'

export const catIndicesApis: EsApiDefinition[] = [
 {
   name: "indices",
   namespace: "cat",
   description: "Get index information.",
   method: "GET",
   path: "/_cat/indices/{index}",
   input: CatIndicesRequest,
   responseType: 'text',
 },
]
