/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { CcrFollowRequest } from '@elastic/es-schemas/ccr_follow.js'
import type { EsApiDefinition } from '../types.ts'

export const ccrFollowApis: EsApiDefinition[] = [
 {
  name: "follow",
  namespace: "ccr",
  description: "Create a follower.",
  method: "PUT",
  path: "/{index}/_ccr/follow",
  input: CcrFollowRequest,
 },
]
