/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { CcrUnfollowRequest } from '@elastic/es-schemas/ccr_unfollow.js'
import type { EsApiDefinition } from '../types.ts'

export const ccrUnfollowApis: EsApiDefinition[] = [
 {
  name: "unfollow",
  namespace: "ccr",
  description: "Unfollow an index.",
  method: "POST",
  path: "/{index}/_ccr/unfollow",
  input: CcrUnfollowRequest,
 },
]
