/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { CcrFollowInfoRequest } from '@elastic/es-schemas/ccr_follow_info.js'
import type { EsApiDefinition } from '../types.ts'

export const ccrFollowInfoApis: EsApiDefinition[] = [
 {
  name: "follow-info",
  namespace: "ccr",
  description: "Get follower information.",
  method: "GET",
  path: "/{index}/_ccr/info",
  input: CcrFollowInfoRequest,
 },
]
