/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { CcrPutAutoFollowPatternRequest } from '@elastic/es-schemas/ccr_put_auto_follow_pattern.js'
import type { EsApiDefinition } from '../types.ts'

export const ccrPutAutoFollowPatternApis: EsApiDefinition[] = [
 {
  name: "put-auto-follow-pattern",
  namespace: "ccr",
  description: "Create or update auto-follow patterns.",
  method: "PUT",
  path: "/_ccr/auto_follow/{name}",
  input: CcrPutAutoFollowPatternRequest,
 },
]
