/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { ClearScrollRequest } from '@elastic/es-schemas/clear_scroll.js'
import type { EsApiDefinition } from '../types.ts'

export const clearScrollApis: EsApiDefinition[] = [
 {
  name: "clear-scroll",
  description: "Clear a scrolling search.",
  method: "DELETE",
  path: "/_search/scroll",
  input: ClearScrollRequest,
 },
]
