/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ClosePointInTimeRequest } from './schemas/close_point_in_time.ts'
import type { EsApiDefinition } from '../types.ts'

export const closePointInTimeApis: EsApiDefinition[] = [
 {
   name: "close-point-in-time",
   description: "Close a point in time.",
   method: "DELETE",
   path: "/_pit",
   input: ClosePointInTimeRequest,
 },
]
