/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { ClusterExistsComponentTemplateRequest } from '@elastic/es-schemas/cluster_exists_component_template.js'
import type { EsApiDefinition } from '../types.ts'

export const clusterExistsComponentTemplateApis: EsApiDefinition[] = [
 {
  name: "exists-component-template",
  namespace: "cluster",
  description: "Check component templates.",
  method: "HEAD",
  path: "/_component_template/{name}",
  input: ClusterExistsComponentTemplateRequest,
 },
]
