/**
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { ClusterDeleteComponentTemplateRequest, ClusterExistsComponentTemplateRequest, ClusterGetComponentTemplateRequest, ClusterInfoRequest, ClusterPutComponentTemplateRequest } from './schemas/cluster.ts'
import type { EsApiDefinition } from '../types.ts'

export const clusterApis: EsApiDefinition[] = [
  {
    name: 'delete-component-template',
    namespace: 'cluster',
    description: 'Delete component templates.',
    method: 'DELETE',
    path: '/_component_template/{name}',
    input: ClusterDeleteComponentTemplateRequest
  },
  {
    name: 'exists-component-template',
    namespace: 'cluster',
    description: 'Check component templates.',
    method: 'HEAD',
    path: '/_component_template/{name}',
    input: ClusterExistsComponentTemplateRequest
  },
  {
    name: 'get-component-template',
    namespace: 'cluster',
    description: 'Get component templates.',
    method: 'GET',
    path: '/_component_template/{name}',
    input: ClusterGetComponentTemplateRequest
  },
  {
    name: 'info',
    namespace: 'cluster',
    description: 'Get cluster info.',
    method: 'GET',
    path: '/_info/{target}',
    input: ClusterInfoRequest
  },
  {
    name: 'put-component-template',
    namespace: 'cluster',
    description: 'Create or update a component template.',
    method: 'PUT',
    path: '/_component_template/{name}',
    input: ClusterPutComponentTemplateRequest
  }
]
