/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ClusterExistsComponentTemplateRequest } from './schemas/cluster_exists_component_template.ts'
import type { EsApiDefinition } from '../types.ts'

export const clusterExistsComponentTemplateApis: EsApiDefinition[] = [
 {
   name: "exists-component-template",
   namespace: "cluster",
   description: "Check component templates.",
   method: "HEAD",
   path: "/_component_template/{name}",
   input: ClusterExistsComponentTemplateRequest,
 },
]
