/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ClusterDeleteComponentTemplateRequest } from './schemas/cluster_delete_component_template.ts'
import type { EsApiDefinition } from '../types.ts'

export const clusterDeleteComponentTemplateApis: EsApiDefinition[] = [
 {
   name: "delete-component-template",
   namespace: "cluster",
   description: "Delete component templates.",
   method: "DELETE",
   path: "/_component_template/{name}",
   input: ClusterDeleteComponentTemplateRequest,
 },
]
