/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { ClusterPendingTasksRequest } from '@elastic/es-schemas/cluster_pending_tasks.js'
import type { EsApiDefinition } from '../types.ts'

export const clusterPendingTasksApis: EsApiDefinition[] = [
 {
  name: "pending-tasks",
  namespace: "cluster",
  description: "Get the pending cluster tasks.",
  method: "GET",
  path: "/_cluster/pending_tasks",
  input: ClusterPendingTasksRequest,
 },
]
