/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ClusterGetComponentTemplateRequest } from './schemas/cluster_get_component_template.ts'
import type { EsApiDefinition } from '../types.ts'

export const clusterGetComponentTemplateApis: EsApiDefinition[] = [
 {
   name: "get-component-template",
   namespace: "cluster",
   description: "Get component templates.",
   method: "GET",
   path: "/_component_template/{name}",
   input: ClusterGetComponentTemplateRequest,
 },
]
