/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { ClusterGetComponentTemplateRequest } from '@elastic/es-schemas/cluster_get_component_template.js'
import type { EsApiDefinition } from '../types.ts'

export const clusterGetComponentTemplateApis: EsApiDefinition[] = [
 {
  name: "get-component-template",
  namespace: "cluster",
  description: "Get component templates.",
  method: "GET",
  path: "/_component_template/{name}",
  input: ClusterGetComponentTemplateRequest,
 },
]
