/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { ClusterInfoRequest } from '@elastic/es-schemas/cluster_info.js'
import type { EsApiDefinition } from '../types.ts'

export const clusterInfoApis: EsApiDefinition[] = [
 {
  name: "info",
  namespace: "cluster",
  description: "Get cluster info.",
  method: "GET",
  path: "/_info/{target}",
  input: ClusterInfoRequest,
 },
]
