/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { ClusterPutComponentTemplateRequest } from '@elastic/es-schemas/cluster_put_component_template.js'
import type { EsApiDefinition } from '../types.ts'

export const clusterPutComponentTemplateApis: EsApiDefinition[] = [
 {
  name: "put-component-template",
  namespace: "cluster",
  description: "Create or update a component template.",
  method: "PUT",
  path: "/_component_template/{name}",
  input: ClusterPutComponentTemplateRequest,
 },
]
