/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ClusterInfoRequest } from './schemas/cluster_info.ts'
import type { EsApiDefinition } from '../types.ts'

export const clusterInfoApis: EsApiDefinition[] = [
 {
   name: "info",
   namespace: "cluster",
   description: "Get cluster info.",
   method: "GET",
   path: "/_info/{target}",
   input: ClusterInfoRequest,
 },
]
