/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { ClusterPutSettingsRequest } from '@elastic/es-schemas/cluster_put_settings.js'
import type { EsApiDefinition } from '../types.ts'

export const clusterPutSettingsApis: EsApiDefinition[] = [
 {
  name: "put-settings",
  namespace: "cluster",
  description: "Update the cluster settings.",
  method: "PUT",
  path: "/_cluster/settings",
  input: ClusterPutSettingsRequest,
 },
]
