/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { ClusterDeleteVotingConfigExclusionsRequest } from '@elastic/es-schemas/cluster_delete_voting_config_exclusions.js'
import type { EsApiDefinition } from '../types.ts'

export const clusterDeleteVotingConfigExclusionsApis: EsApiDefinition[] = [
 {
  name: "delete-voting-config-exclusions",
  namespace: "cluster",
  description: "Clear cluster voting config exclusions.",
  method: "DELETE",
  path: "/_cluster/voting_config_exclusions",
  input: ClusterDeleteVotingConfigExclusionsRequest,
 },
]
