/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ConnectorUpdateErrorRequest } from './schemas/connector_update_error.ts'
import type { EsApiDefinition } from '../types.ts'

export const connectorUpdateErrorApis: EsApiDefinition[] = [
 {
   name: "update-error",
   namespace: "connector",
   description: "Update the connector error field.",
   method: "PUT",
   path: "/_connector/{connector_id}/_error",
   input: ConnectorUpdateErrorRequest,
 },
]
