/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { ConnectorUpdateSchedulingRequest } from '@elastic/es-schemas/connector_update_scheduling.js'
import type { EsApiDefinition } from '../types.ts'

export const connectorUpdateSchedulingApis: EsApiDefinition[] = [
 {
  name: "update-scheduling",
  namespace: "connector",
  description: "Update the connector scheduling.",
  method: "PUT",
  path: "/_connector/{connector_id}/_scheduling",
  input: ConnectorUpdateSchedulingRequest,
 },
]
