/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { ConnectorGetRequest } from '@elastic/es-schemas/connector_get.js'
import type { EsApiDefinition } from '../types.ts'

export const connectorGetApis: EsApiDefinition[] = [
 {
  name: "get",
  namespace: "connector",
  description: "Get a connector.",
  method: "GET",
  path: "/_connector/{connector_id}",
  input: ConnectorGetRequest,
 },
]
