/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ConnectorGetRequest } from './schemas/connector_get.ts'
import type { EsApiDefinition } from '../types.ts'

export const connectorGetApis: EsApiDefinition[] = [
 {
   name: "get",
   namespace: "connector",
   description: "Get a connector.",
   method: "GET",
   path: "/_connector/{connector_id}",
   input: ConnectorGetRequest,
 },
]
