/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { ConnectorCheckInRequest, ConnectorDeleteRequest, ConnectorGetRequest, ConnectorListRequest, ConnectorPostRequest, ConnectorPutRequest, ConnectorSyncJobCancelRequest, ConnectorSyncJobDeleteRequest, ConnectorSyncJobGetRequest, ConnectorSyncJobListRequest, ConnectorSyncJobPostRequest, ConnectorUpdateActiveFilteringRequest, ConnectorUpdateApiKeyIdRequest, ConnectorUpdateConfigurationRequest, ConnectorUpdateErrorRequest, ConnectorUpdateFilteringRequest, ConnectorUpdateFilteringValidationRequest, ConnectorUpdateIndexNameRequest, ConnectorUpdateNameRequest, ConnectorUpdateNativeRequest, ConnectorUpdatePipelineRequest, ConnectorUpdateSchedulingRequest, ConnectorUpdateServiceTypeRequest, ConnectorUpdateStatusRequest } from '@elastic/es-schemas/connector.js'
import type { EsApiDefinition } from '../types.ts'

export const connectorApis: EsApiDefinition[] = [
  {
    name: 'check-in',
    namespace: 'connector',
    description: 'Check in a connector.',
    method: 'PUT',
    path: '/_connector/{connector_id}/_check_in',
    input: ConnectorCheckInRequest
  },
  {
    name: 'delete',
    namespace: 'connector',
    description: 'Delete a connector.',
    method: 'DELETE',
    path: '/_connector/{connector_id}',
    input: ConnectorDeleteRequest
  },
  {
    name: 'get',
    namespace: 'connector',
    description: 'Get a connector.',
    method: 'GET',
    path: '/_connector/{connector_id}',
    input: ConnectorGetRequest
  },
  {
    name: 'list',
    namespace: 'connector',
    description: 'Get all connectors.',
    method: 'GET',
    path: '/_connector',
    input: ConnectorListRequest
  },
  {
    name: 'post',
    namespace: 'connector',
    description: 'Create a connector.',
    method: 'POST',
    path: '/_connector',
    input: ConnectorPostRequest
  },
  {
    name: 'put',
    namespace: 'connector',
    description: 'Create or update a connector.',
    method: 'PUT',
    path: '/_connector/{connector_id}',
    input: ConnectorPutRequest
  },
  {
    name: 'sync-job-cancel',
    namespace: 'connector',
    description: 'Cancel a connector sync job.',
    method: 'PUT',
    path: '/_connector/_sync_job/{connector_sync_job_id}/_cancel',
    input: ConnectorSyncJobCancelRequest
  },
  {
    name: 'sync-job-delete',
    namespace: 'connector',
    description: 'Delete a connector sync job.',
    method: 'DELETE',
    path: '/_connector/_sync_job/{connector_sync_job_id}',
    input: ConnectorSyncJobDeleteRequest
  },
  {
    name: 'sync-job-get',
    namespace: 'connector',
    description: 'Get a connector sync job.',
    method: 'GET',
    path: '/_connector/_sync_job/{connector_sync_job_id}',
    input: ConnectorSyncJobGetRequest
  },
  {
    name: 'sync-job-list',
    namespace: 'connector',
    description: 'Get all connector sync jobs.',
    method: 'GET',
    path: '/_connector/_sync_job',
    input: ConnectorSyncJobListRequest
  },
  {
    name: 'sync-job-post',
    namespace: 'connector',
    description: 'Create a connector sync job.',
    method: 'POST',
    path: '/_connector/_sync_job',
    input: ConnectorSyncJobPostRequest
  },
  {
    name: 'update-active-filtering',
    namespace: 'connector',
    description: 'Activate the connector draft filter.',
    method: 'PUT',
    path: '/_connector/{connector_id}/_filtering/_activate',
    input: ConnectorUpdateActiveFilteringRequest
  },
  {
    name: 'update-api-key-id',
    namespace: 'connector',
    description: 'Update the connector API key ID.',
    method: 'PUT',
    path: '/_connector/{connector_id}/_api_key_id',
    input: ConnectorUpdateApiKeyIdRequest
  },
  {
    name: 'update-configuration',
    namespace: 'connector',
    description: 'Update the connector configuration.',
    method: 'PUT',
    path: '/_connector/{connector_id}/_configuration',
    input: ConnectorUpdateConfigurationRequest
  },
  {
    name: 'update-error',
    namespace: 'connector',
    description: 'Update the connector error field.',
    method: 'PUT',
    path: '/_connector/{connector_id}/_error',
    input: ConnectorUpdateErrorRequest
  },
  {
    name: 'update-filtering',
    namespace: 'connector',
    description: 'Update the connector filtering.',
    method: 'PUT',
    path: '/_connector/{connector_id}/_filtering',
    input: ConnectorUpdateFilteringRequest
  },
  {
    name: 'update-filtering-validation',
    namespace: 'connector',
    description: 'Update the connector draft filtering validation.',
    method: 'PUT',
    path: '/_connector/{connector_id}/_filtering/_validation',
    input: ConnectorUpdateFilteringValidationRequest
  },
  {
    name: 'update-index-name',
    namespace: 'connector',
    description: 'Update the connector index name.',
    method: 'PUT',
    path: '/_connector/{connector_id}/_index_name',
    input: ConnectorUpdateIndexNameRequest
  },
  {
    name: 'update-name',
    namespace: 'connector',
    description: 'Update the connector name and description.',
    method: 'PUT',
    path: '/_connector/{connector_id}/_name',
    input: ConnectorUpdateNameRequest
  },
  {
    name: 'update-native',
    namespace: 'connector',
    description: 'Update the connector is_native flag.',
    method: 'PUT',
    path: '/_connector/{connector_id}/_native',
    input: ConnectorUpdateNativeRequest
  },
  {
    name: 'update-pipeline',
    namespace: 'connector',
    description: 'Update the connector pipeline.',
    method: 'PUT',
    path: '/_connector/{connector_id}/_pipeline',
    input: ConnectorUpdatePipelineRequest
  },
  {
    name: 'update-scheduling',
    namespace: 'connector',
    description: 'Update the connector scheduling.',
    method: 'PUT',
    path: '/_connector/{connector_id}/_scheduling',
    input: ConnectorUpdateSchedulingRequest
  },
  {
    name: 'update-service-type',
    namespace: 'connector',
    description: 'Update the connector service type.',
    method: 'PUT',
    path: '/_connector/{connector_id}/_service_type',
    input: ConnectorUpdateServiceTypeRequest
  },
  {
    name: 'update-status',
    namespace: 'connector',
    description: 'Update the connector status.',
    method: 'PUT',
    path: '/_connector/{connector_id}/_status',
    input: ConnectorUpdateStatusRequest
  }
]
