/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ConnectorUpdateStatusRequest } from './schemas/connector_update_status.ts'
import type { EsApiDefinition } from '../types.ts'

export const connectorUpdateStatusApis: EsApiDefinition[] = [
 {
   name: "update-status",
   namespace: "connector",
   description: "Update the connector status.",
   method: "PUT",
   path: "/_connector/{connector_id}/_status",
   input: ConnectorUpdateStatusRequest,
 },
]
