/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ConnectorUpdateNameRequest } from './schemas/connector_update_name.ts'
import type { EsApiDefinition } from '../types.ts'

export const connectorUpdateNameApis: EsApiDefinition[] = [
 {
   name: "update-name",
   namespace: "connector",
   description: "Update the connector name and description.",
   method: "PUT",
   path: "/_connector/{connector_id}/_name",
   input: ConnectorUpdateNameRequest,
 },
]
