/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { ConnectorPutRequest } from '@elastic/es-schemas/connector_put.js'
import type { EsApiDefinition } from '../types.ts'

export const connectorPutApis: EsApiDefinition[] = [
 {
  name: "put",
  namespace: "connector",
  description: "Create or update a connector.",
  method: "PUT",
  path: "/_connector/{connector_id}",
  input: ConnectorPutRequest,
 },
]
