/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ConnectorSyncJobListRequest } from './schemas/connector_sync_job_list.ts'
import type { EsApiDefinition } from '../types.ts'

export const connectorSyncJobListApis: EsApiDefinition[] = [
 {
   name: "sync-job-list",
   namespace: "connector",
   description: "Get all connector sync jobs.",
   method: "GET",
   path: "/_connector/_sync_job",
   input: ConnectorSyncJobListRequest,
 },
]
