/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ConnectorPutRequest } from './schemas/connector_put.ts'
import type { EsApiDefinition } from '../types.ts'

export const connectorPutApis: EsApiDefinition[] = [
 {
   name: "put",
   namespace: "connector",
   description: "Create or update a connector.",
   method: "PUT",
   path: "/_connector/{connector_id}",
   input: ConnectorPutRequest,
 },
]
