/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { ConnectorSyncJobGetRequest } from '@elastic/es-schemas/connector_sync_job_get.js'
import type { EsApiDefinition } from '../types.ts'

export const connectorSyncJobGetApis: EsApiDefinition[] = [
 {
  name: "sync-job-get",
  namespace: "connector",
  description: "Get a connector sync job.",
  method: "GET",
  path: "/_connector/_sync_job/{connector_sync_job_id}",
  input: ConnectorSyncJobGetRequest,
 },
]
