/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ConnectorUpdatePipelineRequest } from './schemas/connector_update_pipeline.ts'
import type { EsApiDefinition } from '../types.ts'

export const connectorUpdatePipelineApis: EsApiDefinition[] = [
 {
   name: "update-pipeline",
   namespace: "connector",
   description: "Update the connector pipeline.",
   method: "PUT",
   path: "/_connector/{connector_id}/_pipeline",
   input: ConnectorUpdatePipelineRequest,
 },
]
