/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ConnectorSyncJobDeleteRequest } from './schemas/connector_sync_job_delete.ts'
import type { EsApiDefinition } from '../types.ts'

export const connectorSyncJobDeleteApis: EsApiDefinition[] = [
 {
   name: "sync-job-delete",
   namespace: "connector",
   description: "Delete a connector sync job.",
   method: "DELETE",
   path: "/_connector/_sync_job/{connector_sync_job_id}",
   input: ConnectorSyncJobDeleteRequest,
 },
]
