/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { ConnectorUpdateStatusRequest } from '@elastic/es-schemas/connector_update_status.js'
import type { EsApiDefinition } from '../types.ts'

export const connectorUpdateStatusApis: EsApiDefinition[] = [
 {
  name: "update-status",
  namespace: "connector",
  description: "Update the connector status.",
  method: "PUT",
  path: "/_connector/{connector_id}/_status",
  input: ConnectorUpdateStatusRequest,
 },
]
