/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ConnectorCheckInRequest } from './schemas/connector_check_in.ts'
import type { EsApiDefinition } from '../types.ts'

export const connectorCheckInApis: EsApiDefinition[] = [
 {
   name: "check-in",
   namespace: "connector",
   description: "Check in a connector.",
   method: "PUT",
   path: "/_connector/{connector_id}/_check_in",
   input: ConnectorCheckInRequest,
 },
]
