/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ConnectorUpdateIndexNameRequest } from './schemas/connector_update_index_name.ts'
import type { EsApiDefinition } from '../types.ts'

export const connectorUpdateIndexNameApis: EsApiDefinition[] = [
 {
   name: "update-index-name",
   namespace: "connector",
   description: "Update the connector index name.",
   method: "PUT",
   path: "/_connector/{connector_id}/_index_name",
   input: ConnectorUpdateIndexNameRequest,
 },
]
