/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ConnectorUpdateServiceTypeRequest } from './schemas/connector_update_service_type.ts'
import type { EsApiDefinition } from '../types.ts'

export const connectorUpdateServiceTypeApis: EsApiDefinition[] = [
 {
   name: "update-service-type",
   namespace: "connector",
   description: "Update the connector service type.",
   method: "PUT",
   path: "/_connector/{connector_id}/_service_type",
   input: ConnectorUpdateServiceTypeRequest,
 },
]
