/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { ConnectorPostRequest } from '@elastic/es-schemas/connector_post.js'
import type { EsApiDefinition } from '../types.ts'

export const connectorPostApis: EsApiDefinition[] = [
 {
  name: "post",
  namespace: "connector",
  description: "Create a connector.",
  method: "POST",
  path: "/_connector",
  input: ConnectorPostRequest,
 },
]
