/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ConnectorUpdateSchedulingRequest } from './schemas/connector_update_scheduling.ts'
import type { EsApiDefinition } from '../types.ts'

export const connectorUpdateSchedulingApis: EsApiDefinition[] = [
 {
   name: "update-scheduling",
   namespace: "connector",
   description: "Update the connector scheduling.",
   method: "PUT",
   path: "/_connector/{connector_id}/_scheduling",
   input: ConnectorUpdateSchedulingRequest,
 },
]
