/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ConnectorListRequest } from './schemas/connector_list.ts'
import type { EsApiDefinition } from '../types.ts'

export const connectorListApis: EsApiDefinition[] = [
 {
   name: "list",
   namespace: "connector",
   description: "Get all connectors.",
   method: "GET",
   path: "/_connector",
   input: ConnectorListRequest,
 },
]
