/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ConnectorSyncJobCancelRequest } from './schemas/connector_sync_job_cancel.ts'
import type { EsApiDefinition } from '../types.ts'

export const connectorSyncJobCancelApis: EsApiDefinition[] = [
 {
   name: "sync-job-cancel",
   namespace: "connector",
   description: "Cancel a connector sync job.",
   method: "PUT",
   path: "/_connector/_sync_job/{connector_sync_job_id}/_cancel",
   input: ConnectorSyncJobCancelRequest,
 },
]
