/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ConnectorSyncJobPostRequest } from './schemas/connector_sync_job_post.ts'
import type { EsApiDefinition } from '../types.ts'

export const connectorSyncJobPostApis: EsApiDefinition[] = [
 {
   name: "sync-job-post",
   namespace: "connector",
   description: "Create a connector sync job.",
   method: "POST",
   path: "/_connector/_sync_job",
   input: ConnectorSyncJobPostRequest,
 },
]
