/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ConnectorUpdateFilteringRequest } from './schemas/connector_update_filtering.ts'
import type { EsApiDefinition } from '../types.ts'

export const connectorUpdateFilteringApis: EsApiDefinition[] = [
 {
   name: "update-filtering",
   namespace: "connector",
   description: "Update the connector filtering.",
   method: "PUT",
   path: "/_connector/{connector_id}/_filtering",
   input: ConnectorUpdateFilteringRequest,
 },
]
