/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ConnectorPostRequest } from './schemas/connector_post.ts'
import type { EsApiDefinition } from '../types.ts'

export const connectorPostApis: EsApiDefinition[] = [
 {
   name: "post",
   namespace: "connector",
   description: "Create a connector.",
   method: "POST",
   path: "/_connector",
   input: ConnectorPostRequest,
 },
]
