/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { ConnectorSyncJobListRequest } from '@elastic/es-schemas/connector_sync_job_list.js'
import type { EsApiDefinition } from '../types.ts'

export const connectorSyncJobListApis: EsApiDefinition[] = [
 {
  name: "sync-job-list",
  namespace: "connector",
  description: "Get all connector sync jobs.",
  method: "GET",
  path: "/_connector/_sync_job",
  input: ConnectorSyncJobListRequest,
 },
]
