/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ConnectorUpdateConfigurationRequest } from './schemas/connector_update_configuration.ts'
import type { EsApiDefinition } from '../types.ts'

export const connectorUpdateConfigurationApis: EsApiDefinition[] = [
 {
   name: "update-configuration",
   namespace: "connector",
   description: "Update the connector configuration.",
   method: "PUT",
   path: "/_connector/{connector_id}/_configuration",
   input: ConnectorUpdateConfigurationRequest,
 },
]
