/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ConnectorUpdateActiveFilteringRequest } from './schemas/connector_update_active_filtering.ts'
import type { EsApiDefinition } from '../types.ts'

export const connectorUpdateActiveFilteringApis: EsApiDefinition[] = [
 {
   name: "update-active-filtering",
   namespace: "connector",
   description: "Activate the connector draft filter.",
   method: "PUT",
   path: "/_connector/{connector_id}/_filtering/_activate",
   input: ConnectorUpdateActiveFilteringRequest,
 },
]
