/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ConnectorSyncJobGetRequest } from './schemas/connector_sync_job_get.ts'
import type { EsApiDefinition } from '../types.ts'

export const connectorSyncJobGetApis: EsApiDefinition[] = [
 {
   name: "sync-job-get",
   namespace: "connector",
   description: "Get a connector sync job.",
   method: "GET",
   path: "/_connector/_sync_job/{connector_sync_job_id}",
   input: ConnectorSyncJobGetRequest,
 },
]
