/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ConnectorUpdateFilteringValidationRequest } from './schemas/connector_update_filtering_validation.ts'
import type { EsApiDefinition } from '../types.ts'

export const connectorUpdateFilteringValidationApis: EsApiDefinition[] = [
 {
   name: "update-filtering-validation",
   namespace: "connector",
   description: "Update the connector draft filtering validation.",
   method: "PUT",
   path: "/_connector/{connector_id}/_filtering/_validation",
   input: ConnectorUpdateFilteringValidationRequest,
 },
]
