/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { CountRequest } from './schemas/count.ts'
import type { EsApiDefinition } from '../types.ts'

export const countApis: EsApiDefinition[] = [
 {
   name: "count",
   description: "Count search results.",
   method: "POST",
   path: "/{index}/_count",
   input: CountRequest,
 },
]
