/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { DeleteScriptRequest } from '@elastic/es-schemas/_global.js'
import type { EsApiDefinition } from '../types.ts'

export const deleteScriptApis: EsApiDefinition[] = [
  {
    name: 'delete-script',
    description: 'Delete a script or search template.',
    method: 'DELETE',
    path: '/_scripts/{id}',
    input: DeleteScriptRequest
  }
]
