/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { DeleteByQueryRequest } from './schemas/delete_by_query.ts'
import type { EsApiDefinition } from '../types.ts'

export const deleteByQueryApis: EsApiDefinition[] = [
 {
   name: "delete-by-query",
   description: "Delete documents.",
   method: "POST",
   path: "/{index}/_delete_by_query",
   input: DeleteByQueryRequest,
 },
]
