/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { DeleteRequest } from './schemas/delete.ts'
import type { EsApiDefinition } from '../types.ts'

export const deleteApis: EsApiDefinition[] = [
 {
   name: "delete",
   description: "Delete a document.",
   method: "DELETE",
   path: "/{index}/_doc/{id}",
   input: DeleteRequest,
 },
]
