/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { EnrichExecutePolicyRequest } from '@elastic/es-schemas/enrich_execute_policy.js'
import type { EsApiDefinition } from '../types.ts'

export const enrichExecutePolicyApis: EsApiDefinition[] = [
 {
  name: "execute-policy",
  namespace: "enrich",
  description: "Run an enrich policy.",
  method: "PUT",
  path: "/_enrich/policy/{name}/_execute",
  input: EnrichExecutePolicyRequest,
 },
]
