/**
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { EnrichDeletePolicyRequest, EnrichExecutePolicyRequest, EnrichGetPolicyRequest, EnrichPutPolicyRequest } from './schemas/enrich.ts'
import type { EsApiDefinition } from '../types.ts'

export const enrichApis: EsApiDefinition[] = [
  {
    name: 'delete-policy',
    namespace: 'enrich',
    description: 'Delete an enrich policy.',
    method: 'DELETE',
    path: '/_enrich/policy/{name}',
    input: EnrichDeletePolicyRequest
  },
  {
    name: 'execute-policy',
    namespace: 'enrich',
    description: 'Run an enrich policy.',
    method: 'PUT',
    path: '/_enrich/policy/{name}/_execute',
    input: EnrichExecutePolicyRequest
  },
  {
    name: 'get-policy',
    namespace: 'enrich',
    description: 'Get an enrich policy.',
    method: 'GET',
    path: '/_enrich/policy/{name}',
    input: EnrichGetPolicyRequest
  },
  {
    name: 'put-policy',
    namespace: 'enrich',
    description: 'Create an enrich policy.',
    method: 'PUT',
    path: '/_enrich/policy/{name}',
    input: EnrichPutPolicyRequest
  }
]
