/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { EnrichGetPolicyRequest } from './schemas/enrich_get_policy.ts'
import type { EsApiDefinition } from '../types.ts'

export const enrichGetPolicyApis: EsApiDefinition[] = [
 {
   name: "get-policy",
   namespace: "enrich",
   description: "Get an enrich policy.",
   method: "GET",
   path: "/_enrich/policy/{name}",
   input: EnrichGetPolicyRequest,
 },
]
