/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { EnrichPutPolicyRequest } from './schemas/enrich_put_policy.ts'
import type { EsApiDefinition } from '../types.ts'

export const enrichPutPolicyApis: EsApiDefinition[] = [
 {
   name: "put-policy",
   namespace: "enrich",
   description: "Create an enrich policy.",
   method: "PUT",
   path: "/_enrich/policy/{name}",
   input: EnrichPutPolicyRequest,
 },
]
