/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { EnrichDeletePolicyRequest } from '@elastic/es-schemas/enrich_delete_policy.js'
import type { EsApiDefinition } from '../types.ts'

export const enrichDeletePolicyApis: EsApiDefinition[] = [
 {
  name: "delete-policy",
  namespace: "enrich",
  description: "Delete an enrich policy.",
  method: "DELETE",
  path: "/_enrich/policy/{name}",
  input: EnrichDeletePolicyRequest,
 },
]
