/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { EnrichDeletePolicyRequest } from './schemas/enrich_delete_policy.ts'
import type { EsApiDefinition } from '../types.ts'

export const enrichDeletePolicyApis: EsApiDefinition[] = [
 {
   name: "delete-policy",
   namespace: "enrich",
   description: "Delete an enrich policy.",
   method: "DELETE",
   path: "/_enrich/policy/{name}",
   input: EnrichDeletePolicyRequest,
 },
]
