/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { EnrichExecutePolicyRequest } from './schemas/enrich_execute_policy.ts'
import type { EsApiDefinition } from '../types.ts'

export const enrichExecutePolicyApis: EsApiDefinition[] = [
 {
   name: "execute-policy",
   namespace: "enrich",
   description: "Run an enrich policy.",
   method: "PUT",
   path: "/_enrich/policy/{name}/_execute",
   input: EnrichExecutePolicyRequest,
 },
]
