/**
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { EqlDeleteRequest, EqlGetRequest, EqlGetStatusRequest, EqlSearchRequest } from './schemas/eql.ts'
import type { EsApiDefinition } from '../types.ts'

export const eqlApis: EsApiDefinition[] = [
  {
    name: 'delete',
    namespace: 'eql',
    description: 'Delete an async EQL search.',
    method: 'DELETE',
    path: '/_eql/search/{id}',
    input: EqlDeleteRequest
  },
  {
    name: 'get',
    namespace: 'eql',
    description: 'Get async EQL search results.',
    method: 'GET',
    path: '/_eql/search/{id}',
    input: EqlGetRequest
  },
  {
    name: 'get-status',
    namespace: 'eql',
    description: 'Get the async EQL status.',
    method: 'GET',
    path: '/_eql/search/status/{id}',
    input: EqlGetStatusRequest
  },
  {
    name: 'search',
    namespace: 'eql',
    description: 'Get EQL search results.',
    method: 'GET',
    path: '/{index}/_eql/search',
    input: EqlSearchRequest
  }
]
