/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { EqlSearchRequest } from '@elastic/es-schemas/eql_search.js'
import type { EsApiDefinition } from '../types.ts'

export const eqlSearchApis: EsApiDefinition[] = [
 {
  name: "search",
  namespace: "eql",
  description: "Get EQL search results.",
  method: "GET",
  path: "/{index}/_eql/search",
  input: EqlSearchRequest,
 },
]
