/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { EqlGetStatusRequest } from './schemas/eql_get_status.ts'
import type { EsApiDefinition } from '../types.ts'

export const eqlGetStatusApis: EsApiDefinition[] = [
 {
   name: "get-status",
   namespace: "eql",
   description: "Get the async EQL status.",
   method: "GET",
   path: "/_eql/search/status/{id}",
   input: EqlGetStatusRequest,
 },
]
