/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { EqlDeleteRequest } from './schemas/eql_delete.ts'
import type { EsApiDefinition } from '../types.ts'

export const eqlDeleteApis: EsApiDefinition[] = [
 {
   name: "delete",
   namespace: "eql",
   description: "Delete an async EQL search.",
   method: "DELETE",
   path: "/_eql/search/{id}",
   input: EqlDeleteRequest,
 },
]
