/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { EqlGetRequest } from './schemas/eql_get.ts'
import type { EsApiDefinition } from '../types.ts'

export const eqlGetApis: EsApiDefinition[] = [
 {
   name: "get",
   namespace: "eql",
   description: "Get async EQL search results.",
   method: "GET",
   path: "/_eql/search/{id}",
   input: EqlGetRequest,
 },
]
