/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { EqlSearchRequest } from './schemas/eql_search.ts'
import type { EsApiDefinition } from '../types.ts'

export const eqlSearchApis: EsApiDefinition[] = [
 {
   name: "search",
   namespace: "eql",
   description: "Get EQL search results.",
   method: "GET",
   path: "/{index}/_eql/search",
   input: EqlSearchRequest,
 },
]
