/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { EsqlDeleteViewRequest, EsqlGetQueryRequest, EsqlGetViewRequest, EsqlListQueriesRequest, EsqlPutViewRequest, EsqlQueryRequest } from '@elastic/es-schemas/esql.js'
import type { EsApiDefinition } from '../types.ts'

export const esqlApis: EsApiDefinition[] = [
  {
    name: 'delete-view',
    namespace: 'esql',
    description: 'Delete an ES|QL view.',
    method: 'DELETE',
    path: '/_query/view/{name}',
    input: EsqlDeleteViewRequest
  },
  {
    name: 'get-query',
    namespace: 'esql',
    description: 'Get a specific running ES|QL query information.',
    method: 'GET',
    path: '/_query/queries/{id}',
    input: EsqlGetQueryRequest
  },
  {
    name: 'get-view',
    namespace: 'esql',
    description: 'Get an ES|QL view.',
    method: 'GET',
    path: '/_query/view/{name}',
    input: EsqlGetViewRequest
  },
  {
    name: 'list-queries',
    namespace: 'esql',
    description: 'Get running ES|QL queries information.',
    method: 'GET',
    path: '/_query/queries',
    input: EsqlListQueriesRequest
  },
  {
    name: 'put-view',
    namespace: 'esql',
    description: 'Create or update an ES|QL view.',
    method: 'PUT',
    path: '/_query/view/{name}',
    input: EsqlPutViewRequest
  },
  {
    name: 'query',
    namespace: 'esql',
    description: 'Run an ES|QL query.',
    method: 'POST',
    path: '/_query',
    input: EsqlQueryRequest
  }
]
