/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { EsqlDeleteViewRequest } from './schemas/esql_delete_view.ts'
import type { EsApiDefinition } from '../types.ts'

export const esqlDeleteViewApis: EsApiDefinition[] = [
 {
   name: "delete-view",
   namespace: "esql",
   description: "Delete an ES|QL view.",
   method: "DELETE",
   path: "/_query/view/{name}",
   input: EsqlDeleteViewRequest,
 },
]
