/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { EsqlQueryRequest } from '@elastic/es-schemas/esql_query.js'
import type { EsApiDefinition } from '../types.ts'

export const esqlQueryApis: EsApiDefinition[] = [
 {
  name: "query",
  namespace: "esql",
  description: "Run an ES|QL query.",
  method: "POST",
  path: "/_query",
  input: EsqlQueryRequest,
 },
]
