/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { EsqlListQueriesRequest } from './schemas/esql_list_queries.ts'
import type { EsApiDefinition } from '../types.ts'

export const esqlListQueriesApis: EsApiDefinition[] = [
 {
   name: "list-queries",
   namespace: "esql",
   description: "Get running ES|QL queries information.",
   method: "GET",
   path: "/_query/queries",
   input: EsqlListQueriesRequest,
 },
]
