/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { EsqlPutViewRequest } from './schemas/esql_put_view.ts'
import type { EsApiDefinition } from '../types.ts'

export const esqlPutViewApis: EsApiDefinition[] = [
 {
   name: "put-view",
   namespace: "esql",
   description: "Create or update an ES|QL view.",
   method: "PUT",
   path: "/_query/view/{name}",
   input: EsqlPutViewRequest,
 },
]
