/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { EsqlGetQueryRequest } from './schemas/esql_get_query.ts'
import type { EsApiDefinition } from '../types.ts'

export const esqlGetQueryApis: EsApiDefinition[] = [
 {
   name: "get-query",
   namespace: "esql",
   description: "Get a specific running ES|QL query information.",
   method: "GET",
   path: "/_query/queries/{id}",
   input: EsqlGetQueryRequest,
 },
]
