/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { EsqlQueryRequest } from './schemas/esql_query.ts'
import type { EsApiDefinition } from '../types.ts'

export const esqlQueryApis: EsApiDefinition[] = [
 {
   name: "query",
   namespace: "esql",
   description: "Run an ES|QL query.",
   method: "POST",
   path: "/_query",
   input: EsqlQueryRequest,
 },
]
