/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { EsqlGetQueryRequest } from '@elastic/es-schemas/esql_get_query.js'
import type { EsApiDefinition } from '../types.ts'

export const esqlGetQueryApis: EsApiDefinition[] = [
 {
  name: "get-query",
  namespace: "esql",
  description: "Get a specific running ES|QL query information.",
  method: "GET",
  path: "/_query/queries/{id}",
  input: EsqlGetQueryRequest,
 },
]
