/**
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { EsqlGetQueryRequest, EsqlListQueriesRequest, EsqlQueryRequest } from './schemas/esql.ts'
import type { EsApiDefinition } from '../types.ts'

export const esqlApis: EsApiDefinition[] = [
  {
    name: 'get-query',
    namespace: 'esql',
    description: 'Get a specific running ES|QL query information.',
    method: 'GET',
    path: '/_query/queries/{id}',
    input: EsqlGetQueryRequest
  },
  {
    name: 'list-queries',
    namespace: 'esql',
    description: 'Get running ES|QL queries information.',
    method: 'GET',
    path: '/_query/queries',
    input: EsqlListQueriesRequest
  },
  {
    name: 'query',
    namespace: 'esql',
    description: 'Run an ES|QL query.',
    method: 'POST',
    path: '/_query',
    input: EsqlQueryRequest
  }
]
