/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { ExistsRequest } from '@elastic/es-schemas/_global.exists.js'
import type { EsApiDefinition } from '../types.ts'

export const existsApis: EsApiDefinition[] = [
 {
  name: "exists",
  description: "Check a document.",
  method: "HEAD",
  path: "/{index}/_doc/{id}",
  input: ExistsRequest,
 },
]
