/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ExistsSourceRequest } from './schemas/exists_source.ts'
import type { EsApiDefinition } from '../types.ts'

export const existsSourceApis: EsApiDefinition[] = [
 {
   name: "exists-source",
   description: "Check for a document source.",
   method: "HEAD",
   path: "/{index}/_source/{id}",
   input: ExistsSourceRequest,
 },
]
