/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ExistsRequest } from './schemas/exists.ts'
import type { EsApiDefinition } from '../types.ts'

export const existsApis: EsApiDefinition[] = [
 {
   name: "exists",
   description: "Check a document.",
   method: "HEAD",
   path: "/{index}/_doc/{id}",
   input: ExistsRequest,
 },
]
