/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ExplainRequest } from './schemas/explain.ts'
import type { EsApiDefinition } from '../types.ts'

export const explainApis: EsApiDefinition[] = [
 {
   name: "explain",
   description: "Explain a document match result.",
   method: "GET",
   path: "/{index}/_explain/{id}",
   input: ExplainRequest,
 },
]
