/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { FeaturesGetFeaturesRequest } from '@elastic/es-schemas/features_get_features.js'
import type { EsApiDefinition } from '../types.ts'

export const featuresGetFeaturesApis: EsApiDefinition[] = [
 {
  name: "get-features",
  namespace: "features",
  description: "Get the features.",
  method: "GET",
  path: "/_features",
  input: FeaturesGetFeaturesRequest,
 },
]
