/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { FieldCapsRequest } from './schemas/_global.ts'
import type { EsApiDefinition } from '../types.ts'

export const fieldCapsApis: EsApiDefinition[] = [
  {
    name: 'field-caps',
    description: 'Get the field capabilities.',
    method: 'GET',
    path: '/{index}/_field_caps',
    input: FieldCapsRequest
  }
]
