/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { FieldCapsRequest } from '@elastic/es-schemas/field_caps.js'
import type { EsApiDefinition } from '../types.ts'

export const fieldCapsApis: EsApiDefinition[] = [
 {
  name: "field-caps",
  description: "Get the field capabilities.",
  method: "GET",
  path: "/{index}/_field_caps",
  input: FieldCapsRequest,
 },
]
