/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { FieldCapsRequest } from './schemas/field_caps.ts'
import type { EsApiDefinition } from '../types.ts'

export const fieldCapsApis: EsApiDefinition[] = [
 {
   name: "field-caps",
   description: "Get the field capabilities.",
   method: "GET",
   path: "/{index}/_field_caps",
   input: FieldCapsRequest,
 },
]
