/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { FleetGlobalCheckpointsRequest } from '@elastic/es-schemas/fleet_global_checkpoints.js'
import type { EsApiDefinition } from '../types.ts'

export const fleetGlobalCheckpointsApis: EsApiDefinition[] = [
 {
  name: "global-checkpoints",
  namespace: "fleet",
  description: "Get global checkpoints.",
  method: "GET",
  path: "/{index}/_fleet/global_checkpoints",
  input: FleetGlobalCheckpointsRequest,
 },
]
