/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { GetRequest } from './schemas/get.ts'
import type { EsApiDefinition } from '../types.ts'

export const getApis: EsApiDefinition[] = [
 {
   name: "get",
   description: "Get a document by its ID.",
   method: "GET",
   path: "/{index}/_doc/{id}",
   input: GetRequest,
 },
]
