/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { GetScriptRequest } from '@elastic/es-schemas/get_script.js'
import type { EsApiDefinition } from '../types.ts'

export const getScriptApis: EsApiDefinition[] = [
 {
  name: "get-script",
  description: "Get a script or search template.",
  method: "GET",
  path: "/_scripts/{id}",
  input: GetScriptRequest,
 },
]
