/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { GetSourceRequest } from './schemas/get_source.ts'
import type { EsApiDefinition } from '../types.ts'

export const getSourceApis: EsApiDefinition[] = [
 {
   name: "get-source",
   description: "Get a document's source.",
   method: "GET",
   path: "/{index}/_source/{id}",
   input: GetSourceRequest,
 },
]
