/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { GetScriptContextRequest } from '@elastic/es-schemas/get_script_context.js'
import type { EsApiDefinition } from '../types.ts'

export const getScriptContextApis: EsApiDefinition[] = [
 {
  name: "get-script-context",
  description: "Get script contexts.",
  method: "GET",
  path: "/_script_context",
  input: GetScriptContextRequest,
 },
]
