/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { GetScriptRequest } from './schemas/get_script.ts'
import type { EsApiDefinition } from '../types.ts'

export const getScriptApis: EsApiDefinition[] = [
 {
   name: "get-script",
   description: "Get a script or search template.",
   method: "GET",
   path: "/_scripts/{id}",
   input: GetScriptRequest,
 },
]
