/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { GraphExploreRequest } from '@elastic/es-schemas/graph_explore.js'
import type { EsApiDefinition } from '../types.ts'

export const graphExploreApis: EsApiDefinition[] = [
 {
  name: "explore",
  namespace: "graph",
  description: "Explore graph analytics.",
  method: "GET",
  path: "/{index}/_graph/explore",
  input: GraphExploreRequest,
 },
]
