/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IlmRemovePolicyRequest } from '@elastic/es-schemas/ilm_remove_policy.js'
import type { EsApiDefinition } from '../types.ts'

export const ilmRemovePolicyApis: EsApiDefinition[] = [
 {
  name: "remove-policy",
  namespace: "ilm",
  description: "Remove policies from an index.",
  method: "POST",
  path: "/{index}/_ilm/remove",
  input: IlmRemovePolicyRequest,
 },
]
