/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IlmMoveToStepRequest } from '@elastic/es-schemas/ilm_move_to_step.js'
import type { EsApiDefinition } from '../types.ts'

export const ilmMoveToStepApis: EsApiDefinition[] = [
 {
  name: "move-to-step",
  namespace: "ilm",
  description: "Move to a lifecycle step.",
  method: "POST",
  path: "/_ilm/move/{index}",
  input: IlmMoveToStepRequest,
 },
]
