/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IlmStartRequest } from '@elastic/es-schemas/ilm_start.js'
import type { EsApiDefinition } from '../types.ts'

export const ilmStartApis: EsApiDefinition[] = [
 {
  name: "start",
  namespace: "ilm",
  description: "Start the ILM plugin.",
  method: "POST",
  path: "/_ilm/start",
  input: IlmStartRequest,
 },
]
