/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndexRequest } from './schemas/index.ts'
import type { EsApiDefinition } from '../types.ts'

export const indexApis: EsApiDefinition[] = [
 {
   name: "index",
   description: "Create or update a document in an index.",
   method: "PUT",
   path: "/{index}/_doc/{id}",
   input: IndexRequest,
 },
]
