/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IndicesPutAliasRequest } from '@elastic/es-schemas/indices_put_alias.js'
import type { EsApiDefinition } from '../types.ts'

export const indicesPutAliasApis: EsApiDefinition[] = [
 {
  name: "put-alias",
  namespace: "indices",
  description: "Create or update an alias.",
  method: "PUT",
  path: "/{index}/_aliases/{name}",
  input: IndicesPutAliasRequest,
 },
]
