/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesPutMappingRequest } from './schemas/indices_put_mapping.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesPutMappingApis: EsApiDefinition[] = [
 {
   name: "put-mapping",
   namespace: "indices",
   description: "Update field mappings.",
   method: "PUT",
   path: "/{index}/_mapping",
   input: IndicesPutMappingRequest,
 },
]
