/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesDeleteAliasRequest } from './schemas/indices_delete_alias.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesDeleteAliasApis: EsApiDefinition[] = [
 {
   name: "delete-alias",
   namespace: "indices",
   description: "Delete an alias.",
   method: "DELETE",
   path: "/{index}/_aliases/{name}",
   input: IndicesDeleteAliasRequest,
 },
]
