/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesGetDataStreamRequest } from './schemas/indices_get_data_stream.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesGetDataStreamApis: EsApiDefinition[] = [
 {
   name: "get-data-stream",
   namespace: "indices",
   description: "Get data streams.",
   method: "GET",
   path: "/_data_stream/{name}",
   input: IndicesGetDataStreamRequest,
 },
]
