/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesGetDataLifecycleRequest } from './schemas/indices_get_data_lifecycle.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesGetDataLifecycleApis: EsApiDefinition[] = [
 {
   name: "get-data-lifecycle",
   namespace: "indices",
   description: "Get data stream lifecycles.",
   method: "GET",
   path: "/_data_stream/{name}/_lifecycle",
   input: IndicesGetDataLifecycleRequest,
 },
]
