/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesPutAliasRequest } from './schemas/indices_put_alias.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesPutAliasApis: EsApiDefinition[] = [
 {
   name: "put-alias",
   namespace: "indices",
   description: "Create or update an alias.",
   method: "PUT",
   path: "/{index}/_aliases/{name}",
   input: IndicesPutAliasRequest,
 },
]
