/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IndicesPutSettingsRequest } from '@elastic/es-schemas/indices_put_settings.js'
import type { EsApiDefinition } from '../types.ts'

export const indicesPutSettingsApis: EsApiDefinition[] = [
 {
  name: "put-settings",
  namespace: "indices",
  description: "Update index settings.",
  method: "PUT",
  path: "/{index}/_settings",
  input: IndicesPutSettingsRequest,
 },
]
