/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesCancelMigrateReindexRequest } from './schemas/indices_cancel_migrate_reindex.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesCancelMigrateReindexApis: EsApiDefinition[] = [
 {
   name: "cancel-migrate-reindex",
   namespace: "indices",
   description: "Cancel a migration reindex operation.",
   method: "POST",
   path: "/_migration/reindex/{index}/_cancel",
   input: IndicesCancelMigrateReindexRequest,
 },
]
