/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesGetDataStreamSettingsRequest } from './schemas/indices_get_data_stream_settings.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesGetDataStreamSettingsApis: EsApiDefinition[] = [
 {
   name: "get-data-stream-settings",
   namespace: "indices",
   description: "Get data stream settings.",
   method: "GET",
   path: "/_data_stream/{name}/_settings",
   input: IndicesGetDataStreamSettingsRequest,
 },
]
