/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesGetDataStreamMappingsRequest } from './schemas/indices_get_data_stream_mappings.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesGetDataStreamMappingsApis: EsApiDefinition[] = [
 {
   name: "get-data-stream-mappings",
   namespace: "indices",
   description: "Get data stream mappings.",
   method: "GET",
   path: "/_data_stream/{name}/_mappings",
   input: IndicesGetDataStreamMappingsRequest,
 },
]
