/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IndicesStatsRequest } from '@elastic/es-schemas/indices_stats.js'
import type { EsApiDefinition } from '../types.ts'

export const indicesStatsApis: EsApiDefinition[] = [
 {
  name: "stats",
  namespace: "indices",
  description: "Get index statistics.",
  method: "GET",
  path: "/{index}/_stats/{metric}",
  input: IndicesStatsRequest,
 },
]
