/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesGetIndexTemplateRequest } from './schemas/indices_get_index_template.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesGetIndexTemplateApis: EsApiDefinition[] = [
 {
   name: "get-index-template",
   namespace: "indices",
   description: "Get index templates.",
   method: "GET",
   path: "/_index_template/{name}",
   input: IndicesGetIndexTemplateRequest,
 },
]
