/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IndicesExistsIndexTemplateRequest } from '@elastic/es-schemas/indices_exists_index_template.js'
import type { EsApiDefinition } from '../types.ts'

export const indicesExistsIndexTemplateApis: EsApiDefinition[] = [
 {
  name: "exists-index-template",
  namespace: "indices",
  description: "Check index templates.",
  method: "HEAD",
  path: "/_index_template/{name}",
  input: IndicesExistsIndexTemplateRequest,
 },
]
