/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IndicesExistsTemplateRequest } from '@elastic/es-schemas/indices_exists_template.js'
import type { EsApiDefinition } from '../types.ts'

export const indicesExistsTemplateApis: EsApiDefinition[] = [
 {
  name: "exists-template",
  namespace: "indices",
  description: "Check existence of index templates.",
  method: "HEAD",
  path: "/_template/{name}",
  input: IndicesExistsTemplateRequest,
 },
]
