/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesRefreshRequest } from './schemas/indices_refresh.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesRefreshApis: EsApiDefinition[] = [
 {
   name: "refresh",
   namespace: "indices",
   description: "Refresh an index.",
   method: "POST",
   path: "/{index}/_refresh",
   input: IndicesRefreshRequest,
 },
]
