/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesPutDataStreamOptionsRequest } from './schemas/indices_put_data_stream_options.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesPutDataStreamOptionsApis: EsApiDefinition[] = [
 {
   name: "put-data-stream-options",
   namespace: "indices",
   description: "Update data stream options.",
   method: "PUT",
   path: "/_data_stream/{name}/_options",
   input: IndicesPutDataStreamOptionsRequest,
 },
]
