/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesExistsIndexTemplateRequest } from './schemas/indices_exists_index_template.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesExistsIndexTemplateApis: EsApiDefinition[] = [
 {
   name: "exists-index-template",
   namespace: "indices",
   description: "Check index templates.",
   method: "HEAD",
   path: "/_index_template/{name}",
   input: IndicesExistsIndexTemplateRequest,
 },
]
