/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IndicesAddBlockRequest } from '@elastic/es-schemas/indices_add_block.js'
import type { EsApiDefinition } from '../types.ts'

export const indicesAddBlockApis: EsApiDefinition[] = [
 {
  name: "add-block",
  namespace: "indices",
  description: "Add an index block.",
  method: "PUT",
  path: "/{index}/_block/{block}",
  input: IndicesAddBlockRequest,
 },
]
