/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IndicesGetRequest } from '@elastic/es-schemas/indices_get.js'
import type { EsApiDefinition } from '../types.ts'

export const indicesGetApis: EsApiDefinition[] = [
 {
  name: "get",
  namespace: "indices",
  description: "Get index information.",
  method: "GET",
  path: "/{index}",
  input: IndicesGetRequest,
 },
]
