/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IndicesGetTemplateRequest } from '@elastic/es-schemas/indices_get_template.js'
import type { EsApiDefinition } from '../types.ts'

export const indicesGetTemplateApis: EsApiDefinition[] = [
 {
  name: "get-template",
  namespace: "indices",
  description: "Get legacy index templates.",
  method: "GET",
  path: "/_template/{name}",
  input: IndicesGetTemplateRequest,
 },
]
