/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesDeleteDataStreamRequest } from './schemas/indices_delete_data_stream.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesDeleteDataStreamApis: EsApiDefinition[] = [
 {
   name: "delete-data-stream",
   namespace: "indices",
   description: "Delete data streams.",
   method: "DELETE",
   path: "/_data_stream/{name}",
   input: IndicesDeleteDataStreamRequest,
 },
]
