/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesMigrateToDataStreamRequest } from './schemas/indices_migrate_to_data_stream.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesMigrateToDataStreamApis: EsApiDefinition[] = [
 {
   name: "migrate-to-data-stream",
   namespace: "indices",
   description: "Convert an index alias to a data stream.",
   method: "POST",
   path: "/_data_stream/_migrate/{name}",
   input: IndicesMigrateToDataStreamRequest,
 },
]
