/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesAddBlockRequest } from './schemas/indices_add_block.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesAddBlockApis: EsApiDefinition[] = [
 {
   name: "add-block",
   namespace: "indices",
   description: "Add an index block.",
   method: "PUT",
   path: "/{index}/_block/{block}",
   input: IndicesAddBlockRequest,
 },
]
