/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesGetRequest } from './schemas/indices_get.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesGetApis: EsApiDefinition[] = [
 {
   name: "get",
   namespace: "indices",
   description: "Get index information.",
   method: "GET",
   path: "/{index}",
   input: IndicesGetRequest,
 },
]
