/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IndicesDiskUsageRequest } from '@elastic/es-schemas/indices_disk_usage.js'
import type { EsApiDefinition } from '../types.ts'

export const indicesDiskUsageApis: EsApiDefinition[] = [
 {
  name: "disk-usage",
  namespace: "indices",
  description: "Analyze the index disk usage.",
  method: "POST",
  path: "/{index}/_disk_usage",
  input: IndicesDiskUsageRequest,
 },
]
