/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesSimulateTemplateRequest } from './schemas/indices_simulate_template.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesSimulateTemplateApis: EsApiDefinition[] = [
 {
   name: "simulate-template",
   namespace: "indices",
   description: "Simulate an index template.",
   method: "POST",
   path: "/_index_template/_simulate/{name}",
   input: IndicesSimulateTemplateRequest,
 },
]
