/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesExistsRequest } from './schemas/indices_exists.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesExistsApis: EsApiDefinition[] = [
 {
   name: "exists",
   namespace: "indices",
   description: "Check indices.",
   method: "HEAD",
   path: "/{index}",
   input: IndicesExistsRequest,
 },
]
