/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesPutSettingsRequest } from './schemas/indices_put_settings.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesPutSettingsApis: EsApiDefinition[] = [
 {
   name: "put-settings",
   namespace: "indices",
   description: "Update index settings.",
   method: "PUT",
   path: "/{index}/_settings",
   input: IndicesPutSettingsRequest,
 },
]
