/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesResolveIndexRequest } from './schemas/indices_resolve_index.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesResolveIndexApis: EsApiDefinition[] = [
 {
   name: "resolve-index",
   namespace: "indices",
   description: "Resolve indices.",
   method: "GET",
   path: "/_resolve/index/{name}",
   input: IndicesResolveIndexRequest,
 },
]
