/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesModifyDataStreamRequest } from './schemas/indices_modify_data_stream.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesModifyDataStreamApis: EsApiDefinition[] = [
 {
   name: "modify-data-stream",
   namespace: "indices",
   description: "Update data streams.",
   method: "POST",
   path: "/_data_stream/_modify",
   input: IndicesModifyDataStreamRequest,
 },
]
