/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesRemoveBlockRequest } from './schemas/indices_remove_block.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesRemoveBlockApis: EsApiDefinition[] = [
 {
   name: "remove-block",
   namespace: "indices",
   description: "Remove an index block.",
   method: "DELETE",
   path: "/{index}/_block/{block}",
   input: IndicesRemoveBlockRequest,
 },
]
