/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesAnalyzeRequest } from './schemas/indices_analyze.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesAnalyzeApis: EsApiDefinition[] = [
 {
   name: "analyze",
   namespace: "indices",
   description: "Get tokens from text analysis.",
   method: "GET",
   path: "/{index}/_analyze",
   input: IndicesAnalyzeRequest,
 },
]
