/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IndicesReloadSearchAnalyzersRequest } from '@elastic/es-schemas/indices_reload_search_analyzers.js'
import type { EsApiDefinition } from '../types.ts'

export const indicesReloadSearchAnalyzersApis: EsApiDefinition[] = [
 {
  name: "reload-search-analyzers",
  namespace: "indices",
  description: "Reload search analyzers.",
  method: "GET",
  path: "/{index}/_reload_search_analyzers",
  input: IndicesReloadSearchAnalyzersRequest,
 },
]
