/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesCreateFromRequest } from './schemas/indices_create_from.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesCreateFromApis: EsApiDefinition[] = [
 {
   name: "create-from",
   namespace: "indices",
   description: "Create an index from a source index.",
   method: "PUT",
   path: "/_create_from/{source}/{dest}",
   input: IndicesCreateFromRequest,
 },
]
