/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesRolloverRequest } from './schemas/indices_rollover.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesRolloverApis: EsApiDefinition[] = [
 {
   name: "rollover",
   namespace: "indices",
   description: "Roll over to a new index.",
   method: "POST",
   path: "/{alias}/_rollover/{new_index}",
   input: IndicesRolloverRequest,
 },
]
