/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IndicesAddBlockRequest, IndicesAnalyzeRequest, IndicesCancelMigrateReindexRequest, IndicesCreateDataStreamRequest, IndicesCreateFromRequest, IndicesCreateRequest, IndicesDeleteAliasRequest, IndicesDeleteDataStreamRequest, IndicesDeleteIndexTemplateRequest, IndicesDeleteRequest, IndicesExistsAliasRequest, IndicesExistsIndexTemplateRequest, IndicesExistsRequest, IndicesExplainDataLifecycleRequest, IndicesGetAliasRequest, IndicesGetDataLifecycleRequest, IndicesGetDataStreamMappingsRequest, IndicesGetDataStreamOptionsRequest, IndicesGetDataStreamRequest, IndicesGetDataStreamSettingsRequest, IndicesGetIndexTemplateRequest, IndicesGetMappingRequest, IndicesGetMigrateReindexStatusRequest, IndicesGetRequest, IndicesGetSettingsRequest, IndicesMigrateToDataStreamRequest, IndicesModifyDataStreamRequest, IndicesPutAliasRequest, IndicesPutDataLifecycleRequest, IndicesPutDataStreamMappingsRequest, IndicesPutDataStreamOptionsRequest, IndicesPutDataStreamSettingsRequest, IndicesPutIndexTemplateRequest, IndicesPutMappingRequest, IndicesPutSettingsRequest, IndicesRefreshRequest, IndicesRemoveBlockRequest, IndicesResolveIndexRequest, IndicesRolloverRequest, IndicesSimulateIndexTemplateRequest, IndicesSimulateTemplateRequest, IndicesUpdateAliasesRequest, IndicesValidateQueryRequest } from './schemas/indices.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesApis: EsApiDefinition[] = [
  {
    name: 'add-block',
    namespace: 'indices',
    description: 'Add an index block.',
    method: 'PUT',
    path: '/{index}/_block/{block}',
    input: IndicesAddBlockRequest
  },
  {
    name: 'analyze',
    namespace: 'indices',
    description: 'Get tokens from text analysis.',
    method: 'GET',
    path: '/{index}/_analyze',
    input: IndicesAnalyzeRequest
  },
  {
    name: 'cancel-migrate-reindex',
    namespace: 'indices',
    description: 'Cancel a migration reindex operation.',
    method: 'POST',
    path: '/_migration/reindex/{index}/_cancel',
    input: IndicesCancelMigrateReindexRequest
  },
  {
    name: 'create',
    namespace: 'indices',
    description: 'Create an index.',
    method: 'PUT',
    path: '/{index}',
    input: IndicesCreateRequest
  },
  {
    name: 'create-data-stream',
    namespace: 'indices',
    description: 'Create a data stream.',
    method: 'PUT',
    path: '/_data_stream/{name}',
    input: IndicesCreateDataStreamRequest
  },
  {
    name: 'create-from',
    namespace: 'indices',
    description: 'Create an index from a source index.',
    method: 'PUT',
    path: '/_create_from/{source}/{dest}',
    input: IndicesCreateFromRequest
  },
  {
    name: 'delete',
    namespace: 'indices',
    description: 'Delete indices.',
    method: 'DELETE',
    path: '/{index}',
    input: IndicesDeleteRequest
  },
  {
    name: 'delete-alias',
    namespace: 'indices',
    description: 'Delete an alias.',
    method: 'DELETE',
    path: '/{index}/_aliases/{name}',
    input: IndicesDeleteAliasRequest
  },
  {
    name: 'delete-data-stream',
    namespace: 'indices',
    description: 'Delete data streams.',
    method: 'DELETE',
    path: '/_data_stream/{name}',
    input: IndicesDeleteDataStreamRequest
  },
  {
    name: 'delete-index-template',
    namespace: 'indices',
    description: 'Delete an index template.',
    method: 'DELETE',
    path: '/_index_template/{name}',
    input: IndicesDeleteIndexTemplateRequest
  },
  {
    name: 'exists',
    namespace: 'indices',
    description: 'Check indices.',
    method: 'HEAD',
    path: '/{index}',
    input: IndicesExistsRequest
  },
  {
    name: 'exists-alias',
    namespace: 'indices',
    description: 'Check aliases.',
    method: 'HEAD',
    path: '/{index}/_alias/{name}',
    input: IndicesExistsAliasRequest
  },
  {
    name: 'exists-index-template',
    namespace: 'indices',
    description: 'Check index templates.',
    method: 'HEAD',
    path: '/_index_template/{name}',
    input: IndicesExistsIndexTemplateRequest
  },
  {
    name: 'explain-data-lifecycle',
    namespace: 'indices',
    description: 'Get the status for a data stream lifecycle.',
    method: 'GET',
    path: '/{index}/_lifecycle/explain',
    input: IndicesExplainDataLifecycleRequest
  },
  {
    name: 'get',
    namespace: 'indices',
    description: 'Get index information.',
    method: 'GET',
    path: '/{index}',
    input: IndicesGetRequest
  },
  {
    name: 'get-alias',
    namespace: 'indices',
    description: 'Get aliases.',
    method: 'GET',
    path: '/{index}/_alias/{name}',
    input: IndicesGetAliasRequest
  },
  {
    name: 'get-data-lifecycle',
    namespace: 'indices',
    description: 'Get data stream lifecycles.',
    method: 'GET',
    path: '/_data_stream/{name}/_lifecycle',
    input: IndicesGetDataLifecycleRequest
  },
  {
    name: 'get-data-stream',
    namespace: 'indices',
    description: 'Get data streams.',
    method: 'GET',
    path: '/_data_stream/{name}',
    input: IndicesGetDataStreamRequest
  },
  {
    name: 'get-data-stream-mappings',
    namespace: 'indices',
    description: 'Get data stream mappings.',
    method: 'GET',
    path: '/_data_stream/{name}/_mappings',
    input: IndicesGetDataStreamMappingsRequest
  },
  {
    name: 'get-data-stream-options',
    namespace: 'indices',
    description: 'Get data stream options.',
    method: 'GET',
    path: '/_data_stream/{name}/_options',
    input: IndicesGetDataStreamOptionsRequest
  },
  {
    name: 'get-data-stream-settings',
    namespace: 'indices',
    description: 'Get data stream settings.',
    method: 'GET',
    path: '/_data_stream/{name}/_settings',
    input: IndicesGetDataStreamSettingsRequest
  },
  {
    name: 'get-index-template',
    namespace: 'indices',
    description: 'Get index templates.',
    method: 'GET',
    path: '/_index_template/{name}',
    input: IndicesGetIndexTemplateRequest
  },
  {
    name: 'get-mapping',
    namespace: 'indices',
    description: 'Get mapping definitions.',
    method: 'GET',
    path: '/{index}/_mapping',
    input: IndicesGetMappingRequest
  },
  {
    name: 'get-migrate-reindex-status',
    namespace: 'indices',
    description: 'Get the migration reindexing status.',
    method: 'GET',
    path: '/_migration/reindex/{index}/_status',
    input: IndicesGetMigrateReindexStatusRequest
  },
  {
    name: 'get-settings',
    namespace: 'indices',
    description: 'Get index settings.',
    method: 'GET',
    path: '/{index}/_settings/{name}',
    input: IndicesGetSettingsRequest
  },
  {
    name: 'migrate-to-data-stream',
    namespace: 'indices',
    description: 'Convert an index alias to a data stream.',
    method: 'POST',
    path: '/_data_stream/_migrate/{name}',
    input: IndicesMigrateToDataStreamRequest
  },
  {
    name: 'modify-data-stream',
    namespace: 'indices',
    description: 'Update data streams.',
    method: 'POST',
    path: '/_data_stream/_modify',
    input: IndicesModifyDataStreamRequest
  },
  {
    name: 'put-alias',
    namespace: 'indices',
    description: 'Create or update an alias.',
    method: 'PUT',
    path: '/{index}/_aliases/{name}',
    input: IndicesPutAliasRequest
  },
  {
    name: 'put-data-lifecycle',
    namespace: 'indices',
    description: 'Update data stream lifecycles.',
    method: 'PUT',
    path: '/_data_stream/{name}/_lifecycle',
    input: IndicesPutDataLifecycleRequest
  },
  {
    name: 'put-data-stream-mappings',
    namespace: 'indices',
    description: 'Update data stream mappings.',
    method: 'PUT',
    path: '/_data_stream/{name}/_mappings',
    input: IndicesPutDataStreamMappingsRequest
  },
  {
    name: 'put-data-stream-options',
    namespace: 'indices',
    description: 'Update data stream options.',
    method: 'PUT',
    path: '/_data_stream/{name}/_options',
    input: IndicesPutDataStreamOptionsRequest
  },
  {
    name: 'put-data-stream-settings',
    namespace: 'indices',
    description: 'Update data stream settings.',
    method: 'PUT',
    path: '/_data_stream/{name}/_settings',
    input: IndicesPutDataStreamSettingsRequest
  },
  {
    name: 'put-index-template',
    namespace: 'indices',
    description: 'Create or update an index template.',
    method: 'PUT',
    path: '/_index_template/{name}',
    input: IndicesPutIndexTemplateRequest
  },
  {
    name: 'put-mapping',
    namespace: 'indices',
    description: 'Update field mappings.',
    method: 'PUT',
    path: '/{index}/_mapping',
    input: IndicesPutMappingRequest
  },
  {
    name: 'put-settings',
    namespace: 'indices',
    description: 'Update index settings.',
    method: 'PUT',
    path: '/{index}/_settings',
    input: IndicesPutSettingsRequest
  },
  {
    name: 'refresh',
    namespace: 'indices',
    description: 'Refresh an index.',
    method: 'POST',
    path: '/{index}/_refresh',
    input: IndicesRefreshRequest
  },
  {
    name: 'remove-block',
    namespace: 'indices',
    description: 'Remove an index block.',
    method: 'DELETE',
    path: '/{index}/_block/{block}',
    input: IndicesRemoveBlockRequest
  },
  {
    name: 'resolve-index',
    namespace: 'indices',
    description: 'Resolve indices.',
    method: 'GET',
    path: '/_resolve/index/{name}',
    input: IndicesResolveIndexRequest
  },
  {
    name: 'rollover',
    namespace: 'indices',
    description: 'Roll over to a new index.',
    method: 'POST',
    path: '/{alias}/_rollover/{new_index}',
    input: IndicesRolloverRequest
  },
  {
    name: 'simulate-index-template',
    namespace: 'indices',
    description: 'Simulate an index.',
    method: 'POST',
    path: '/_index_template/_simulate_index/{name}',
    input: IndicesSimulateIndexTemplateRequest
  },
  {
    name: 'simulate-template',
    namespace: 'indices',
    description: 'Simulate an index template.',
    method: 'POST',
    path: '/_index_template/_simulate/{name}',
    input: IndicesSimulateTemplateRequest
  },
  {
    name: 'update-aliases',
    namespace: 'indices',
    description: 'Create or update an alias.',
    method: 'POST',
    path: '/_aliases',
    input: IndicesUpdateAliasesRequest
  },
  {
    name: 'validate-query',
    namespace: 'indices',
    description: 'Validate a query.',
    method: 'GET',
    path: '/{index}/_validate/query',
    input: IndicesValidateQueryRequest
  }
]
