/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IndicesGetMappingRequest } from '@elastic/es-schemas/indices_get_mapping.js'
import type { EsApiDefinition } from '../types.ts'

export const indicesGetMappingApis: EsApiDefinition[] = [
 {
  name: "get-mapping",
  namespace: "indices",
  description: "Get mapping definitions.",
  method: "GET",
  path: "/{index}/_mapping",
  input: IndicesGetMappingRequest,
 },
]
