/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesGetDataStreamOptionsRequest } from './schemas/indices_get_data_stream_options.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesGetDataStreamOptionsApis: EsApiDefinition[] = [
 {
   name: "get-data-stream-options",
   namespace: "indices",
   description: "Get data stream options.",
   method: "GET",
   path: "/_data_stream/{name}/_options",
   input: IndicesGetDataStreamOptionsRequest,
 },
]
