/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesCreateDataStreamRequest } from './schemas/indices_create_data_stream.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesCreateDataStreamApis: EsApiDefinition[] = [
 {
   name: "create-data-stream",
   namespace: "indices",
   description: "Create a data stream.",
   method: "PUT",
   path: "/_data_stream/{name}",
   input: IndicesCreateDataStreamRequest,
 },
]
