/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesGetSettingsRequest } from './schemas/indices_get_settings.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesGetSettingsApis: EsApiDefinition[] = [
 {
   name: "get-settings",
   namespace: "indices",
   description: "Get index settings.",
   method: "GET",
   path: "/{index}/_settings/{name}",
   input: IndicesGetSettingsRequest,
 },
]
