/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesGetMappingRequest } from './schemas/indices_get_mapping.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesGetMappingApis: EsApiDefinition[] = [
 {
   name: "get-mapping",
   namespace: "indices",
   description: "Get mapping definitions.",
   method: "GET",
   path: "/{index}/_mapping",
   input: IndicesGetMappingRequest,
 },
]
