/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesGetMigrateReindexStatusRequest } from './schemas/indices_get_migrate_reindex_status.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesGetMigrateReindexStatusApis: EsApiDefinition[] = [
 {
   name: "get-migrate-reindex-status",
   namespace: "indices",
   description: "Get the migration reindexing status.",
   method: "GET",
   path: "/_migration/reindex/{index}/_status",
   input: IndicesGetMigrateReindexStatusRequest,
 },
]
