/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IndicesGetMigrateReindexStatusRequest } from '@elastic/es-schemas/indices_get_migrate_reindex_status.js'
import type { EsApiDefinition } from '../types.ts'

export const indicesGetMigrateReindexStatusApis: EsApiDefinition[] = [
 {
  name: "get-migrate-reindex-status",
  namespace: "indices",
  description: "Get the migration reindexing status.",
  method: "GET",
  path: "/_migration/reindex/{index}/_status",
  input: IndicesGetMigrateReindexStatusRequest,
 },
]
