/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IndicesRolloverRequest } from '@elastic/es-schemas/indices_rollover.js'
import type { EsApiDefinition } from '../types.ts'

export const indicesRolloverApis: EsApiDefinition[] = [
 {
  name: "rollover",
  namespace: "indices",
  description: "Roll over to a new index.",
  method: "POST",
  path: "/{alias}/_rollover/{new_index}",
  input: IndicesRolloverRequest,
 },
]
