/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesCreateRequest } from './schemas/indices_create.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesCreateApis: EsApiDefinition[] = [
 {
   name: "create",
   namespace: "indices",
   description: "Create an index.",
   method: "PUT",
   path: "/{index}",
   input: IndicesCreateRequest,
 },
]
