/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesSimulateIndexTemplateRequest } from './schemas/indices_simulate_index_template.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesSimulateIndexTemplateApis: EsApiDefinition[] = [
 {
   name: "simulate-index-template",
   namespace: "indices",
   description: "Simulate an index.",
   method: "POST",
   path: "/_index_template/_simulate_index/{name}",
   input: IndicesSimulateIndexTemplateRequest,
 },
]
