/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IndicesShrinkRequest } from '@elastic/es-schemas/indices_shrink.js'
import type { EsApiDefinition } from '../types.ts'

export const indicesShrinkApis: EsApiDefinition[] = [
 {
  name: "shrink",
  namespace: "indices",
  description: "Shrink an index.",
  method: "PUT",
  path: "/{index}/_shrink/{target}",
  input: IndicesShrinkRequest,
 },
]
