/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IndicesDeleteRequest } from '@elastic/es-schemas/indices_delete.js'
import type { EsApiDefinition } from '../types.ts'

export const indicesDeleteApis: EsApiDefinition[] = [
 {
  name: "delete",
  namespace: "indices",
  description: "Delete indices.",
  method: "DELETE",
  path: "/{index}",
  input: IndicesDeleteRequest,
 },
]
