/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesValidateQueryRequest } from './schemas/indices_validate_query.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesValidateQueryApis: EsApiDefinition[] = [
 {
   name: "validate-query",
   namespace: "indices",
   description: "Validate a query.",
   method: "GET",
   path: "/{index}/_validate/query",
   input: IndicesValidateQueryRequest,
 },
]
