/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesPutDataStreamMappingsRequest } from './schemas/indices_put_data_stream_mappings.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesPutDataStreamMappingsApis: EsApiDefinition[] = [
 {
   name: "put-data-stream-mappings",
   namespace: "indices",
   description: "Update data stream mappings.",
   method: "PUT",
   path: "/_data_stream/{name}/_mappings",
   input: IndicesPutDataStreamMappingsRequest,
 },
]
