/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesPutDataLifecycleRequest } from './schemas/indices_put_data_lifecycle.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesPutDataLifecycleApis: EsApiDefinition[] = [
 {
   name: "put-data-lifecycle",
   namespace: "indices",
   description: "Update data stream lifecycles.",
   method: "PUT",
   path: "/_data_stream/{name}/_lifecycle",
   input: IndicesPutDataLifecycleRequest,
 },
]
