/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesUpdateAliasesRequest } from './schemas/indices_update_aliases.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesUpdateAliasesApis: EsApiDefinition[] = [
 {
   name: "update-aliases",
   namespace: "indices",
   description: "Create or update an alias.",
   method: "POST",
   path: "/_aliases",
   input: IndicesUpdateAliasesRequest,
 },
]
