/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesExplainDataLifecycleRequest } from './schemas/indices_explain_data_lifecycle.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesExplainDataLifecycleApis: EsApiDefinition[] = [
 {
   name: "explain-data-lifecycle",
   namespace: "indices",
   description: "Get the status for a data stream lifecycle.",
   method: "GET",
   path: "/{index}/_lifecycle/explain",
   input: IndicesExplainDataLifecycleRequest,
 },
]
