/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesPutIndexTemplateRequest } from './schemas/indices_put_index_template.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesPutIndexTemplateApis: EsApiDefinition[] = [
 {
   name: "put-index-template",
   namespace: "indices",
   description: "Create or update an index template.",
   method: "PUT",
   path: "/_index_template/{name}",
   input: IndicesPutIndexTemplateRequest,
 },
]
