/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IndicesRefreshRequest } from '@elastic/es-schemas/indices_refresh.js'
import type { EsApiDefinition } from '../types.ts'

export const indicesRefreshApis: EsApiDefinition[] = [
 {
  name: "refresh",
  namespace: "indices",
  description: "Refresh an index.",
  method: "POST",
  path: "/{index}/_refresh",
  input: IndicesRefreshRequest,
 },
]
