/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IndicesGetAliasRequest } from './schemas/indices_get_alias.ts'
import type { EsApiDefinition } from '../types.ts'

export const indicesGetAliasApis: EsApiDefinition[] = [
 {
   name: "get-alias",
   namespace: "indices",
   description: "Get aliases.",
   method: "GET",
   path: "/{index}/_alias/{name}",
   input: IndicesGetAliasRequest,
 },
]
