/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IndicesCloseRequest } from '@elastic/es-schemas/indices_close.js'
import type { EsApiDefinition } from '../types.ts'

export const indicesCloseApis: EsApiDefinition[] = [
 {
  name: "close",
  namespace: "indices",
  description: "Close an index.",
  method: "POST",
  path: "/{index}/_close",
  input: IndicesCloseRequest,
 },
]
