/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferenceSparseEmbeddingRequest } from './schemas/inference_sparse_embedding.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferenceSparseEmbeddingApis: EsApiDefinition[] = [
 {
   name: "sparse-embedding",
   namespace: "inference",
   description: "Perform sparse embedding inference on the service.",
   method: "POST",
   path: "/_inference/sparse_embedding/{inference_id}",
   input: InferenceSparseEmbeddingRequest,
 },
]
