/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferencePutAzureopenaiRequest } from './schemas/inference_put_azureopenai.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutAzureopenaiApis: EsApiDefinition[] = [
 {
   name: "put-azureopenai",
   namespace: "inference",
   description: "Create an Azure OpenAI inference endpoint.",
   method: "PUT",
   path: "/_inference/{task_type}/{azureopenai_inference_id}",
   input: InferencePutAzureopenaiRequest,
 },
]
