/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferencePutOpenshiftAiRequest } from './schemas/inference_put_openshift_ai.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutOpenshiftAiApis: EsApiDefinition[] = [
 {
   name: "put-openshift-ai",
   namespace: "inference",
   description: "Create an OpenShift AI inference endpoint.",
   method: "PUT",
   path: "/_inference/{task_type}/{openshiftai_inference_id}",
   input: InferencePutOpenshiftAiRequest,
 },
]
