/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferencePutAzureaistudioRequest } from './schemas/inference_put_azureaistudio.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutAzureaistudioApis: EsApiDefinition[] = [
 {
   name: "put-azureaistudio",
   namespace: "inference",
   description: "Create an Azure AI studio inference endpoint.",
   method: "PUT",
   path: "/_inference/{task_type}/{azureaistudio_inference_id}",
   input: InferencePutAzureaistudioRequest,
 },
]
