/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferenceEmbeddingRequest } from './schemas/inference_embedding.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferenceEmbeddingApis: EsApiDefinition[] = [
 {
   name: "embedding",
   namespace: "inference",
   description: "Perform dense embedding inference on the service.",
   method: "POST",
   path: "/_inference/embedding/{inference_id}",
   input: InferenceEmbeddingRequest,
 },
]
