/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferenceChatCompletionUnifiedRequest } from './schemas/inference_chat_completion_unified.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferenceChatCompletionUnifiedApis: EsApiDefinition[] = [
 {
   name: "chat-completion-unified",
   namespace: "inference",
   description: "Perform chat completion inference on the service.",
   method: "POST",
   path: "/_inference/chat_completion/{inference_id}/_stream",
   input: InferenceChatCompletionUnifiedRequest,
 },
]
