/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferencePutContextualaiRequest } from './schemas/inference_put_contextualai.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutContextualaiApis: EsApiDefinition[] = [
 {
   name: "put-contextualai",
   namespace: "inference",
   description: "Create an Contextual AI inference endpoint.",
   method: "PUT",
   path: "/_inference/{task_type}/{contextualai_inference_id}",
   input: InferencePutContextualaiRequest,
 },
]
