/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { InferenceGetRequest } from '@elastic/es-schemas/inference_get.js'
import type { EsApiDefinition } from '../types.ts'

export const inferenceGetApis: EsApiDefinition[] = [
 {
  name: "get",
  namespace: "inference",
  description: "Get an inference endpoint.",
  method: "GET",
  path: "/_inference/{task_type}/{inference_id}",
  input: InferenceGetRequest,
 },
]
