/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferencePutNvidiaRequest } from './schemas/inference_put_nvidia.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutNvidiaApis: EsApiDefinition[] = [
 {
   name: "put-nvidia",
   namespace: "inference",
   description: "Create an Nvidia inference endpoint.",
   method: "PUT",
   path: "/_inference/{task_type}/{nvidia_inference_id}",
   input: InferencePutNvidiaRequest,
 },
]
