/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferencePutOpenaiRequest } from './schemas/inference_put_openai.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutOpenaiApis: EsApiDefinition[] = [
 {
   name: "put-openai",
   namespace: "inference",
   description: "Create an OpenAI inference endpoint.",
   method: "PUT",
   path: "/_inference/{task_type}/{openai_inference_id}",
   input: InferencePutOpenaiRequest,
 },
]
