/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferenceInferenceRequest } from './schemas/inference_inference.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferenceInferenceApis: EsApiDefinition[] = [
 {
   name: "inference",
   namespace: "inference",
   description: "Perform inference on the service.",
   method: "POST",
   path: "/_inference/{task_type}/{inference_id}",
   input: InferenceInferenceRequest,
 },
]
