/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { InferenceDeleteRequest } from '@elastic/es-schemas/inference_delete.js'
import type { EsApiDefinition } from '../types.ts'

export const inferenceDeleteApis: EsApiDefinition[] = [
 {
  name: "delete",
  namespace: "inference",
  description: "Delete an inference endpoint.",
  method: "DELETE",
  path: "/_inference/{task_type}/{inference_id}",
  input: InferenceDeleteRequest,
 },
]
