/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferencePutAlibabacloudRequest } from './schemas/inference_put_alibabacloud.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutAlibabacloudApis: EsApiDefinition[] = [
 {
   name: "put-alibabacloud",
   namespace: "inference",
   description: "Create an AlibabaCloud AI Search inference endpoint.",
   method: "PUT",
   path: "/_inference/{task_type}/{alibabacloud_inference_id}",
   input: InferencePutAlibabacloudRequest,
 },
]
