/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { InferenceTextEmbeddingRequest } from '@elastic/es-schemas/inference_text_embedding.js'
import type { EsApiDefinition } from '../types.ts'

export const inferenceTextEmbeddingApis: EsApiDefinition[] = [
 {
  name: "text-embedding",
  namespace: "inference",
  description: "Perform text embedding inference on the service.",
  method: "POST",
  path: "/_inference/text_embedding/{inference_id}",
  input: InferenceTextEmbeddingRequest,
 },
]
