/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { InferencePutGoogleaistudioRequest } from '@elastic/es-schemas/inference_put_googleaistudio.js'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutGoogleaistudioApis: EsApiDefinition[] = [
 {
  name: "put-googleaistudio",
  namespace: "inference",
  description: "Create an Google AI Studio inference endpoint.",
  method: "PUT",
  path: "/_inference/{task_type}/{googleaistudio_inference_id}",
  input: InferencePutGoogleaistudioRequest,
 },
]
