/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferencePutDeepseekRequest } from './schemas/inference_put_deepseek.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutDeepseekApis: EsApiDefinition[] = [
 {
   name: "put-deepseek",
   namespace: "inference",
   description: "Create a DeepSeek inference endpoint.",
   method: "PUT",
   path: "/_inference/{task_type}/{deepseek_inference_id}",
   input: InferencePutDeepseekRequest,
 },
]
