/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferencePutVoyageaiRequest } from './schemas/inference_put_voyageai.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutVoyageaiApis: EsApiDefinition[] = [
 {
   name: "put-voyageai",
   namespace: "inference",
   description: "Create a VoyageAI inference endpoint.",
   method: "PUT",
   path: "/_inference/{task_type}/{voyageai_inference_id}",
   input: InferencePutVoyageaiRequest,
 },
]
