/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { InferencePutAzureopenaiRequest } from '@elastic/es-schemas/inference_put_azureopenai.js'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutAzureopenaiApis: EsApiDefinition[] = [
 {
  name: "put-azureopenai",
  namespace: "inference",
  description: "Create an Azure OpenAI inference endpoint.",
  method: "PUT",
  path: "/_inference/{task_type}/{azureopenai_inference_id}",
  input: InferencePutAzureopenaiRequest,
 },
]
