/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferenceTextEmbeddingRequest } from './schemas/inference_text_embedding.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferenceTextEmbeddingApis: EsApiDefinition[] = [
 {
   name: "text-embedding",
   namespace: "inference",
   description: "Perform text embedding inference on the service.",
   method: "POST",
   path: "/_inference/text_embedding/{inference_id}",
   input: InferenceTextEmbeddingRequest,
 },
]
