/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { InferencePutContextualaiRequest } from '@elastic/es-schemas/inference_put_contextualai.js'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutContextualaiApis: EsApiDefinition[] = [
 {
  name: "put-contextualai",
  namespace: "inference",
  description: "Create an Contextual AI inference endpoint.",
  method: "PUT",
  path: "/_inference/{task_type}/{contextualai_inference_id}",
  input: InferencePutContextualaiRequest,
 },
]
