/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferencePutElasticsearchRequest } from './schemas/inference_put_elasticsearch.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutElasticsearchApis: EsApiDefinition[] = [
 {
   name: "put-elasticsearch",
   namespace: "inference",
   description: "Create an Elasticsearch inference endpoint.",
   method: "PUT",
   path: "/_inference/{task_type}/{elasticsearch_inference_id}",
   input: InferencePutElasticsearchRequest,
 },
]
