/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferenceStreamCompletionRequest } from './schemas/inference_stream_completion.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferenceStreamCompletionApis: EsApiDefinition[] = [
 {
   name: "stream-completion",
   namespace: "inference",
   description: "Perform streaming completion inference on the service.",
   method: "POST",
   path: "/_inference/completion/{inference_id}/_stream",
   input: InferenceStreamCompletionRequest,
 },
]
