/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferencePutAmazonbedrockRequest } from './schemas/inference_put_amazonbedrock.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutAmazonbedrockApis: EsApiDefinition[] = [
 {
   name: "put-amazonbedrock",
   namespace: "inference",
   description: "Create an Amazon Bedrock inference endpoint.",
   method: "PUT",
   path: "/_inference/{task_type}/{amazonbedrock_inference_id}",
   input: InferencePutAmazonbedrockRequest,
 },
]
