/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferenceCompletionRequest } from './schemas/inference_completion.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferenceCompletionApis: EsApiDefinition[] = [
 {
   name: "completion",
   namespace: "inference",
   description: "Perform completion inference on the service.",
   method: "POST",
   path: "/_inference/completion/{inference_id}",
   input: InferenceCompletionRequest,
 },
]
