/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferenceUpdateRequest } from './schemas/inference_update.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferenceUpdateApis: EsApiDefinition[] = [
 {
   name: "update",
   namespace: "inference",
   description: "Update an inference endpoint.",
   method: "PUT",
   path: "/_inference/{task_type}/{inference_id}/_update",
   input: InferenceUpdateRequest,
 },
]
