/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { InferenceChatCompletionUnifiedRequest, InferenceCompletionRequest, InferenceDeleteRequest, InferenceEmbeddingRequest, InferenceGetRequest, InferenceInferenceRequest, InferencePutAi21Request, InferencePutAlibabacloudRequest, InferencePutAmazonbedrockRequest, InferencePutAmazonsagemakerRequest, InferencePutAnthropicRequest, InferencePutAzureaistudioRequest, InferencePutAzureopenaiRequest, InferencePutCohereRequest, InferencePutContextualaiRequest, InferencePutCustomRequest, InferencePutDeepseekRequest, InferencePutElasticsearchRequest, InferencePutElserRequest, InferencePutFireworksaiRequest, InferencePutGoogleaistudioRequest, InferencePutGooglevertexaiRequest, InferencePutGroqRequest, InferencePutHuggingFaceRequest, InferencePutJinaaiRequest, InferencePutLlamaRequest, InferencePutMistralRequest, InferencePutNvidiaRequest, InferencePutOpenaiRequest, InferencePutOpenshiftAiRequest, InferencePutRequest, InferencePutVoyageaiRequest, InferencePutWatsonxRequest, InferenceRerankRequest, InferenceSparseEmbeddingRequest, InferenceTextEmbeddingRequest } from '@elastic/es-schemas/inference.js'
import type { EsApiDefinition } from '../types.ts'

export const inferenceApis: EsApiDefinition[] = [
  {
    name: 'chat-completion-unified',
    namespace: 'inference',
    description: 'Perform chat completion inference on the service.',
    method: 'POST',
    path: '/_inference/chat_completion/{inference_id}/_stream',
    input: InferenceChatCompletionUnifiedRequest
  },
  {
    name: 'completion',
    namespace: 'inference',
    description: 'Perform completion inference on the service.',
    method: 'POST',
    path: '/_inference/completion/{inference_id}',
    input: InferenceCompletionRequest
  },
  {
    name: 'delete',
    namespace: 'inference',
    description: 'Delete an inference endpoint.',
    method: 'DELETE',
    path: '/_inference/{task_type}/{inference_id}',
    input: InferenceDeleteRequest
  },
  {
    name: 'embedding',
    namespace: 'inference',
    description: 'Perform dense embedding inference on the service.',
    method: 'POST',
    path: '/_inference/embedding/{inference_id}',
    input: InferenceEmbeddingRequest
  },
  {
    name: 'get',
    namespace: 'inference',
    description: 'Get an inference endpoint.',
    method: 'GET',
    path: '/_inference/{task_type}/{inference_id}',
    input: InferenceGetRequest
  },
  {
    name: 'inference',
    namespace: 'inference',
    description: 'Perform inference on the service.',
    method: 'POST',
    path: '/_inference/{task_type}/{inference_id}',
    input: InferenceInferenceRequest
  },
  {
    name: 'put',
    namespace: 'inference',
    description: 'Create an inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{inference_id}',
    input: InferencePutRequest
  },
  {
    name: 'put-ai21',
    namespace: 'inference',
    description: 'Create a AI21 inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{ai21_inference_id}',
    input: InferencePutAi21Request
  },
  {
    name: 'put-alibabacloud',
    namespace: 'inference',
    description: 'Create an AlibabaCloud AI Search inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{alibabacloud_inference_id}',
    input: InferencePutAlibabacloudRequest
  },
  {
    name: 'put-amazonbedrock',
    namespace: 'inference',
    description: 'Create an Amazon Bedrock inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{amazonbedrock_inference_id}',
    input: InferencePutAmazonbedrockRequest
  },
  {
    name: 'put-amazonsagemaker',
    namespace: 'inference',
    description: 'Create an Amazon SageMaker inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{amazonsagemaker_inference_id}',
    input: InferencePutAmazonsagemakerRequest
  },
  {
    name: 'put-anthropic',
    namespace: 'inference',
    description: 'Create an Anthropic inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{anthropic_inference_id}',
    input: InferencePutAnthropicRequest
  },
  {
    name: 'put-azureaistudio',
    namespace: 'inference',
    description: 'Create an Azure AI studio inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{azureaistudio_inference_id}',
    input: InferencePutAzureaistudioRequest
  },
  {
    name: 'put-azureopenai',
    namespace: 'inference',
    description: 'Create an Azure OpenAI inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{azureopenai_inference_id}',
    input: InferencePutAzureopenaiRequest
  },
  {
    name: 'put-cohere',
    namespace: 'inference',
    description: 'Create a Cohere inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{cohere_inference_id}',
    input: InferencePutCohereRequest
  },
  {
    name: 'put-contextualai',
    namespace: 'inference',
    description: 'Create an Contextual AI inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{contextualai_inference_id}',
    input: InferencePutContextualaiRequest
  },
  {
    name: 'put-custom',
    namespace: 'inference',
    description: 'Create a custom inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{custom_inference_id}',
    input: InferencePutCustomRequest
  },
  {
    name: 'put-deepseek',
    namespace: 'inference',
    description: 'Create a DeepSeek inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{deepseek_inference_id}',
    input: InferencePutDeepseekRequest
  },
  {
    name: 'put-elasticsearch',
    namespace: 'inference',
    description: 'Create an Elasticsearch inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{elasticsearch_inference_id}',
    input: InferencePutElasticsearchRequest
  },
  {
    name: 'put-elser',
    namespace: 'inference',
    description: 'Create an ELSER inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{elser_inference_id}',
    input: InferencePutElserRequest
  },
  {
    name: 'put-fireworksai',
    namespace: 'inference',
    description: 'Create a Fireworks AI inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{fireworksai_inference_id}',
    input: InferencePutFireworksaiRequest
  },
  {
    name: 'put-googleaistudio',
    namespace: 'inference',
    description: 'Create an Google AI Studio inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{googleaistudio_inference_id}',
    input: InferencePutGoogleaistudioRequest
  },
  {
    name: 'put-googlevertexai',
    namespace: 'inference',
    description: 'Create a Google Vertex AI inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{googlevertexai_inference_id}',
    input: InferencePutGooglevertexaiRequest
  },
  {
    name: 'put-groq',
    namespace: 'inference',
    description: 'Create a Groq inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{groq_inference_id}',
    input: InferencePutGroqRequest
  },
  {
    name: 'put-hugging-face',
    namespace: 'inference',
    description: 'Create a Hugging Face inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{huggingface_inference_id}',
    input: InferencePutHuggingFaceRequest
  },
  {
    name: 'put-jinaai',
    namespace: 'inference',
    description: 'Create an JinaAI inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{jinaai_inference_id}',
    input: InferencePutJinaaiRequest
  },
  {
    name: 'put-llama',
    namespace: 'inference',
    description: 'Create a Llama inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{llama_inference_id}',
    input: InferencePutLlamaRequest
  },
  {
    name: 'put-mistral',
    namespace: 'inference',
    description: 'Create a Mistral inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{mistral_inference_id}',
    input: InferencePutMistralRequest
  },
  {
    name: 'put-nvidia',
    namespace: 'inference',
    description: 'Create an Nvidia inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{nvidia_inference_id}',
    input: InferencePutNvidiaRequest
  },
  {
    name: 'put-openai',
    namespace: 'inference',
    description: 'Create an OpenAI inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{openai_inference_id}',
    input: InferencePutOpenaiRequest
  },
  {
    name: 'put-openshift-ai',
    namespace: 'inference',
    description: 'Create an OpenShift AI inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{openshiftai_inference_id}',
    input: InferencePutOpenshiftAiRequest
  },
  {
    name: 'put-voyageai',
    namespace: 'inference',
    description: 'Create a VoyageAI inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{voyageai_inference_id}',
    input: InferencePutVoyageaiRequest
  },
  {
    name: 'put-watsonx',
    namespace: 'inference',
    description: 'Create a Watsonx inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{watsonx_inference_id}',
    input: InferencePutWatsonxRequest
  },
  {
    name: 'rerank',
    namespace: 'inference',
    description: 'Perform reranking inference on the service.',
    method: 'POST',
    path: '/_inference/rerank/{inference_id}',
    input: InferenceRerankRequest
  },
  {
    name: 'sparse-embedding',
    namespace: 'inference',
    description: 'Perform sparse embedding inference on the service.',
    method: 'POST',
    path: '/_inference/sparse_embedding/{inference_id}',
    input: InferenceSparseEmbeddingRequest
  },
  {
    name: 'text-embedding',
    namespace: 'inference',
    description: 'Perform text embedding inference on the service.',
    method: 'POST',
    path: '/_inference/text_embedding/{inference_id}',
    input: InferenceTextEmbeddingRequest
  }
]
