/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferenceGetRequest } from './schemas/inference_get.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferenceGetApis: EsApiDefinition[] = [
 {
   name: "get",
   namespace: "inference",
   description: "Get an inference endpoint.",
   method: "GET",
   path: "/_inference/{task_type}/{inference_id}",
   input: InferenceGetRequest,
 },
]
