/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { InferenceChatCompletionUnifiedRequest } from '@elastic/es-schemas/inference_chat_completion_unified.js'
import type { EsApiDefinition } from '../types.ts'

export const inferenceChatCompletionUnifiedApis: EsApiDefinition[] = [
 {
  name: "chat-completion-unified",
  namespace: "inference",
  description: "Perform chat completion inference on the service.",
  method: "POST",
  path: "/_inference/chat_completion/{inference_id}/_stream",
  input: InferenceChatCompletionUnifiedRequest,
 },
]
