/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { InferenceCompletionRequest } from '@elastic/es-schemas/inference_completion.js'
import type { EsApiDefinition } from '../types.ts'

export const inferenceCompletionApis: EsApiDefinition[] = [
 {
  name: "completion",
  namespace: "inference",
  description: "Perform completion inference on the service.",
  method: "POST",
  path: "/_inference/completion/{inference_id}",
  input: InferenceCompletionRequest,
 },
]
