/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { InferenceEmbeddingRequest } from '@elastic/es-schemas/inference_embedding.js'
import type { EsApiDefinition } from '../types.ts'

export const inferenceEmbeddingApis: EsApiDefinition[] = [
 {
  name: "embedding",
  namespace: "inference",
  description: "Perform dense embedding inference on the service.",
  method: "POST",
  path: "/_inference/embedding/{inference_id}",
  input: InferenceEmbeddingRequest,
 },
]
