/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferencePutAmazonsagemakerRequest } from './schemas/inference_put_amazonsagemaker.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutAmazonsagemakerApis: EsApiDefinition[] = [
 {
   name: "put-amazonsagemaker",
   namespace: "inference",
   description: "Create an Amazon SageMaker inference endpoint.",
   method: "PUT",
   path: "/_inference/{task_type}/{amazonsagemaker_inference_id}",
   input: InferencePutAmazonsagemakerRequest,
 },
]
