/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferencePutFireworksaiRequest } from './schemas/inference_put_fireworksai.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutFireworksaiApis: EsApiDefinition[] = [
 {
   name: "put-fireworksai",
   namespace: "inference",
   description: "Create a Fireworks AI inference endpoint.",
   method: "PUT",
   path: "/_inference/{task_type}/{fireworksai_inference_id}",
   input: InferencePutFireworksaiRequest,
 },
]
