/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferencePutJinaaiRequest } from './schemas/inference_put_jinaai.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutJinaaiApis: EsApiDefinition[] = [
 {
   name: "put-jinaai",
   namespace: "inference",
   description: "Create an JinaAI inference endpoint.",
   method: "PUT",
   path: "/_inference/{task_type}/{jinaai_inference_id}",
   input: InferencePutJinaaiRequest,
 },
]
