/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferencePutCustomRequest } from './schemas/inference_put_custom.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutCustomApis: EsApiDefinition[] = [
 {
   name: "put-custom",
   namespace: "inference",
   description: "Create a custom inference endpoint.",
   method: "PUT",
   path: "/_inference/{task_type}/{custom_inference_id}",
   input: InferencePutCustomRequest,
 },
]
