/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferencePutMistralRequest } from './schemas/inference_put_mistral.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutMistralApis: EsApiDefinition[] = [
 {
   name: "put-mistral",
   namespace: "inference",
   description: "Create a Mistral inference endpoint.",
   method: "PUT",
   path: "/_inference/{task_type}/{mistral_inference_id}",
   input: InferencePutMistralRequest,
 },
]
