/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferencePutLlamaRequest } from './schemas/inference_put_llama.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutLlamaApis: EsApiDefinition[] = [
 {
   name: "put-llama",
   namespace: "inference",
   description: "Create a Llama inference endpoint.",
   method: "PUT",
   path: "/_inference/{task_type}/{llama_inference_id}",
   input: InferencePutLlamaRequest,
 },
]
