/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferencePutGooglevertexaiRequest } from './schemas/inference_put_googlevertexai.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutGooglevertexaiApis: EsApiDefinition[] = [
 {
   name: "put-googlevertexai",
   namespace: "inference",
   description: "Create a Google Vertex AI inference endpoint.",
   method: "PUT",
   path: "/_inference/{task_type}/{googlevertexai_inference_id}",
   input: InferencePutGooglevertexaiRequest,
 },
]
