/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferencePutElserRequest } from './schemas/inference_put_elser.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutElserApis: EsApiDefinition[] = [
 {
   name: "put-elser",
   namespace: "inference",
   description: "Create an ELSER inference endpoint.",
   method: "PUT",
   path: "/_inference/{task_type}/{elser_inference_id}",
   input: InferencePutElserRequest,
 },
]
