/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferencePutGroqRequest } from './schemas/inference_put_groq.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutGroqApis: EsApiDefinition[] = [
 {
   name: "put-groq",
   namespace: "inference",
   description: "Create a Groq inference endpoint.",
   method: "PUT",
   path: "/_inference/{task_type}/{groq_inference_id}",
   input: InferencePutGroqRequest,
 },
]
