/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferencePutCohereRequest } from './schemas/inference_put_cohere.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutCohereApis: EsApiDefinition[] = [
 {
   name: "put-cohere",
   namespace: "inference",
   description: "Create a Cohere inference endpoint.",
   method: "PUT",
   path: "/_inference/{task_type}/{cohere_inference_id}",
   input: InferencePutCohereRequest,
 },
]
