/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferencePutGoogleaistudioRequest } from './schemas/inference_put_googleaistudio.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutGoogleaistudioApis: EsApiDefinition[] = [
 {
   name: "put-googleaistudio",
   namespace: "inference",
   description: "Create an Google AI Studio inference endpoint.",
   method: "PUT",
   path: "/_inference/{task_type}/{googleaistudio_inference_id}",
   input: InferencePutGoogleaistudioRequest,
 },
]
