/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferencePutHuggingFaceRequest } from './schemas/inference_put_hugging_face.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutHuggingFaceApis: EsApiDefinition[] = [
 {
   name: "put-hugging-face",
   namespace: "inference",
   description: "Create a Hugging Face inference endpoint.",
   method: "PUT",
   path: "/_inference/{task_type}/{huggingface_inference_id}",
   input: InferencePutHuggingFaceRequest,
 },
]
