/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { InferencePutVoyageaiRequest } from '@elastic/es-schemas/inference_put_voyageai.js'
import type { EsApiDefinition } from '../types.ts'

export const inferencePutVoyageaiApis: EsApiDefinition[] = [
 {
  name: "put-voyageai",
  namespace: "inference",
  description: "Create a VoyageAI inference endpoint.",
  method: "PUT",
  path: "/_inference/{task_type}/{voyageai_inference_id}",
  input: InferencePutVoyageaiRequest,
 },
]
