/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { InferenceDeleteRequest } from './schemas/inference_delete.ts'
import type { EsApiDefinition } from '../types.ts'

export const inferenceDeleteApis: EsApiDefinition[] = [
 {
   name: "delete",
   namespace: "inference",
   description: "Delete an inference endpoint.",
   method: "DELETE",
   path: "/_inference/{task_type}/{inference_id}",
   input: InferenceDeleteRequest,
 },
]
