/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { InfoRequest } from '@elastic/es-schemas/info.js'
import type { EsApiDefinition } from '../types.ts'

export const infoApis: EsApiDefinition[] = [
 {
  name: "info",
  description: "Get cluster info.",
  method: "GET",
  path: "/",
  input: InfoRequest,
 },
]
