/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IngestDeleteIpLocationDatabaseRequest } from '@elastic/es-schemas/ingest_delete_ip_location_database.js'
import type { EsApiDefinition } from '../types.ts'

export const ingestDeleteIpLocationDatabaseApis: EsApiDefinition[] = [
 {
  name: "delete-ip-location-database",
  namespace: "ingest",
  description: "Delete IP geolocation database configurations.",
  method: "DELETE",
  path: "/_ingest/ip_location/database/{id}",
  input: IngestDeleteIpLocationDatabaseRequest,
 },
]
