/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IngestSimulateRequest } from './schemas/ingest_simulate.ts'
import type { EsApiDefinition } from '../types.ts'

export const ingestSimulateApis: EsApiDefinition[] = [
 {
   name: "simulate",
   namespace: "ingest",
   description: "Simulate a pipeline.",
   method: "GET",
   path: "/_ingest/pipeline/{id}/_simulate",
   input: IngestSimulateRequest,
 },
]
