/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IngestProcessorGrokRequest } from './schemas/ingest_processor_grok.ts'
import type { EsApiDefinition } from '../types.ts'

export const ingestProcessorGrokApis: EsApiDefinition[] = [
 {
   name: "processor-grok",
   namespace: "ingest",
   description: "Run a grok processor.",
   method: "GET",
   path: "/_ingest/processor/grok",
   input: IngestProcessorGrokRequest,
 },
]
