/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IngestProcessorGrokRequest } from '@elastic/es-schemas/ingest_processor_grok.js'
import type { EsApiDefinition } from '../types.ts'

export const ingestProcessorGrokApis: EsApiDefinition[] = [
 {
  name: "processor-grok",
  namespace: "ingest",
  description: "Run a grok processor.",
  method: "GET",
  path: "/_ingest/processor/grok",
  input: IngestProcessorGrokRequest,
 },
]
