/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IngestDeletePipelineRequest } from './schemas/ingest_delete_pipeline.ts'
import type { EsApiDefinition } from '../types.ts'

export const ingestDeletePipelineApis: EsApiDefinition[] = [
 {
   name: "delete-pipeline",
   namespace: "ingest",
   description: "Delete pipelines.",
   method: "DELETE",
   path: "/_ingest/pipeline/{id}",
   input: IngestDeletePipelineRequest,
 },
]
