/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IngestPutIpLocationDatabaseRequest } from '@elastic/es-schemas/ingest_put_ip_location_database.js'
import type { EsApiDefinition } from '../types.ts'

export const ingestPutIpLocationDatabaseApis: EsApiDefinition[] = [
 {
  name: "put-ip-location-database",
  namespace: "ingest",
  description: "Create or update an IP geolocation database configuration.",
  method: "PUT",
  path: "/_ingest/ip_location/database/{id}",
  input: IngestPutIpLocationDatabaseRequest,
 },
]
