/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IngestGeoIpStatsRequest } from '@elastic/es-schemas/ingest_geo_ip_stats.js'
import type { EsApiDefinition } from '../types.ts'

export const ingestGeoIpStatsApis: EsApiDefinition[] = [
 {
  name: "geo-ip-stats",
  namespace: "ingest",
  description: "Get GeoIP statistics.",
  method: "GET",
  path: "/_ingest/geoip/stats",
  input: IngestGeoIpStatsRequest,
 },
]
