/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IngestPutPipelineRequest } from '@elastic/es-schemas/ingest_put_pipeline.js'
import type { EsApiDefinition } from '../types.ts'

export const ingestPutPipelineApis: EsApiDefinition[] = [
 {
  name: "put-pipeline",
  namespace: "ingest",
  description: "Create or update a pipeline.",
  method: "PUT",
  path: "/_ingest/pipeline/{id}",
  input: IngestPutPipelineRequest,
 },
]
