/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IngestGetPipelineRequest } from '@elastic/es-schemas/ingest_get_pipeline.js'
import type { EsApiDefinition } from '../types.ts'

export const ingestGetPipelineApis: EsApiDefinition[] = [
 {
  name: "get-pipeline",
  namespace: "ingest",
  description: "Get pipelines.",
  method: "GET",
  path: "/_ingest/pipeline/{id}",
  input: IngestGetPipelineRequest,
 },
]
