/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { IngestDeletePipelineRequest, IngestGetPipelineRequest, IngestProcessorGrokRequest, IngestPutPipelineRequest, IngestSimulateRequest } from '@elastic/es-schemas/ingest.js'
import type { EsApiDefinition } from '../types.ts'

export const ingestApis: EsApiDefinition[] = [
 {
  name: "delete-pipeline",
  namespace: "ingest",
  description: "Delete pipelines.",
  method: "DELETE",
  path: "/_ingest/pipeline/{id}",
  input: IngestDeletePipelineRequest,
 },
 {
  name: "get-pipeline",
  namespace: "ingest",
  description: "Get pipelines.",
  method: "GET",
  path: "/_ingest/pipeline/{id}",
  input: IngestGetPipelineRequest,
 },
 {
  name: "processor-grok",
  namespace: "ingest",
  description: "Run a grok processor.",
  method: "GET",
  path: "/_ingest/processor/grok",
  input: IngestProcessorGrokRequest,
 },
 {
  name: "put-pipeline",
  namespace: "ingest",
  description: "Create or update a pipeline.",
  method: "PUT",
  path: "/_ingest/pipeline/{id}",
  input: IngestPutPipelineRequest,
 },
 {
  name: "simulate",
  namespace: "ingest",
  description: "Simulate a pipeline.",
  method: "GET",
  path: "/_ingest/pipeline/{id}/_simulate",
  input: IngestSimulateRequest,
 },
]
