/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { IngestGetPipelineRequest } from './schemas/ingest_get_pipeline.ts'
import type { EsApiDefinition } from '../types.ts'

export const ingestGetPipelineApis: EsApiDefinition[] = [
 {
   name: "get-pipeline",
   namespace: "ingest",
   description: "Get pipelines.",
   method: "GET",
   path: "/_ingest/pipeline/{id}",
   input: IngestGetPipelineRequest,
 },
]
