/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { LicenseGetBasicStatusRequest } from '@elastic/es-schemas/license_get_basic_status.js'
import type { EsApiDefinition } from '../types.ts'

export const licenseGetBasicStatusApis: EsApiDefinition[] = [
 {
  name: "get-basic-status",
  namespace: "license",
  description: "Get the basic license status.",
  method: "GET",
  path: "/_license/basic_status",
  input: LicenseGetBasicStatusRequest,
 },
]
