/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { LicenseGetRequest } from './schemas/license.ts'
import type { EsApiDefinition } from '../types.ts'

export const licenseApis: EsApiDefinition[] = [
  {
    name: 'get',
    namespace: 'license',
    description: 'Get license information.',
    method: 'GET',
    path: '/_license',
    input: LicenseGetRequest
  }
]
