/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { LicensePostRequest } from '@elastic/es-schemas/license_post.js'
import type { EsApiDefinition } from '../types.ts'

export const licensePostApis: EsApiDefinition[] = [
 {
  name: "post",
  namespace: "license",
  description: "Update the license.",
  method: "PUT",
  path: "/_license",
  input: LicensePostRequest,
 },
]
