/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { LogstashGetPipelineRequest } from './schemas/logstash_get_pipeline.ts'
import type { EsApiDefinition } from '../types.ts'

export const logstashGetPipelineApis: EsApiDefinition[] = [
 {
   name: "get-pipeline",
   namespace: "logstash",
   description: "Get Logstash pipelines.",
   method: "GET",
   path: "/_logstash/pipeline/{id}",
   input: LogstashGetPipelineRequest,
 },
]
