/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { LogstashGetPipelineRequest } from '@elastic/es-schemas/logstash_get_pipeline.js'
import type { EsApiDefinition } from '../types.ts'

export const logstashGetPipelineApis: EsApiDefinition[] = [
 {
  name: "get-pipeline",
  namespace: "logstash",
  description: "Get Logstash pipelines.",
  method: "GET",
  path: "/_logstash/pipeline/{id}",
  input: LogstashGetPipelineRequest,
 },
]
