/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { LogstashDeletePipelineRequest } from './schemas/logstash_delete_pipeline.ts'
import type { EsApiDefinition } from '../types.ts'

export const logstashDeletePipelineApis: EsApiDefinition[] = [
 {
   name: "delete-pipeline",
   namespace: "logstash",
   description: "Delete a Logstash pipeline.",
   method: "DELETE",
   path: "/_logstash/pipeline/{id}",
   input: LogstashDeletePipelineRequest,
 },
]
