/**
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { LogstashDeletePipelineRequest, LogstashGetPipelineRequest, LogstashPutPipelineRequest } from './schemas/logstash.ts'
import type { EsApiDefinition } from '../types.ts'

export const logstashApis: EsApiDefinition[] = [
  {
    name: 'delete-pipeline',
    namespace: 'logstash',
    description: 'Delete a Logstash pipeline.',
    method: 'DELETE',
    path: '/_logstash/pipeline/{id}',
    input: LogstashDeletePipelineRequest
  },
  {
    name: 'get-pipeline',
    namespace: 'logstash',
    description: 'Get Logstash pipelines.',
    method: 'GET',
    path: '/_logstash/pipeline/{id}',
    input: LogstashGetPipelineRequest
  },
  {
    name: 'put-pipeline',
    namespace: 'logstash',
    description: 'Create or update a Logstash pipeline.',
    method: 'PUT',
    path: '/_logstash/pipeline/{id}',
    input: LogstashPutPipelineRequest
  }
]
