/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { LogstashDeletePipelineRequest } from '@elastic/es-schemas/logstash_delete_pipeline.js'
import type { EsApiDefinition } from '../types.ts'

export const logstashDeletePipelineApis: EsApiDefinition[] = [
 {
  name: "delete-pipeline",
  namespace: "logstash",
  description: "Delete a Logstash pipeline.",
  method: "DELETE",
  path: "/_logstash/pipeline/{id}",
  input: LogstashDeletePipelineRequest,
 },
]
