/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { MigrationPostFeatureUpgradeRequest } from '@elastic/es-schemas/migration_post_feature_upgrade.js'
import type { EsApiDefinition } from '../types.ts'

export const migrationPostFeatureUpgradeApis: EsApiDefinition[] = [
 {
  name: "post-feature-upgrade",
  namespace: "migration",
  description: "Start the feature migration.",
  method: "POST",
  path: "/_migration/system_features",
  input: MigrationPostFeatureUpgradeRequest,
 },
]
