/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlCloseJobRequest } from './schemas/ml_close_job.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlCloseJobApis: EsApiDefinition[] = [
 {
   name: "close-job",
   namespace: "ml",
   description: "Close anomaly detection jobs.",
   method: "POST",
   path: "/_ml/anomaly_detectors/{job_id}/_close",
   input: MlCloseJobRequest,
 },
]
