/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { MlDeleteModelSnapshotRequest } from '@elastic/es-schemas/ml_delete_model_snapshot.js'
import type { EsApiDefinition } from '../types.ts'

export const mlDeleteModelSnapshotApis: EsApiDefinition[] = [
 {
  name: "delete-model-snapshot",
  namespace: "ml",
  description: "Delete a model snapshot.",
  method: "DELETE",
  path: "/_ml/anomaly_detectors/{job_id}/model_snapshots/{snapshot_id}",
  input: MlDeleteModelSnapshotRequest,
 },
]
