/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlDeleteDatafeedRequest } from './schemas/ml_delete_datafeed.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlDeleteDatafeedApis: EsApiDefinition[] = [
 {
   name: "delete-datafeed",
   namespace: "ml",
   description: "Delete a datafeed.",
   method: "DELETE",
   path: "/_ml/datafeeds/{datafeed_id}",
   input: MlDeleteDatafeedRequest,
 },
]
