/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlDeleteJobRequest } from './schemas/ml_delete_job.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlDeleteJobApis: EsApiDefinition[] = [
 {
   name: "delete-job",
   namespace: "ml",
   description: "Delete an anomaly detection job.",
   method: "DELETE",
   path: "/_ml/anomaly_detectors/{job_id}",
   input: MlDeleteJobRequest,
 },
]
