/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { MlDeleteCalendarRequest } from '@elastic/es-schemas/ml_delete_calendar.js'
import type { EsApiDefinition } from '../types.ts'

export const mlDeleteCalendarApis: EsApiDefinition[] = [
 {
  name: "delete-calendar",
  namespace: "ml",
  description: "Delete a calendar.",
  method: "DELETE",
  path: "/_ml/calendars/{calendar_id}",
  input: MlDeleteCalendarRequest,
 },
]
