/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlDeleteTrainedModelRequest } from './schemas/ml_delete_trained_model.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlDeleteTrainedModelApis: EsApiDefinition[] = [
 {
   name: "delete-trained-model",
   namespace: "ml",
   description: "Delete an unreferenced trained model.",
   method: "DELETE",
   path: "/_ml/trained_models/{model_id}",
   input: MlDeleteTrainedModelRequest,
 },
]
