/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlDeleteCalendarRequest } from './schemas/ml_delete_calendar.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlDeleteCalendarApis: EsApiDefinition[] = [
 {
   name: "delete-calendar",
   namespace: "ml",
   description: "Delete a calendar.",
   method: "DELETE",
   path: "/_ml/calendars/{calendar_id}",
   input: MlDeleteCalendarRequest,
 },
]
