/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlDeleteDataFrameAnalyticsRequest } from './schemas/ml_delete_data_frame_analytics.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlDeleteDataFrameAnalyticsApis: EsApiDefinition[] = [
 {
   name: "delete-data-frame-analytics",
   namespace: "ml",
   description: "Delete a data frame analytics job.",
   method: "DELETE",
   path: "/_ml/data_frame/analytics/{id}",
   input: MlDeleteDataFrameAnalyticsRequest,
 },
]
