/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlDeleteCalendarEventRequest } from './schemas/ml_delete_calendar_event.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlDeleteCalendarEventApis: EsApiDefinition[] = [
 {
   name: "delete-calendar-event",
   namespace: "ml",
   description: "Delete events from a calendar.",
   method: "DELETE",
   path: "/_ml/calendars/{calendar_id}/events/{event_id}",
   input: MlDeleteCalendarEventRequest,
 },
]
