/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlDeleteCalendarJobRequest } from './schemas/ml_delete_calendar_job.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlDeleteCalendarJobApis: EsApiDefinition[] = [
 {
   name: "delete-calendar-job",
   namespace: "ml",
   description: "Delete anomaly jobs from a calendar.",
   method: "DELETE",
   path: "/_ml/calendars/{calendar_id}/jobs/{job_id}",
   input: MlDeleteCalendarJobRequest,
 },
]
