/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlDeleteTrainedModelAliasRequest } from './schemas/ml_delete_trained_model_alias.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlDeleteTrainedModelAliasApis: EsApiDefinition[] = [
 {
   name: "delete-trained-model-alias",
   namespace: "ml",
   description: "Delete a trained model alias.",
   method: "DELETE",
   path: "/_ml/trained_models/{model_id}/model_aliases/{model_alias}",
   input: MlDeleteTrainedModelAliasRequest,
 },
]
