/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { MlDeleteDataFrameAnalyticsRequest } from '@elastic/es-schemas/ml_delete_data_frame_analytics.js'
import type { EsApiDefinition } from '../types.ts'

export const mlDeleteDataFrameAnalyticsApis: EsApiDefinition[] = [
 {
  name: "delete-data-frame-analytics",
  namespace: "ml",
  description: "Delete a data frame analytics job.",
  method: "DELETE",
  path: "/_ml/data_frame/analytics/{id}",
  input: MlDeleteDataFrameAnalyticsRequest,
 },
]
