/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlEvaluateDataFrameRequest } from './schemas/ml_evaluate_data_frame.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlEvaluateDataFrameApis: EsApiDefinition[] = [
 {
   name: "evaluate-data-frame",
   namespace: "ml",
   description: "Evaluate data frame analytics.",
   method: "POST",
   path: "/_ml/data_frame/_evaluate",
   input: MlEvaluateDataFrameRequest,
 },
]
