/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlEstimateModelMemoryRequest } from './schemas/ml_estimate_model_memory.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlEstimateModelMemoryApis: EsApiDefinition[] = [
 {
   name: "estimate-model-memory",
   namespace: "ml",
   description: "Estimate job model memory usage.",
   method: "POST",
   path: "/_ml/anomaly_detectors/_estimate_model_memory",
   input: MlEstimateModelMemoryRequest,
 },
]
