/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { MlEstimateModelMemoryRequest } from '@elastic/es-schemas/ml_estimate_model_memory.js'
import type { EsApiDefinition } from '../types.ts'

export const mlEstimateModelMemoryApis: EsApiDefinition[] = [
 {
  name: "estimate-model-memory",
  namespace: "ml",
  description: "Estimate job model memory usage.",
  method: "POST",
  path: "/_ml/anomaly_detectors/_estimate_model_memory",
  input: MlEstimateModelMemoryRequest,
 },
]
