/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { MlExplainDataFrameAnalyticsRequest } from '@elastic/es-schemas/ml_explain_data_frame_analytics.js'
import type { EsApiDefinition } from '../types.ts'

export const mlExplainDataFrameAnalyticsApis: EsApiDefinition[] = [
 {
  name: "explain-data-frame-analytics",
  namespace: "ml",
  description: "Explain data frame analytics config.",
  method: "GET",
  path: "/_ml/data_frame/analytics/{id}/_explain",
  input: MlExplainDataFrameAnalyticsRequest,
 },
]
