/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlGetDataFrameAnalyticsRequest } from './schemas/ml_get_data_frame_analytics.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlGetDataFrameAnalyticsApis: EsApiDefinition[] = [
 {
   name: "get-data-frame-analytics",
   namespace: "ml",
   description: "Get data frame analytics job configuration info.",
   method: "GET",
   path: "/_ml/data_frame/analytics/{id}",
   input: MlGetDataFrameAnalyticsRequest,
 },
]
