/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { MlGetInfluencersRequest } from '@elastic/es-schemas/ml_get_influencers.js'
import type { EsApiDefinition } from '../types.ts'

export const mlGetInfluencersApis: EsApiDefinition[] = [
 {
  name: "get-influencers",
  namespace: "ml",
  description: "Get anomaly detection job results for influencers.",
  method: "GET",
  path: "/_ml/anomaly_detectors/{job_id}/results/influencers",
  input: MlGetInfluencersRequest,
 },
]
