/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlGetFiltersRequest } from './schemas/ml_get_filters.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlGetFiltersApis: EsApiDefinition[] = [
 {
   name: "get-filters",
   namespace: "ml",
   description: "Get filters.",
   method: "GET",
   path: "/_ml/filters/{filter_id}",
   input: MlGetFiltersRequest,
 },
]
