/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlGetTrainedModelsStatsRequest } from './schemas/ml_get_trained_models_stats.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlGetTrainedModelsStatsApis: EsApiDefinition[] = [
 {
   name: "get-trained-models-stats",
   namespace: "ml",
   description: "Get trained models usage info.",
   method: "GET",
   path: "/_ml/trained_models/{model_id}/_stats",
   input: MlGetTrainedModelsStatsRequest,
 },
]
