/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlGetCalendarsRequest } from './schemas/ml_get_calendars.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlGetCalendarsApis: EsApiDefinition[] = [
 {
   name: "get-calendars",
   namespace: "ml",
   description: "Get calendar configuration info.",
   method: "GET",
   path: "/_ml/calendars/{calendar_id}",
   input: MlGetCalendarsRequest,
 },
]
