/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlGetDatafeedsRequest } from './schemas/ml_get_datafeeds.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlGetDatafeedsApis: EsApiDefinition[] = [
 {
   name: "get-datafeeds",
   namespace: "ml",
   description: "Get datafeeds configuration info.",
   method: "GET",
   path: "/_ml/datafeeds/{datafeed_id}",
   input: MlGetDatafeedsRequest,
 },
]
