/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlGetTrainedModelsRequest } from './schemas/ml_get_trained_models.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlGetTrainedModelsApis: EsApiDefinition[] = [
 {
   name: "get-trained-models",
   namespace: "ml",
   description: "Get trained model configuration info.",
   method: "GET",
   path: "/_ml/trained_models/{model_id}",
   input: MlGetTrainedModelsRequest,
 },
]
