/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { MlGetMemoryStatsRequest } from '@elastic/es-schemas/ml_get_memory_stats.js'
import type { EsApiDefinition } from '../types.ts'

export const mlGetMemoryStatsApis: EsApiDefinition[] = [
 {
  name: "get-memory-stats",
  namespace: "ml",
  description: "Get machine learning memory usage info.",
  method: "GET",
  path: "/_ml/memory/{node_id}/_stats",
  input: MlGetMemoryStatsRequest,
 },
]
