/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlGetCalendarEventsRequest } from './schemas/ml_get_calendar_events.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlGetCalendarEventsApis: EsApiDefinition[] = [
 {
   name: "get-calendar-events",
   namespace: "ml",
   description: "Get info about events in calendars.",
   method: "GET",
   path: "/_ml/calendars/{calendar_id}/events",
   input: MlGetCalendarEventsRequest,
 },
]
