/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlGetOverallBucketsRequest } from './schemas/ml_get_overall_buckets.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlGetOverallBucketsApis: EsApiDefinition[] = [
 {
   name: "get-overall-buckets",
   namespace: "ml",
   description: "Get overall bucket results.",
   method: "GET",
   path: "/_ml/anomaly_detectors/{job_id}/results/overall_buckets",
   input: MlGetOverallBucketsRequest,
 },
]
