/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { MlGetCalendarsRequest } from '@elastic/es-schemas/ml_get_calendars.js'
import type { EsApiDefinition } from '../types.ts'

export const mlGetCalendarsApis: EsApiDefinition[] = [
 {
  name: "get-calendars",
  namespace: "ml",
  description: "Get calendar configuration info.",
  method: "GET",
  path: "/_ml/calendars/{calendar_id}",
  input: MlGetCalendarsRequest,
 },
]
