/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { MlGetDataFrameAnalyticsStatsRequest } from '@elastic/es-schemas/ml_get_data_frame_analytics_stats.js'
import type { EsApiDefinition } from '../types.ts'

export const mlGetDataFrameAnalyticsStatsApis: EsApiDefinition[] = [
 {
  name: "get-data-frame-analytics-stats",
  namespace: "ml",
  description: "Get data frame analytics job stats.",
  method: "GET",
  path: "/_ml/data_frame/analytics/{id}/_stats",
  input: MlGetDataFrameAnalyticsStatsRequest,
 },
]
