/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlGetDatafeedStatsRequest } from './schemas/ml_get_datafeed_stats.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlGetDatafeedStatsApis: EsApiDefinition[] = [
 {
   name: "get-datafeed-stats",
   namespace: "ml",
   description: "Get datafeed stats.",
   method: "GET",
   path: "/_ml/datafeeds/{datafeed_id}/_stats",
   input: MlGetDatafeedStatsRequest,
 },
]
