/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlGetJobStatsRequest } from './schemas/ml_get_job_stats.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlGetJobStatsApis: EsApiDefinition[] = [
 {
   name: "get-job-stats",
   namespace: "ml",
   description: "Get anomaly detection job stats.",
   method: "GET",
   path: "/_ml/anomaly_detectors/{job_id}/_stats",
   input: MlGetJobStatsRequest,
 },
]
