/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlInferTrainedModelRequest } from './schemas/ml_infer_trained_model.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlInferTrainedModelApis: EsApiDefinition[] = [
 {
   name: "infer-trained-model",
   namespace: "ml",
   description: "Evaluate a trained model.",
   method: "POST",
   path: "/_ml/trained_models/{model_id}/_infer",
   input: MlInferTrainedModelRequest,
 },
]
