/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { MlOpenJobRequest } from '@elastic/es-schemas/ml_open_job.js'
import type { EsApiDefinition } from '../types.ts'

export const mlOpenJobApis: EsApiDefinition[] = [
 {
  name: "open-job",
  namespace: "ml",
  description: "Open anomaly detection jobs.",
  method: "POST",
  path: "/_ml/anomaly_detectors/{job_id}/_open",
  input: MlOpenJobRequest,
 },
]
