/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlPutCalendarJobRequest } from './schemas/ml_put_calendar_job.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlPutCalendarJobApis: EsApiDefinition[] = [
 {
   name: "put-calendar-job",
   namespace: "ml",
   description: "Add anomaly detection job to calendar.",
   method: "PUT",
   path: "/_ml/calendars/{calendar_id}/jobs/{job_id}",
   input: MlPutCalendarJobRequest,
 },
]
