/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlPutFilterRequest } from './schemas/ml_put_filter.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlPutFilterApis: EsApiDefinition[] = [
 {
   name: "put-filter",
   namespace: "ml",
   description: "Create a filter.",
   method: "PUT",
   path: "/_ml/filters/{filter_id}",
   input: MlPutFilterRequest,
 },
]
