/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { MlPostCalendarEventsRequest } from '@elastic/es-schemas/ml_post_calendar_events.js'
import type { EsApiDefinition } from '../types.ts'

export const mlPostCalendarEventsApis: EsApiDefinition[] = [
 {
  name: "post-calendar-events",
  namespace: "ml",
  description: "Add scheduled events to the calendar.",
  method: "POST",
  path: "/_ml/calendars/{calendar_id}/events",
  input: MlPostCalendarEventsRequest,
 },
]
