/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlPutJobRequest } from './schemas/ml_put_job.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlPutJobApis: EsApiDefinition[] = [
 {
   name: "put-job",
   namespace: "ml",
   description: "Create an anomaly detection job.",
   method: "PUT",
   path: "/_ml/anomaly_detectors/{job_id}",
   input: MlPutJobRequest,
 },
]
