/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { MlPutTrainedModelVocabularyRequest } from '@elastic/es-schemas/ml_put_trained_model_vocabulary.js'
import type { EsApiDefinition } from '../types.ts'

export const mlPutTrainedModelVocabularyApis: EsApiDefinition[] = [
 {
  name: "put-trained-model-vocabulary",
  namespace: "ml",
  description: "Create a trained model vocabulary.",
  method: "PUT",
  path: "/_ml/trained_models/{model_id}/vocabulary",
  input: MlPutTrainedModelVocabularyRequest,
 },
]
