/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlPutCalendarRequest } from './schemas/ml_put_calendar.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlPutCalendarApis: EsApiDefinition[] = [
 {
   name: "put-calendar",
   namespace: "ml",
   description: "Create a calendar.",
   method: "PUT",
   path: "/_ml/calendars/{calendar_id}",
   input: MlPutCalendarRequest,
 },
]
