/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlPutTrainedModelAliasRequest } from './schemas/ml_put_trained_model_alias.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlPutTrainedModelAliasApis: EsApiDefinition[] = [
 {
   name: "put-trained-model-alias",
   namespace: "ml",
   description: "Create or update a trained model alias.",
   method: "PUT",
   path: "/_ml/trained_models/{model_id}/model_aliases/{model_alias}",
   input: MlPutTrainedModelAliasRequest,
 },
]
