/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlPreviewDataFrameAnalyticsRequest } from './schemas/ml_preview_data_frame_analytics.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlPreviewDataFrameAnalyticsApis: EsApiDefinition[] = [
 {
   name: "preview-data-frame-analytics",
   namespace: "ml",
   description: "Preview features used by data frame analytics.",
   method: "GET",
   path: "/_ml/data_frame/analytics/{id}/_preview",
   input: MlPreviewDataFrameAnalyticsRequest,
 },
]
