/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { MlPutFilterRequest } from '@elastic/es-schemas/ml_put_filter.js'
import type { EsApiDefinition } from '../types.ts'

export const mlPutFilterApis: EsApiDefinition[] = [
 {
  name: "put-filter",
  namespace: "ml",
  description: "Create a filter.",
  method: "PUT",
  path: "/_ml/filters/{filter_id}",
  input: MlPutFilterRequest,
 },
]
