/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlPutTrainedModelRequest } from './schemas/ml_put_trained_model.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlPutTrainedModelApis: EsApiDefinition[] = [
 {
   name: "put-trained-model",
   namespace: "ml",
   description: "Create a trained model.",
   method: "PUT",
   path: "/_ml/trained_models/{model_id}",
   input: MlPutTrainedModelRequest,
 },
]
