/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { MlPutDatafeedRequest } from '@elastic/es-schemas/ml_put_datafeed.js'
import type { EsApiDefinition } from '../types.ts'

export const mlPutDatafeedApis: EsApiDefinition[] = [
 {
  name: "put-datafeed",
  namespace: "ml",
  description: "Create a datafeed.",
  method: "PUT",
  path: "/_ml/datafeeds/{datafeed_id}",
  input: MlPutDatafeedRequest,
 },
]
