/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { z } from 'zod'
import { MlPostDataRequest } from '@elastic/es-schemas/ml_post_data.js'
import type { EsApiDefinition } from '../types.ts'

const MlPostDataRequestPassthrough = MlPostDataRequest.extend({
  data: z.array(z.any()).optional().meta({ found_in: 'body' })
})

export const mlPostDataApis: EsApiDefinition[] = [
 {
  name: "post-data",
  namespace: "ml",
  description: "Send data to an anomaly detection job for analysis.",
  method: "POST",
  path: "/_ml/anomaly_detectors/{job_id}/_data",
  input: MlPostDataRequestPassthrough,
  bodyFormat: 'ndjson',
 },
]
