/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlPostCalendarEventsRequest } from './schemas/ml_post_calendar_events.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlPostCalendarEventsApis: EsApiDefinition[] = [
 {
   name: "post-calendar-events",
   namespace: "ml",
   description: "Add scheduled events to the calendar.",
   method: "POST",
   path: "/_ml/calendars/{calendar_id}/events",
   input: MlPostCalendarEventsRequest,
 },
]
