/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlPutTrainedModelDefinitionPartRequest } from './schemas/ml_put_trained_model_definition_part.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlPutTrainedModelDefinitionPartApis: EsApiDefinition[] = [
 {
   name: "put-trained-model-definition-part",
   namespace: "ml",
   description: "Create part of a trained model definition.",
   method: "PUT",
   path: "/_ml/trained_models/{model_id}/definition/{part}",
   input: MlPutTrainedModelDefinitionPartRequest,
 },
]
