/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlPutDatafeedRequest } from './schemas/ml_put_datafeed.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlPutDatafeedApis: EsApiDefinition[] = [
 {
   name: "put-datafeed",
   namespace: "ml",
   description: "Create a datafeed.",
   method: "PUT",
   path: "/_ml/datafeeds/{datafeed_id}",
   input: MlPutDatafeedRequest,
 },
]
