/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlResetJobRequest } from './schemas/ml_reset_job.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlResetJobApis: EsApiDefinition[] = [
 {
   name: "reset-job",
   namespace: "ml",
   description: "Reset an anomaly detection job.",
   method: "POST",
   path: "/_ml/anomaly_detectors/{job_id}/_reset",
   input: MlResetJobRequest,
 },
]
