/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlStopTrainedModelDeploymentRequest } from './schemas/ml_stop_trained_model_deployment.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlStopTrainedModelDeploymentApis: EsApiDefinition[] = [
 {
   name: "stop-trained-model-deployment",
   namespace: "ml",
   description: "Stop a trained model deployment.",
   method: "POST",
   path: "/_ml/trained_models/{model_id}/deployment/_stop",
   input: MlStopTrainedModelDeploymentRequest,
 },
]
