/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlStopDataFrameAnalyticsRequest } from './schemas/ml_stop_data_frame_analytics.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlStopDataFrameAnalyticsApis: EsApiDefinition[] = [
 {
   name: "stop-data-frame-analytics",
   namespace: "ml",
   description: "Stop data frame analytics jobs.",
   method: "POST",
   path: "/_ml/data_frame/analytics/{id}/_stop",
   input: MlStopDataFrameAnalyticsRequest,
 },
]
