/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlStopDatafeedRequest } from './schemas/ml_stop_datafeed.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlStopDatafeedApis: EsApiDefinition[] = [
 {
   name: "stop-datafeed",
   namespace: "ml",
   description: "Stop datafeeds.",
   method: "POST",
   path: "/_ml/datafeeds/{datafeed_id}/_stop",
   input: MlStopDatafeedRequest,
 },
]
