/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlStartDatafeedRequest } from './schemas/ml_start_datafeed.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlStartDatafeedApis: EsApiDefinition[] = [
 {
   name: "start-datafeed",
   namespace: "ml",
   description: "Start datafeeds.",
   method: "POST",
   path: "/_ml/datafeeds/{datafeed_id}/_start",
   input: MlStartDatafeedRequest,
 },
]
