/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlStartTrainedModelDeploymentRequest } from './schemas/ml_start_trained_model_deployment.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlStartTrainedModelDeploymentApis: EsApiDefinition[] = [
 {
   name: "start-trained-model-deployment",
   namespace: "ml",
   description: "Start a trained model deployment.",
   method: "POST",
   path: "/_ml/trained_models/{model_id}/deployment/_start",
   input: MlStartTrainedModelDeploymentRequest,
 },
]
