/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlStartDataFrameAnalyticsRequest } from './schemas/ml_start_data_frame_analytics.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlStartDataFrameAnalyticsApis: EsApiDefinition[] = [
 {
   name: "start-data-frame-analytics",
   namespace: "ml",
   description: "Start a data frame analytics job.",
   method: "POST",
   path: "/_ml/data_frame/analytics/{id}/_start",
   input: MlStartDataFrameAnalyticsRequest,
 },
]
