/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { MlUpdateTrainedModelDeploymentRequest } from '@elastic/es-schemas/ml_update_trained_model_deployment.js'
import type { EsApiDefinition } from '../types.ts'

export const mlUpdateTrainedModelDeploymentApis: EsApiDefinition[] = [
 {
  name: "update-trained-model-deployment",
  namespace: "ml",
  description: "Update a trained model deployment.",
  method: "POST",
  path: "/_ml/trained_models/{model_id}/deployment/_update",
  input: MlUpdateTrainedModelDeploymentRequest,
 },
]
