/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlUpdateDatafeedRequest } from './schemas/ml_update_datafeed.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlUpdateDatafeedApis: EsApiDefinition[] = [
 {
   name: "update-datafeed",
   namespace: "ml",
   description: "Update a datafeed.",
   method: "POST",
   path: "/_ml/datafeeds/{datafeed_id}/_update",
   input: MlUpdateDatafeedRequest,
 },
]
