/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlUpdateTrainedModelDeploymentRequest } from './schemas/ml_update_trained_model_deployment.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlUpdateTrainedModelDeploymentApis: EsApiDefinition[] = [
 {
   name: "update-trained-model-deployment",
   namespace: "ml",
   description: "Update a trained model deployment.",
   method: "POST",
   path: "/_ml/trained_models/{model_id}/deployment/_update",
   input: MlUpdateTrainedModelDeploymentRequest,
 },
]
