/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlUpdateFilterRequest } from './schemas/ml_update_filter.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlUpdateFilterApis: EsApiDefinition[] = [
 {
   name: "update-filter",
   namespace: "ml",
   description: "Update a filter.",
   method: "POST",
   path: "/_ml/filters/{filter_id}/_update",
   input: MlUpdateFilterRequest,
 },
]
