/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlUpdateJobRequest } from './schemas/ml_update_job.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlUpdateJobApis: EsApiDefinition[] = [
 {
   name: "update-job",
   namespace: "ml",
   description: "Update an anomaly detection job.",
   method: "POST",
   path: "/_ml/anomaly_detectors/{job_id}/_update",
   input: MlUpdateJobRequest,
 },
]
