/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MlUpdateDataFrameAnalyticsRequest } from './schemas/ml_update_data_frame_analytics.ts'
import type { EsApiDefinition } from '../types.ts'

export const mlUpdateDataFrameAnalyticsApis: EsApiDefinition[] = [
 {
   name: "update-data-frame-analytics",
   namespace: "ml",
   description: "Update a data frame analytics job.",
   method: "POST",
   path: "/_ml/data_frame/analytics/{id}/_update",
   input: MlUpdateDataFrameAnalyticsRequest,
 },
]
