/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { z } from 'zod'
import { MsearchTemplateRequest } from './schemas/msearch_template.ts'
import type { EsApiDefinition } from '../types.ts'

const MsearchTemplateRequestPassthrough = MsearchTemplateRequest.extend({
  search_templates: z.array(z.any()).optional().meta({ found_in: 'body' })
})

export const msearchTemplateApis: EsApiDefinition[] = [
 {
   name: "msearch-template",
   description: "Run multiple templated searches.",
   method: "GET",
   path: "/{index}/_msearch/template",
   input: MsearchTemplateRequestPassthrough,
   bodyFormat: 'ndjson',
 },
]
