/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { z } from 'zod'
import { MsearchRequest } from './schemas/msearch.ts'
import type { EsApiDefinition } from '../types.ts'

const MsearchRequestPassthrough = MsearchRequest.extend({
  searches: z.array(z.any()).optional().meta({ found_in: 'body' })
})

export const msearchApis: EsApiDefinition[] = [
 {
   name: "msearch",
   description: "Run multiple searches.",
   method: "GET",
   path: "/{index}/_msearch",
   input: MsearchRequestPassthrough,
   bodyFormat: 'ndjson',
 },
]
