/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { MtermvectorsRequest } from './schemas/mtermvectors.ts'
import type { EsApiDefinition } from '../types.ts'

export const mtermvectorsApis: EsApiDefinition[] = [
 {
   name: "mtermvectors",
   description: "Get multiple term vectors.",
   method: "GET",
   path: "/{index}/_mtermvectors",
   input: MtermvectorsRequest,
 },
]
