/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { NodesClearRepositoriesMeteringArchiveRequest } from '@elastic/es-schemas/nodes_clear_repositories_metering_archive.js'
import type { EsApiDefinition } from '../types.ts'

export const nodesClearRepositoriesMeteringArchiveApis: EsApiDefinition[] = [
 {
  name: "clear-repositories-metering-archive",
  namespace: "nodes",
  description: "Clear the archived repositories metering.",
  method: "DELETE",
  path: "/_nodes/{node_id}/_repositories_metering/{max_archive_version}",
  input: NodesClearRepositoriesMeteringArchiveRequest,
 },
]
