/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { NodesInfoRequest } from '@elastic/es-schemas/nodes_info.js'
import type { EsApiDefinition } from '../types.ts'

export const nodesInfoApis: EsApiDefinition[] = [
 {
  name: "info",
  namespace: "nodes",
  description: "Get node information.",
  method: "GET",
  path: "/_nodes/{node_id}/{metric}",
  input: NodesInfoRequest,
 },
]
