/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { OpenPointInTimeRequest } from './schemas/open_point_in_time.ts'
import type { EsApiDefinition } from '../types.ts'

export const openPointInTimeApis: EsApiDefinition[] = [
 {
   name: "open-point-in-time",
   description: "Open a point in time.",
   method: "POST",
   path: "/{index}/_pit",
   input: OpenPointInTimeRequest,
 },
]
