/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { OpenPointInTimeRequest } from './schemas/_global.ts'
import type { EsApiDefinition } from '../types.ts'

export const openPointInTimeApis: EsApiDefinition[] = [
  {
    name: 'open-point-in-time',
    description: 'Open a point in time.',
    method: 'POST',
    path: '/{index}/_pit',
    input: OpenPointInTimeRequest
  }
]
