/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { PingRequest } from './schemas/ping.ts'
import type { EsApiDefinition } from '../types.ts'

export const pingApis: EsApiDefinition[] = [
 {
   name: "ping",
   description: "Ping the cluster.",
   method: "HEAD",
   path: "/",
   input: PingRequest,
 },
]
