/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { PingRequest } from './schemas/_global.ts'
import type { EsApiDefinition } from '../types.ts'

export const pingApis: EsApiDefinition[] = [
  {
    name: 'ping',
    description: 'Ping the cluster.',
    method: 'HEAD',
    path: '/',
    input: PingRequest
  }
]
