/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ProjectGetRoutingRequest } from './schemas/project_get_routing.ts'
import type { EsApiDefinition } from '../types.ts'

export const projectGetRoutingApis: EsApiDefinition[] = [
 {
   name: "get-routing",
   namespace: "project",
   description: "Get a project routing expression.",
   method: "GET",
   path: "/_project_routing/{name}",
   input: ProjectGetRoutingRequest,
 },
]
