/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { ProjectCreateManyRoutingRequest, ProjectCreateRoutingRequest, ProjectDeleteRoutingRequest, ProjectGetManyRoutingRequest, ProjectGetRoutingRequest, ProjectTagsRequest } from '@elastic/es-schemas/project.js'
import type { EsApiDefinition } from '../types.ts'

export const projectApis: EsApiDefinition[] = [
  {
    name: 'create-many-routing',
    namespace: 'project',
    description: 'Create or update project routing expressions.',
    method: 'PUT',
    path: '/_project_routing',
    input: ProjectCreateManyRoutingRequest
  },
  {
    name: 'create-routing',
    namespace: 'project',
    description: 'Create or update a project routing expression.',
    method: 'PUT',
    path: '/_project_routing/{name}',
    input: ProjectCreateRoutingRequest
  },
  {
    name: 'delete-routing',
    namespace: 'project',
    description: 'Delete a project routing expression.',
    method: 'DELETE',
    path: '/_project_routing/{name}',
    input: ProjectDeleteRoutingRequest
  },
  {
    name: 'get-many-routing',
    namespace: 'project',
    description: 'Get project routing expressions.',
    method: 'GET',
    path: '/_project_routing',
    input: ProjectGetManyRoutingRequest
  },
  {
    name: 'get-routing',
    namespace: 'project',
    description: 'Get a project routing expression.',
    method: 'GET',
    path: '/_project_routing/{name}',
    input: ProjectGetRoutingRequest
  },
  {
    name: 'tags',
    namespace: 'project',
    description: 'Get tags.',
    method: 'GET',
    path: '/_project/tags',
    input: ProjectTagsRequest
  }
]
