/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ProjectTagsRequest } from './schemas/project_tags.ts'
import type { EsApiDefinition } from '../types.ts'

export const projectTagsApis: EsApiDefinition[] = [
 {
   name: "tags",
   namespace: "project",
   description: "Get tags.",
   method: "GET",
   path: "/_project/tags",
   input: ProjectTagsRequest,
 },
]
