/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { ProjectGetManyRoutingRequest } from '@elastic/es-schemas/project_get_many_routing.js'
import type { EsApiDefinition } from '../types.ts'

export const projectGetManyRoutingApis: EsApiDefinition[] = [
 {
  name: "get-many-routing",
  namespace: "project",
  description: "Get project routing expressions.",
  method: "GET",
  path: "/_project_routing",
  input: ProjectGetManyRoutingRequest,
 },
]
