/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ProjectGetManyRoutingRequest } from './schemas/project_get_many_routing.ts'
import type { EsApiDefinition } from '../types.ts'

export const projectGetManyRoutingApis: EsApiDefinition[] = [
 {
   name: "get-many-routing",
   namespace: "project",
   description: "Get project routing expressions.",
   method: "GET",
   path: "/_project_routing",
   input: ProjectGetManyRoutingRequest,
 },
]
