/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ProjectDeleteRoutingRequest } from './schemas/project_delete_routing.ts'
import type { EsApiDefinition } from '../types.ts'

export const projectDeleteRoutingApis: EsApiDefinition[] = [
 {
   name: "delete-routing",
   namespace: "project",
   description: "Delete a project routing expression.",
   method: "DELETE",
   path: "/_project_routing/{name}",
   input: ProjectDeleteRoutingRequest,
 },
]
