/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { ProjectTagsRequest } from '@elastic/es-schemas/project_tags.js'
import type { EsApiDefinition } from '../types.ts'

export const projectTagsApis: EsApiDefinition[] = [
 {
  name: "tags",
  namespace: "project",
  description: "Get tags.",
  method: "GET",
  path: "/_project/tags",
  input: ProjectTagsRequest,
 },
]
