/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ProjectCreateManyRoutingRequest } from './schemas/project_create_many_routing.ts'
import type { EsApiDefinition } from '../types.ts'

export const projectCreateManyRoutingApis: EsApiDefinition[] = [
 {
   name: "create-many-routing",
   namespace: "project",
   description: "Create or update project routing expressions.",
   method: "PUT",
   path: "/_project_routing",
   input: ProjectCreateManyRoutingRequest,
 },
]
