/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { ProjectDeleteRoutingRequest } from '@elastic/es-schemas/project_delete_routing.js'
import type { EsApiDefinition } from '../types.ts'

export const projectDeleteRoutingApis: EsApiDefinition[] = [
 {
  name: "delete-routing",
  namespace: "project",
  description: "Delete a project routing expression.",
  method: "DELETE",
  path: "/_project_routing/{name}",
  input: ProjectDeleteRoutingRequest,
 },
]
