/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ProjectCreateRoutingRequest } from './schemas/project_create_routing.ts'
import type { EsApiDefinition } from '../types.ts'

export const projectCreateRoutingApis: EsApiDefinition[] = [
 {
   name: "create-routing",
   namespace: "project",
   description: "Create or update a project routing expression.",
   method: "PUT",
   path: "/_project_routing/{name}",
   input: ProjectCreateRoutingRequest,
 },
]
