/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { PutScriptRequest } from './schemas/put_script.ts'
import type { EsApiDefinition } from '../types.ts'

export const putScriptApis: EsApiDefinition[] = [
 {
   name: "put-script",
   description: "Create or update a script or search template.",
   method: "PUT",
   path: "/_scripts/{id}/{context}",
   input: PutScriptRequest,
 },
]
