/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { QueryRulesGetRuleRequest } from './schemas/query_rules_get_rule.ts'
import type { EsApiDefinition } from '../types.ts'

export const queryRulesGetRuleApis: EsApiDefinition[] = [
 {
   name: "get-rule",
   namespace: "query-rules",
   description: "Get a query rule.",
   method: "GET",
   path: "/_query_rules/{ruleset_id}/_rule/{rule_id}",
   input: QueryRulesGetRuleRequest,
 },
]
