/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { QueryRulesListRulesetsRequest } from '@elastic/es-schemas/query_rules_list_rulesets.js'
import type { EsApiDefinition } from '../types.ts'

export const queryRulesListRulesetsApis: EsApiDefinition[] = [
 {
  name: "list-rulesets",
  namespace: "query-rules",
  description: "Get all query rulesets.",
  method: "GET",
  path: "/_query_rules",
  input: QueryRulesListRulesetsRequest,
 },
]
