/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { QueryRulesDeleteRuleRequest } from '@elastic/es-schemas/query_rules_delete_rule.js'
import type { EsApiDefinition } from '../types.ts'

export const queryRulesDeleteRuleApis: EsApiDefinition[] = [
 {
  name: "delete-rule",
  namespace: "query-rules",
  description: "Delete a query rule.",
  method: "DELETE",
  path: "/_query_rules/{ruleset_id}/_rule/{rule_id}",
  input: QueryRulesDeleteRuleRequest,
 },
]
