/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { QueryRulesTestRequest } from './schemas/query_rules_test.ts'
import type { EsApiDefinition } from '../types.ts'

export const queryRulesTestApis: EsApiDefinition[] = [
 {
   name: "test",
   namespace: "query-rules",
   description: "Test a query ruleset.",
   method: "POST",
   path: "/_query_rules/{ruleset_id}/_test",
   input: QueryRulesTestRequest,
 },
]
