/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { QueryRulesGetRulesetRequest } from '@elastic/es-schemas/query_rules_get_ruleset.js'
import type { EsApiDefinition } from '../types.ts'

export const queryRulesGetRulesetApis: EsApiDefinition[] = [
 {
  name: "get-ruleset",
  namespace: "query-rules",
  description: "Get a query ruleset.",
  method: "GET",
  path: "/_query_rules/{ruleset_id}",
  input: QueryRulesGetRulesetRequest,
 },
]
