/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { QueryRulesDeleteRuleRequest, QueryRulesDeleteRulesetRequest, QueryRulesGetRuleRequest, QueryRulesGetRulesetRequest, QueryRulesListRulesetsRequest, QueryRulesPutRuleRequest, QueryRulesPutRulesetRequest, QueryRulesTestRequest } from './schemas/query_rules.ts'
import type { EsApiDefinition } from '../types.ts'

export const queryRulesApis: EsApiDefinition[] = [
  {
    name: 'delete-rule',
    namespace: 'query-rules',
    description: 'Delete a query rule.',
    method: 'DELETE',
    path: '/_query_rules/{ruleset_id}/_rule/{rule_id}',
    input: QueryRulesDeleteRuleRequest
  },
  {
    name: 'delete-ruleset',
    namespace: 'query-rules',
    description: 'Delete a query ruleset.',
    method: 'DELETE',
    path: '/_query_rules/{ruleset_id}',
    input: QueryRulesDeleteRulesetRequest
  },
  {
    name: 'get-rule',
    namespace: 'query-rules',
    description: 'Get a query rule.',
    method: 'GET',
    path: '/_query_rules/{ruleset_id}/_rule/{rule_id}',
    input: QueryRulesGetRuleRequest
  },
  {
    name: 'get-ruleset',
    namespace: 'query-rules',
    description: 'Get a query ruleset.',
    method: 'GET',
    path: '/_query_rules/{ruleset_id}',
    input: QueryRulesGetRulesetRequest
  },
  {
    name: 'list-rulesets',
    namespace: 'query-rules',
    description: 'Get all query rulesets.',
    method: 'GET',
    path: '/_query_rules',
    input: QueryRulesListRulesetsRequest
  },
  {
    name: 'put-rule',
    namespace: 'query-rules',
    description: 'Create or update a query rule.',
    method: 'PUT',
    path: '/_query_rules/{ruleset_id}/_rule/{rule_id}',
    input: QueryRulesPutRuleRequest
  },
  {
    name: 'put-ruleset',
    namespace: 'query-rules',
    description: 'Create or update a query ruleset.',
    method: 'PUT',
    path: '/_query_rules/{ruleset_id}',
    input: QueryRulesPutRulesetRequest
  },
  {
    name: 'test',
    namespace: 'query-rules',
    description: 'Test a query ruleset.',
    method: 'POST',
    path: '/_query_rules/{ruleset_id}/_test',
    input: QueryRulesTestRequest
  }
]
