/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { QueryRulesDeleteRulesetRequest } from './schemas/query_rules_delete_ruleset.ts'
import type { EsApiDefinition } from '../types.ts'

export const queryRulesDeleteRulesetApis: EsApiDefinition[] = [
 {
   name: "delete-ruleset",
   namespace: "query-rules",
   description: "Delete a query ruleset.",
   method: "DELETE",
   path: "/_query_rules/{ruleset_id}",
   input: QueryRulesDeleteRulesetRequest,
 },
]
