/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { QueryRulesPutRuleRequest } from './schemas/query_rules_put_rule.ts'
import type { EsApiDefinition } from '../types.ts'

export const queryRulesPutRuleApis: EsApiDefinition[] = [
 {
   name: "put-rule",
   namespace: "query-rules",
   description: "Create or update a query rule.",
   method: "PUT",
   path: "/_query_rules/{ruleset_id}/_rule/{rule_id}",
   input: QueryRulesPutRuleRequest,
 },
]
