/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { QueryRulesListRulesetsRequest } from './schemas/query_rules_list_rulesets.ts'
import type { EsApiDefinition } from '../types.ts'

export const queryRulesListRulesetsApis: EsApiDefinition[] = [
 {
   name: "list-rulesets",
   namespace: "query-rules",
   description: "Get all query rulesets.",
   method: "GET",
   path: "/_query_rules",
   input: QueryRulesListRulesetsRequest,
 },
]
