/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { QueryRulesGetRulesetRequest } from './schemas/query_rules_get_ruleset.ts'
import type { EsApiDefinition } from '../types.ts'

export const queryRulesGetRulesetApis: EsApiDefinition[] = [
 {
   name: "get-ruleset",
   namespace: "query-rules",
   description: "Get a query ruleset.",
   method: "GET",
   path: "/_query_rules/{ruleset_id}",
   input: QueryRulesGetRulesetRequest,
 },
]
