/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { ReindexRequest } from '@elastic/es-schemas/_global.reindex.js'
import type { EsApiDefinition } from '../types.ts'

export const reindexApis: EsApiDefinition[] = [
 {
  name: "reindex",
  description: "Reindex documents.",
  method: "POST",
  path: "/_reindex",
  input: ReindexRequest,
 },
]
