/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ReindexRequest } from './schemas/reindex.ts'
import type { EsApiDefinition } from '../types.ts'

export const reindexApis: EsApiDefinition[] = [
 {
   name: "reindex",
   description: "Reindex documents.",
   method: "POST",
   path: "/_reindex",
   input: ReindexRequest,
 },
]
