/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { RenderSearchTemplateRequest } from './schemas/render_search_template.ts'
import type { EsApiDefinition } from '../types.ts'

export const renderSearchTemplateApis: EsApiDefinition[] = [
 {
   name: "render-search-template",
   description: "Render a search template.",
   method: "GET",
   path: "/_render/template/{id}",
   input: RenderSearchTemplateRequest,
 },
]
