/**
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { RenderSearchTemplateRequest } from './schemas/_global.ts'
import type { EsApiDefinition } from '../types.ts'

export const renderSearchTemplateApis: EsApiDefinition[] = [
  {
    name: 'render-search-template',
    description: 'Render a search template.',
    method: 'GET',
    path: '/_render/template/{id}',
    input: RenderSearchTemplateRequest
  }
]
