/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { RenderSearchTemplateRequest } from '@elastic/es-schemas/_global.render_search_template.js'
import type { EsApiDefinition } from '../types.ts'

export const renderSearchTemplateApis: EsApiDefinition[] = [
 {
  name: "render-search-template",
  description: "Render a search template.",
  method: "GET",
  path: "/_render/template/{id}",
  input: RenderSearchTemplateRequest,
 },
]
