/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { RollupGetRollupCapsRequest } from '@elastic/es-schemas/rollup_get_rollup_caps.js'
import type { EsApiDefinition } from '../types.ts'

export const rollupGetRollupCapsApis: EsApiDefinition[] = [
 {
  name: "get-rollup-caps",
  namespace: "rollup",
  description: "Get the rollup job capabilities.",
  method: "GET",
  path: "/_rollup/data/{id}",
  input: RollupGetRollupCapsRequest,
 },
]
