/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ScriptsPainlessExecuteRequest } from './schemas/scripts_painless_execute.ts'
import type { EsApiDefinition } from '../types.ts'

export const scriptsPainlessExecuteApis: EsApiDefinition[] = [
 {
   name: "scripts-painless-execute",
   description: "Run a script.",
   method: "GET",
   path: "/_scripts/painless/_execute",
   input: ScriptsPainlessExecuteRequest,
 },
]
