/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { ScrollRequest } from './schemas/scroll.ts'
import type { EsApiDefinition } from '../types.ts'

export const scrollApis: EsApiDefinition[] = [
 {
   name: "scroll",
   description: "Run a scrolling search.",
   method: "GET",
   path: "/_search/scroll",
   input: ScrollRequest,
 },
]
