/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SearchMvtRequest } from './schemas/search_mvt.ts'
import type { EsApiDefinition } from '../types.ts'

export const searchMvtApis: EsApiDefinition[] = [
 {
   name: "search-mvt",
   description: "Search a vector tile.",
   method: "POST",
   path: "/{index}/_mvt/{field}/{zoom}/{x}/{y}",
   input: SearchMvtRequest,
 },
]
