/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SearchApplicationDeleteBehavioralAnalyticsRequest, SearchApplicationDeleteRequest, SearchApplicationGetBehavioralAnalyticsRequest, SearchApplicationGetRequest, SearchApplicationListRequest, SearchApplicationPutBehavioralAnalyticsRequest, SearchApplicationPutRequest, SearchApplicationSearchRequest } from '@elastic/es-schemas/search_application.js'
import type { EsApiDefinition } from '../types.ts'

export const searchApplicationApis: EsApiDefinition[] = [
 {
  name: "delete",
  namespace: "search-application",
  description: "Delete a search application.",
  method: "DELETE",
  path: "/_application/search_application/{name}",
  input: SearchApplicationDeleteRequest,
 },
 {
  name: "delete-behavioral-analytics",
  namespace: "search-application",
  description: "Delete a behavioral analytics collection.",
  method: "DELETE",
  path: "/_application/analytics/{name}",
  input: SearchApplicationDeleteBehavioralAnalyticsRequest,
 },
 {
  name: "get",
  namespace: "search-application",
  description: "Get search application details.",
  method: "GET",
  path: "/_application/search_application/{name}",
  input: SearchApplicationGetRequest,
 },
 {
  name: "get-behavioral-analytics",
  namespace: "search-application",
  description: "Get behavioral analytics collections.",
  method: "GET",
  path: "/_application/analytics/{name}",
  input: SearchApplicationGetBehavioralAnalyticsRequest,
 },
 {
  name: "list",
  namespace: "search-application",
  description: "Get search applications.",
  method: "GET",
  path: "/_application/search_application",
  input: SearchApplicationListRequest,
 },
 {
  name: "put",
  namespace: "search-application",
  description: "Create or update a search application.",
  method: "PUT",
  path: "/_application/search_application/{name}",
  input: SearchApplicationPutRequest,
 },
 {
  name: "put-behavioral-analytics",
  namespace: "search-application",
  description: "Create a behavioral analytics collection.",
  method: "PUT",
  path: "/_application/analytics/{name}",
  input: SearchApplicationPutBehavioralAnalyticsRequest,
 },
 {
  name: "search",
  namespace: "search-application",
  description: "Run a search application search.",
  method: "GET",
  path: "/_application/search_application/{name}/_search",
  input: SearchApplicationSearchRequest,
 },
]
