/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SearchApplicationGetBehavioralAnalyticsRequest } from './schemas/search_application_get_behavioral_analytics.ts'
import type { EsApiDefinition } from '../types.ts'

export const searchApplicationGetBehavioralAnalyticsApis: EsApiDefinition[] = [
 {
   name: "get-behavioral-analytics",
   namespace: "search-application",
   description: "Get behavioral analytics collections.",
   method: "GET",
   path: "/_application/analytics/{name}",
   input: SearchApplicationGetBehavioralAnalyticsRequest,
 },
]
