/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SearchApplicationGetRequest } from './schemas/search_application_get.ts'
import type { EsApiDefinition } from '../types.ts'

export const searchApplicationGetApis: EsApiDefinition[] = [
 {
   name: "get",
   namespace: "search-application",
   description: "Get search application details.",
   method: "GET",
   path: "/_application/search_application/{name}",
   input: SearchApplicationGetRequest,
 },
]
