/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SearchApplicationPutRequest } from './schemas/search_application_put.ts'
import type { EsApiDefinition } from '../types.ts'

export const searchApplicationPutApis: EsApiDefinition[] = [
 {
   name: "put",
   namespace: "search-application",
   description: "Create or update a search application.",
   method: "PUT",
   path: "/_application/search_application/{name}",
   input: SearchApplicationPutRequest,
 },
]
