/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SearchApplicationDeleteBehavioralAnalyticsRequest } from './schemas/search_application_delete_behavioral_analytics.ts'
import type { EsApiDefinition } from '../types.ts'

export const searchApplicationDeleteBehavioralAnalyticsApis: EsApiDefinition[] = [
 {
   name: "delete-behavioral-analytics",
   namespace: "search-application",
   description: "Delete a behavioral analytics collection.",
   method: "DELETE",
   path: "/_application/analytics/{name}",
   input: SearchApplicationDeleteBehavioralAnalyticsRequest,
 },
]
