/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SearchMvtRequest } from '@elastic/es-schemas/_global.search_mvt.js'
import type { EsApiDefinition } from '../types.ts'

export const searchMvtApis: EsApiDefinition[] = [
 {
  name: "search-mvt",
  description: "Search a vector tile.",
  method: "POST",
  path: "/{index}/_mvt/{field}/{zoom}/{x}/{y}",
  input: SearchMvtRequest,
 },
]
