/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SearchableSnapshotsMountRequest } from '@elastic/es-schemas/searchable_snapshots_mount.js'
import type { EsApiDefinition } from '../types.ts'

export const searchableSnapshotsMountApis: EsApiDefinition[] = [
 {
  name: "mount",
  namespace: "searchable-snapshots",
  description: "Mount a snapshot.",
  method: "POST",
  path: "/_snapshot/{repository}/{snapshot}/_mount",
  input: SearchableSnapshotsMountRequest,
 },
]
