/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SearchApplicationPutBehavioralAnalyticsRequest } from './schemas/search_application_put_behavioral_analytics.ts'
import type { EsApiDefinition } from '../types.ts'

export const searchApplicationPutBehavioralAnalyticsApis: EsApiDefinition[] = [
 {
   name: "put-behavioral-analytics",
   namespace: "search-application",
   description: "Create a behavioral analytics collection.",
   method: "PUT",
   path: "/_application/analytics/{name}",
   input: SearchApplicationPutBehavioralAnalyticsRequest,
 },
]
