/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SearchApplicationGetBehavioralAnalyticsRequest } from '@elastic/es-schemas/search_application_get_behavioral_analytics.js'
import type { EsApiDefinition } from '../types.ts'

export const searchApplicationGetBehavioralAnalyticsApis: EsApiDefinition[] = [
 {
  name: "get-behavioral-analytics",
  namespace: "search-application",
  description: "Get behavioral analytics collections.",
  method: "GET",
  path: "/_application/analytics/{name}",
  input: SearchApplicationGetBehavioralAnalyticsRequest,
 },
]
