/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SearchApplicationSearchRequest } from './schemas/search_application_search.ts'
import type { EsApiDefinition } from '../types.ts'

export const searchApplicationSearchApis: EsApiDefinition[] = [
 {
   name: "search",
   namespace: "search-application",
   description: "Run a search application search.",
   method: "GET",
   path: "/_application/search_application/{name}/_search",
   input: SearchApplicationSearchRequest,
 },
]
