/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SearchApplicationDeleteRequest } from './schemas/search_application_delete.ts'
import type { EsApiDefinition } from '../types.ts'

export const searchApplicationDeleteApis: EsApiDefinition[] = [
 {
   name: "delete",
   namespace: "search-application",
   description: "Delete a search application.",
   method: "DELETE",
   path: "/_application/search_application/{name}",
   input: SearchApplicationDeleteRequest,
 },
]
