/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SearchApplicationListRequest } from './schemas/search_application_list.ts'
import type { EsApiDefinition } from '../types.ts'

export const searchApplicationListApis: EsApiDefinition[] = [
 {
   name: "list",
   namespace: "search-application",
   description: "Get search applications.",
   method: "GET",
   path: "/_application/search_application",
   input: SearchApplicationListRequest,
 },
]
