/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SearchApplicationDeleteRequest } from '@elastic/es-schemas/search_application_delete.js'
import type { EsApiDefinition } from '../types.ts'

export const searchApplicationDeleteApis: EsApiDefinition[] = [
 {
  name: "delete",
  namespace: "search-application",
  description: "Delete a search application.",
  method: "DELETE",
  path: "/_application/search_application/{name}",
  input: SearchApplicationDeleteRequest,
 },
]
