/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SearchRequest } from './schemas/search.ts'
import type { EsApiDefinition } from '../types.ts'

export const searchApis: EsApiDefinition[] = [
 {
   name: "search",
   description: "Run a search.",
   method: "GET",
   path: "/{index}/_search",
   input: SearchRequest,
 },
]
