/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SearchTemplateRequest } from './schemas/search_template.ts'
import type { EsApiDefinition } from '../types.ts'

export const searchTemplateApis: EsApiDefinition[] = [
 {
   name: "search-template",
   description: "Run a search with a search template.",
   method: "GET",
   path: "/{index}/_search/template",
   input: SearchTemplateRequest,
 },
]
