/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SecurityGetApiKeyRequest } from '@elastic/es-schemas/security_get_api_key.js'
import type { EsApiDefinition } from '../types.ts'

export const securityGetApiKeyApis: EsApiDefinition[] = [
 {
  name: "get-api-key",
  namespace: "security",
  description: "Get API key information.",
  method: "GET",
  path: "/_security/api_key",
  input: SecurityGetApiKeyRequest,
 },
]
