/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SecurityGetRoleRequest } from './schemas/security_get_role.ts'
import type { EsApiDefinition } from '../types.ts'

export const securityGetRoleApis: EsApiDefinition[] = [
 {
   name: "get-role",
   namespace: "security",
   description: "Get roles.",
   method: "GET",
   path: "/_security/role/{name}",
   input: SecurityGetRoleRequest,
 },
]
