/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SecurityGetServiceCredentialsRequest } from '@elastic/es-schemas/security_get_service_credentials.js'
import type { EsApiDefinition } from '../types.ts'

export const securityGetServiceCredentialsApis: EsApiDefinition[] = [
 {
  name: "get-service-credentials",
  namespace: "security",
  description: "Get service account credentials.",
  method: "GET",
  path: "/_security/service/{namespace}/{service}/credential",
  input: SecurityGetServiceCredentialsRequest,
 },
]
