/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SecurityGetApiKeyRequest } from './schemas/security_get_api_key.ts'
import type { EsApiDefinition } from '../types.ts'

export const securityGetApiKeyApis: EsApiDefinition[] = [
 {
   name: "get-api-key",
   namespace: "security",
   description: "Get API key information.",
   method: "GET",
   path: "/_security/api_key",
   input: SecurityGetApiKeyRequest,
 },
]
