/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SecuritySamlCompleteLogoutRequest } from '@elastic/es-schemas/security_saml_complete_logout.js'
import type { EsApiDefinition } from '../types.ts'

export const securitySamlCompleteLogoutApis: EsApiDefinition[] = [
 {
  name: "saml-complete-logout",
  namespace: "security",
  description: "Logout of SAML completely.",
  method: "POST",
  path: "/_security/saml/complete_logout",
  input: SecuritySamlCompleteLogoutRequest,
 },
]
