/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SecurityChangePasswordRequest } from '@elastic/es-schemas/security_change_password.js'
import type { EsApiDefinition } from '../types.ts'

export const securityChangePasswordApis: EsApiDefinition[] = [
 {
  name: "change-password",
  namespace: "security",
  description: "Change passwords.",
  method: "PUT",
  path: "/_security/user/{username}/_password",
  input: SecurityChangePasswordRequest,
 },
]
