/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SecurityInvalidateApiKeyRequest } from './schemas/security_invalidate_api_key.ts'
import type { EsApiDefinition } from '../types.ts'

export const securityInvalidateApiKeyApis: EsApiDefinition[] = [
 {
   name: "invalidate-api-key",
   namespace: "security",
   description: "Invalidate API keys.",
   method: "DELETE",
   path: "/_security/api_key",
   input: SecurityInvalidateApiKeyRequest,
 },
]
