/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SecurityGetRoleMappingRequest } from '@elastic/es-schemas/security_get_role_mapping.js'
import type { EsApiDefinition } from '../types.ts'

export const securityGetRoleMappingApis: EsApiDefinition[] = [
 {
  name: "get-role-mapping",
  namespace: "security",
  description: "Get role mappings.",
  method: "GET",
  path: "/_security/role_mapping/{name}",
  input: SecurityGetRoleMappingRequest,
 },
]
