/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SecurityDeleteServiceTokenRequest } from '@elastic/es-schemas/security_delete_service_token.js'
import type { EsApiDefinition } from '../types.ts'

export const securityDeleteServiceTokenApis: EsApiDefinition[] = [
 {
  name: "delete-service-token",
  namespace: "security",
  description: "Delete service account tokens.",
  method: "DELETE",
  path: "/_security/service/{namespace}/{service}/credential/token/{name}",
  input: SecurityDeleteServiceTokenRequest,
 },
]
