/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SecurityDeletePrivilegesRequest } from '@elastic/es-schemas/security_delete_privileges.js'
import type { EsApiDefinition } from '../types.ts'

export const securityDeletePrivilegesApis: EsApiDefinition[] = [
 {
  name: "delete-privileges",
  namespace: "security",
  description: "Delete application privileges.",
  method: "DELETE",
  path: "/_security/privilege/{application}/{name}",
  input: SecurityDeletePrivilegesRequest,
 },
]
