/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SecurityGetSettingsRequest } from '@elastic/es-schemas/security_get_settings.js'
import type { EsApiDefinition } from '../types.ts'

export const securityGetSettingsApis: EsApiDefinition[] = [
 {
  name: "get-settings",
  namespace: "security",
  description: "Get security index settings.",
  method: "GET",
  path: "/_security/settings",
  input: SecurityGetSettingsRequest,
 },
]
