/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SecurityQueryRoleRequest } from './schemas/security_query_role.ts'
import type { EsApiDefinition } from '../types.ts'

export const securityQueryRoleApis: EsApiDefinition[] = [
 {
   name: "query-role",
   namespace: "security",
   description: "Find roles with a query.",
   method: "GET",
   path: "/_security/_query/role",
   input: SecurityQueryRoleRequest,
 },
]
