/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SecuritySamlLogoutRequest } from '@elastic/es-schemas/security_saml_logout.js'
import type { EsApiDefinition } from '../types.ts'

export const securitySamlLogoutApis: EsApiDefinition[] = [
 {
  name: "saml-logout",
  namespace: "security",
  description: "Logout of SAML.",
  method: "POST",
  path: "/_security/saml/logout",
  input: SecuritySamlLogoutRequest,
 },
]
