/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SecurityAuthenticateRequest } from '@elastic/es-schemas/security_authenticate.js'
import type { EsApiDefinition } from '../types.ts'

export const securityAuthenticateApis: EsApiDefinition[] = [
 {
  name: "authenticate",
  namespace: "security",
  description: "Authenticate a user.",
  method: "GET",
  path: "/_security/_authenticate",
  input: SecurityAuthenticateRequest,
 },
]
