/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SecurityGetTokenRequest } from '@elastic/es-schemas/security_get_token.js'
import type { EsApiDefinition } from '../types.ts'

export const securityGetTokenApis: EsApiDefinition[] = [
 {
  name: "get-token",
  namespace: "security",
  description: "Get a token.",
  method: "POST",
  path: "/_security/oauth2/token",
  input: SecurityGetTokenRequest,
 },
]
