/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SecurityClearCachedRealmsRequest } from '@elastic/es-schemas/security_clear_cached_realms.js'
import type { EsApiDefinition } from '../types.ts'

export const securityClearCachedRealmsApis: EsApiDefinition[] = [
 {
  name: "clear-cached-realms",
  namespace: "security",
  description: "Clear the user cache.",
  method: "POST",
  path: "/_security/realm/{realms}/_clear_cache",
  input: SecurityClearCachedRealmsRequest,
 },
]
