/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SecurityHasPrivilegesRequest } from './schemas/security_has_privileges.ts'
import type { EsApiDefinition } from '../types.ts'

export const securityHasPrivilegesApis: EsApiDefinition[] = [
 {
   name: "has-privileges",
   namespace: "security",
   description: "Check user privileges.",
   method: "GET",
   path: "/_security/user/{user}/_has_privileges",
   input: SecurityHasPrivilegesRequest,
 },
]
