/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SecurityInvalidateApiKeyRequest } from '@elastic/es-schemas/security_invalidate_api_key.js'
import type { EsApiDefinition } from '../types.ts'

export const securityInvalidateApiKeyApis: EsApiDefinition[] = [
 {
  name: "invalidate-api-key",
  namespace: "security",
  description: "Invalidate API keys.",
  method: "DELETE",
  path: "/_security/api_key",
  input: SecurityInvalidateApiKeyRequest,
 },
]
