/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SecurityPutRoleRequest } from './schemas/security_put_role.ts'
import type { EsApiDefinition } from '../types.ts'

export const securityPutRoleApis: EsApiDefinition[] = [
 {
   name: "put-role",
   namespace: "security",
   description: "Create or update roles.",
   method: "PUT",
   path: "/_security/role/{name}",
   input: SecurityPutRoleRequest,
 },
]
