/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SecurityDeleteRoleRequest } from '@elastic/es-schemas/security_delete_role.js'
import type { EsApiDefinition } from '../types.ts'

export const securityDeleteRoleApis: EsApiDefinition[] = [
 {
  name: "delete-role",
  namespace: "security",
  description: "Delete roles.",
  method: "DELETE",
  path: "/_security/role/{name}",
  input: SecurityDeleteRoleRequest,
 },
]
