/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SecuritySamlPrepareAuthenticationRequest } from '@elastic/es-schemas/security_saml_prepare_authentication.js'
import type { EsApiDefinition } from '../types.ts'

export const securitySamlPrepareAuthenticationApis: EsApiDefinition[] = [
 {
  name: "saml-prepare-authentication",
  namespace: "security",
  description: "Prepare SAML authentication.",
  method: "POST",
  path: "/_security/saml/prepare",
  input: SecuritySamlPrepareAuthenticationRequest,
 },
]
