/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SecurityEnrollNodeRequest } from '@elastic/es-schemas/security_enroll_node.js'
import type { EsApiDefinition } from '../types.ts'

export const securityEnrollNodeApis: EsApiDefinition[] = [
 {
  name: "enroll-node",
  namespace: "security",
  description: "Enroll a node.",
  method: "GET",
  path: "/_security/enroll/node",
  input: SecurityEnrollNodeRequest,
 },
]
