/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SecurityDeleteRoleRequest } from './schemas/security_delete_role.ts'
import type { EsApiDefinition } from '../types.ts'

export const securityDeleteRoleApis: EsApiDefinition[] = [
 {
   name: "delete-role",
   namespace: "security",
   description: "Delete roles.",
   method: "DELETE",
   path: "/_security/role/{name}",
   input: SecurityDeleteRoleRequest,
 },
]
