/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SecurityQueryApiKeysRequest } from './schemas/security_query_api_keys.ts'
import type { EsApiDefinition } from '../types.ts'

export const securityQueryApiKeysApis: EsApiDefinition[] = [
 {
   name: "query-api-keys",
   namespace: "security",
   description: "Find API keys with a query.",
   method: "GET",
   path: "/_security/_query/api_key",
   input: SecurityQueryApiKeysRequest,
 },
]
