/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SecurityBulkUpdateApiKeysRequest } from '@elastic/es-schemas/security_bulk_update_api_keys.js'
import type { EsApiDefinition } from '../types.ts'

export const securityBulkUpdateApiKeysApis: EsApiDefinition[] = [
 {
  name: "bulk-update-api-keys",
  namespace: "security",
  description: "Bulk update API keys.",
  method: "POST",
  path: "/_security/api_key/_bulk_update",
  input: SecurityBulkUpdateApiKeysRequest,
 },
]
