/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SecurityDeleteUserRequest } from '@elastic/es-schemas/security_delete_user.js'
import type { EsApiDefinition } from '../types.ts'

export const securityDeleteUserApis: EsApiDefinition[] = [
 {
  name: "delete-user",
  namespace: "security",
  description: "Delete users.",
  method: "DELETE",
  path: "/_security/user/{username}",
  input: SecurityDeleteUserRequest,
 },
]
