/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SecurityPutUserRequest } from '@elastic/es-schemas/security_put_user.js'
import type { EsApiDefinition } from '../types.ts'

export const securityPutUserApis: EsApiDefinition[] = [
 {
  name: "put-user",
  namespace: "security",
  description: "Create or update users.",
  method: "PUT",
  path: "/_security/user/{username}",
  input: SecurityPutUserRequest,
 },
]
