/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SecurityCreateApiKeyRequest } from './schemas/security_create_api_key.ts'
import type { EsApiDefinition } from '../types.ts'

export const securityCreateApiKeyApis: EsApiDefinition[] = [
 {
   name: "create-api-key",
   namespace: "security",
   description: "Create an API key.",
   method: "PUT",
   path: "/_security/api_key",
   input: SecurityCreateApiKeyRequest,
 },
]
