/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SecurityUpdateUserProfileDataRequest } from '@elastic/es-schemas/security_update_user_profile_data.js'
import type { EsApiDefinition } from '../types.ts'

export const securityUpdateUserProfileDataApis: EsApiDefinition[] = [
 {
  name: "update-user-profile-data",
  namespace: "security",
  description: "Update user profile data.",
  method: "PUT",
  path: "/_security/profile/{uid}/_data",
  input: SecurityUpdateUserProfileDataRequest,
 },
]
