/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SecurityAuthenticateRequest, SecurityCreateApiKeyRequest, SecurityDeleteRoleRequest, SecurityGetApiKeyRequest, SecurityGetBuiltinPrivilegesRequest, SecurityGetRoleRequest, SecurityHasPrivilegesRequest, SecurityInvalidateApiKeyRequest, SecurityPutRoleRequest, SecurityQueryApiKeysRequest, SecurityQueryRoleRequest, SecurityUpdateApiKeyRequest } from '@elastic/es-schemas/security.js'
import type { EsApiDefinition } from '../types.ts'

export const securityApis: EsApiDefinition[] = [
 {
  name: "authenticate",
  namespace: "security",
  description: "Authenticate a user.",
  method: "GET",
  path: "/_security/_authenticate",
  input: SecurityAuthenticateRequest,
 },
 {
  name: "create-api-key",
  namespace: "security",
  description: "Create an API key.",
  method: "PUT",
  path: "/_security/api_key",
  input: SecurityCreateApiKeyRequest,
 },
 {
  name: "delete-role",
  namespace: "security",
  description: "Delete roles.",
  method: "DELETE",
  path: "/_security/role/{name}",
  input: SecurityDeleteRoleRequest,
 },
 {
  name: "get-api-key",
  namespace: "security",
  description: "Get API key information.",
  method: "GET",
  path: "/_security/api_key",
  input: SecurityGetApiKeyRequest,
 },
 {
  name: "get-builtin-privileges",
  namespace: "security",
  description: "Get builtin privileges.",
  method: "GET",
  path: "/_security/privilege/_builtin",
  input: SecurityGetBuiltinPrivilegesRequest,
 },
 {
  name: "get-role",
  namespace: "security",
  description: "Get roles.",
  method: "GET",
  path: "/_security/role/{name}",
  input: SecurityGetRoleRequest,
 },
 {
  name: "has-privileges",
  namespace: "security",
  description: "Check user privileges.",
  method: "GET",
  path: "/_security/user/{user}/_has_privileges",
  input: SecurityHasPrivilegesRequest,
 },
 {
  name: "invalidate-api-key",
  namespace: "security",
  description: "Invalidate API keys.",
  method: "DELETE",
  path: "/_security/api_key",
  input: SecurityInvalidateApiKeyRequest,
 },
 {
  name: "put-role",
  namespace: "security",
  description: "Create or update roles.",
  method: "PUT",
  path: "/_security/role/{name}",
  input: SecurityPutRoleRequest,
 },
 {
  name: "query-api-keys",
  namespace: "security",
  description: "Find API keys with a query.",
  method: "GET",
  path: "/_security/_query/api_key",
  input: SecurityQueryApiKeysRequest,
 },
 {
  name: "query-role",
  namespace: "security",
  description: "Find roles with a query.",
  method: "GET",
  path: "/_security/_query/role",
  input: SecurityQueryRoleRequest,
 },
 {
  name: "update-api-key",
  namespace: "security",
  description: "Update an API key.",
  method: "PUT",
  path: "/_security/api_key/{id}",
  input: SecurityUpdateApiKeyRequest,
 },
]
