/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SlmGetStatusRequest } from '@elastic/es-schemas/slm_get_status.js'
import type { EsApiDefinition } from '../types.ts'

export const slmGetStatusApis: EsApiDefinition[] = [
 {
  name: "get-status",
  namespace: "slm",
  description: "Get the snapshot lifecycle management status.",
  method: "GET",
  path: "/_slm/status",
  input: SlmGetStatusRequest,
 },
]
