/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SlmStopRequest } from '@elastic/es-schemas/slm_stop.js'
import type { EsApiDefinition } from '../types.ts'

export const slmStopApis: EsApiDefinition[] = [
 {
  name: "stop",
  namespace: "slm",
  description: "Stop snapshot lifecycle management.",
  method: "POST",
  path: "/_slm/stop",
  input: SlmStopRequest,
 },
]
