/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SnapshotDeleteRequest } from '@elastic/es-schemas/snapshot_delete.js'
import type { EsApiDefinition } from '../types.ts'

export const snapshotDeleteApis: EsApiDefinition[] = [
 {
  name: "delete",
  namespace: "snapshot",
  description: "Delete snapshots.",
  method: "DELETE",
  path: "/_snapshot/{repository}/{snapshot}",
  input: SnapshotDeleteRequest,
 },
]
