/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SnapshotCreateRequest } from '@elastic/es-schemas/snapshot_create.js'
import type { EsApiDefinition } from '../types.ts'

export const snapshotCreateApis: EsApiDefinition[] = [
 {
  name: "create",
  namespace: "snapshot",
  description: "Create a snapshot.",
  method: "PUT",
  path: "/_snapshot/{repository}/{snapshot}",
  input: SnapshotCreateRequest,
 },
]
