/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SnapshotGetRequest } from '@elastic/es-schemas/snapshot_get.js'
import type { EsApiDefinition } from '../types.ts'

export const snapshotGetApis: EsApiDefinition[] = [
 {
  name: "get",
  namespace: "snapshot",
  description: "Get snapshot information.",
  method: "GET",
  path: "/_snapshot/{repository}/{snapshot}",
  input: SnapshotGetRequest,
 },
]
