/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SnapshotRestoreRequest } from '@elastic/es-schemas/snapshot_restore.js'
import type { EsApiDefinition } from '../types.ts'

export const snapshotRestoreApis: EsApiDefinition[] = [
 {
  name: "restore",
  namespace: "snapshot",
  description: "Restore a snapshot.",
  method: "POST",
  path: "/_snapshot/{repository}/{snapshot}/_restore",
  input: SnapshotRestoreRequest,
 },
]
