/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SqlClearCursorRequest, SqlDeleteAsyncRequest, SqlGetAsyncRequest, SqlGetAsyncStatusRequest, SqlQueryRequest, SqlTranslateRequest } from '@elastic/es-schemas/sql.js'
import type { EsApiDefinition } from '../types.ts'

export const sqlApis: EsApiDefinition[] = [
 {
  name: "clear-cursor",
  namespace: "sql",
  description: "Clear an SQL search cursor.",
  method: "POST",
  path: "/_sql/close",
  input: SqlClearCursorRequest,
 },
 {
  name: "delete-async",
  namespace: "sql",
  description: "Delete an async SQL search.",
  method: "DELETE",
  path: "/_sql/async/delete/{id}",
  input: SqlDeleteAsyncRequest,
 },
 {
  name: "get-async",
  namespace: "sql",
  description: "Get async SQL search results.",
  method: "GET",
  path: "/_sql/async/{id}",
  input: SqlGetAsyncRequest,
 },
 {
  name: "get-async-status",
  namespace: "sql",
  description: "Get the async SQL search status.",
  method: "GET",
  path: "/_sql/async/status/{id}",
  input: SqlGetAsyncStatusRequest,
 },
 {
  name: "query",
  namespace: "sql",
  description: "Get SQL search results.",
  method: "POST",
  path: "/_sql",
  input: SqlQueryRequest,
 },
 {
  name: "translate",
  namespace: "sql",
  description: "Translate SQL into Elasticsearch queries.",
  method: "POST",
  path: "/_sql/translate",
  input: SqlTranslateRequest,
 },
]
