/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SqlGetAsyncStatusRequest } from './schemas/sql_get_async_status.ts'
import type { EsApiDefinition } from '../types.ts'

export const sqlGetAsyncStatusApis: EsApiDefinition[] = [
 {
   name: "get-async-status",
   namespace: "sql",
   description: "Get the async SQL search status.",
   method: "GET",
   path: "/_sql/async/status/{id}",
   input: SqlGetAsyncStatusRequest,
 },
]
