/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SqlGetAsyncRequest } from './schemas/sql_get_async.ts'
import type { EsApiDefinition } from '../types.ts'

export const sqlGetAsyncApis: EsApiDefinition[] = [
 {
   name: "get-async",
   namespace: "sql",
   description: "Get async SQL search results.",
   method: "GET",
   path: "/_sql/async/{id}",
   input: SqlGetAsyncRequest,
 },
]
