/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SqlGetAsyncRequest } from '@elastic/es-schemas/sql_get_async.js'
import type { EsApiDefinition } from '../types.ts'

export const sqlGetAsyncApis: EsApiDefinition[] = [
 {
  name: "get-async",
  namespace: "sql",
  description: "Get async SQL search results.",
  method: "GET",
  path: "/_sql/async/{id}",
  input: SqlGetAsyncRequest,
 },
]
