/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SqlDeleteAsyncRequest } from './schemas/sql_delete_async.ts'
import type { EsApiDefinition } from '../types.ts'

export const sqlDeleteAsyncApis: EsApiDefinition[] = [
 {
   name: "delete-async",
   namespace: "sql",
   description: "Delete an async SQL search.",
   method: "DELETE",
   path: "/_sql/async/delete/{id}",
   input: SqlDeleteAsyncRequest,
 },
]
