/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SqlDeleteAsyncRequest } from '@elastic/es-schemas/sql_delete_async.js'
import type { EsApiDefinition } from '../types.ts'

export const sqlDeleteAsyncApis: EsApiDefinition[] = [
 {
  name: "delete-async",
  namespace: "sql",
  description: "Delete an async SQL search.",
  method: "DELETE",
  path: "/_sql/async/delete/{id}",
  input: SqlDeleteAsyncRequest,
 },
]
