/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SqlClearCursorRequest } from './schemas/sql_clear_cursor.ts'
import type { EsApiDefinition } from '../types.ts'

export const sqlClearCursorApis: EsApiDefinition[] = [
 {
   name: "clear-cursor",
   namespace: "sql",
   description: "Clear an SQL search cursor.",
   method: "POST",
   path: "/_sql/close",
   input: SqlClearCursorRequest,
 },
]
