/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SqlTranslateRequest } from './schemas/sql_translate.ts'
import type { EsApiDefinition } from '../types.ts'

export const sqlTranslateApis: EsApiDefinition[] = [
 {
   name: "translate",
   namespace: "sql",
   description: "Translate SQL into Elasticsearch queries.",
   method: "POST",
   path: "/_sql/translate",
   input: SqlTranslateRequest,
 },
]
