/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SynonymsDeleteSynonymRequest } from './schemas/synonyms_delete_synonym.ts'
import type { EsApiDefinition } from '../types.ts'

export const synonymsDeleteSynonymApis: EsApiDefinition[] = [
 {
   name: "delete-synonym",
   namespace: "synonyms",
   description: "Delete a synonym set.",
   method: "DELETE",
   path: "/_synonyms/{id}",
   input: SynonymsDeleteSynonymRequest,
 },
]
