/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SynonymsPutSynonymRequest } from './schemas/synonyms_put_synonym.ts'
import type { EsApiDefinition } from '../types.ts'

export const synonymsPutSynonymApis: EsApiDefinition[] = [
 {
   name: "put-synonym",
   namespace: "synonyms",
   description: "Create or update a synonym set.",
   method: "PUT",
   path: "/_synonyms/{id}",
   input: SynonymsPutSynonymRequest,
 },
]
