/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SynonymsGetSynonymsSetsRequest } from './schemas/synonyms_get_synonyms_sets.ts'
import type { EsApiDefinition } from '../types.ts'

export const synonymsGetSynonymsSetsApis: EsApiDefinition[] = [
 {
   name: "get-synonyms-sets",
   namespace: "synonyms",
   description: "Get all synonym sets.",
   method: "GET",
   path: "/_synonyms",
   input: SynonymsGetSynonymsSetsRequest,
 },
]
