/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SynonymsDeleteSynonymRuleRequest } from '@elastic/es-schemas/synonyms_delete_synonym_rule.js'
import type { EsApiDefinition } from '../types.ts'

export const synonymsDeleteSynonymRuleApis: EsApiDefinition[] = [
 {
  name: "delete-synonym-rule",
  namespace: "synonyms",
  description: "Delete a synonym rule.",
  method: "DELETE",
  path: "/_synonyms/{set_id}/{rule_id}",
  input: SynonymsDeleteSynonymRuleRequest,
 },
]
