/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SynonymsGetSynonymRuleRequest } from '@elastic/es-schemas/synonyms_get_synonym_rule.js'
import type { EsApiDefinition } from '../types.ts'

export const synonymsGetSynonymRuleApis: EsApiDefinition[] = [
 {
  name: "get-synonym-rule",
  namespace: "synonyms",
  description: "Get a synonym rule.",
  method: "GET",
  path: "/_synonyms/{set_id}/{rule_id}",
  input: SynonymsGetSynonymRuleRequest,
 },
]
