/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SynonymsGetSynonymRequest } from './schemas/synonyms_get_synonym.ts'
import type { EsApiDefinition } from '../types.ts'

export const synonymsGetSynonymApis: EsApiDefinition[] = [
 {
   name: "get-synonym",
   namespace: "synonyms",
   description: "Get a synonym set.",
   method: "GET",
   path: "/_synonyms/{id}",
   input: SynonymsGetSynonymRequest,
 },
]
