/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SynonymsGetSynonymRuleRequest } from './schemas/synonyms_get_synonym_rule.ts'
import type { EsApiDefinition } from '../types.ts'

export const synonymsGetSynonymRuleApis: EsApiDefinition[] = [
 {
   name: "get-synonym-rule",
   namespace: "synonyms",
   description: "Get a synonym rule.",
   method: "GET",
   path: "/_synonyms/{set_id}/{rule_id}",
   input: SynonymsGetSynonymRuleRequest,
 },
]
