/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { SynonymsDeleteSynonymRuleRequest } from './schemas/synonyms_delete_synonym_rule.ts'
import type { EsApiDefinition } from '../types.ts'

export const synonymsDeleteSynonymRuleApis: EsApiDefinition[] = [
 {
   name: "delete-synonym-rule",
   namespace: "synonyms",
   description: "Delete a synonym rule.",
   method: "DELETE",
   path: "/_synonyms/{set_id}/{rule_id}",
   input: SynonymsDeleteSynonymRuleRequest,
 },
]
