/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { SynonymsDeleteSynonymRequest, SynonymsDeleteSynonymRuleRequest, SynonymsGetSynonymRequest, SynonymsGetSynonymRuleRequest, SynonymsGetSynonymsSetsRequest, SynonymsPutSynonymRequest, SynonymsPutSynonymRuleRequest } from './schemas/synonyms.ts'
import type { EsApiDefinition } from '../types.ts'

export const synonymsApis: EsApiDefinition[] = [
  {
    name: 'delete-synonym',
    namespace: 'synonyms',
    description: 'Delete a synonym set.',
    method: 'DELETE',
    path: '/_synonyms/{id}',
    input: SynonymsDeleteSynonymRequest
  },
  {
    name: 'delete-synonym-rule',
    namespace: 'synonyms',
    description: 'Delete a synonym rule.',
    method: 'DELETE',
    path: '/_synonyms/{set_id}/{rule_id}',
    input: SynonymsDeleteSynonymRuleRequest
  },
  {
    name: 'get-synonym',
    namespace: 'synonyms',
    description: 'Get a synonym set.',
    method: 'GET',
    path: '/_synonyms/{id}',
    input: SynonymsGetSynonymRequest
  },
  {
    name: 'get-synonym-rule',
    namespace: 'synonyms',
    description: 'Get a synonym rule.',
    method: 'GET',
    path: '/_synonyms/{set_id}/{rule_id}',
    input: SynonymsGetSynonymRuleRequest
  },
  {
    name: 'get-synonyms-sets',
    namespace: 'synonyms',
    description: 'Get all synonym sets.',
    method: 'GET',
    path: '/_synonyms',
    input: SynonymsGetSynonymsSetsRequest
  },
  {
    name: 'put-synonym',
    namespace: 'synonyms',
    description: 'Create or update a synonym set.',
    method: 'PUT',
    path: '/_synonyms/{id}',
    input: SynonymsPutSynonymRequest
  },
  {
    name: 'put-synonym-rule',
    namespace: 'synonyms',
    description: 'Create or update a synonym rule.',
    method: 'PUT',
    path: '/_synonyms/{set_id}/{rule_id}',
    input: SynonymsPutSynonymRuleRequest
  }
]
