/**
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { TasksGetRequest } from './schemas/tasks.ts'
import type { EsApiDefinition } from '../types.ts'

export const tasksApis: EsApiDefinition[] = [
  {
    name: 'get',
    namespace: 'tasks',
    description: 'Get task information.',
    method: 'GET',
    path: '/_tasks/{task_id}',
    input: TasksGetRequest
  }
]
