/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { TasksCancelRequest } from '@elastic/es-schemas/tasks_cancel.js'
import type { EsApiDefinition } from '../types.ts'

export const tasksCancelApis: EsApiDefinition[] = [
 {
  name: "cancel",
  namespace: "tasks",
  description: "Cancel a task.",
  method: "POST",
  path: "/_tasks/{task_id}/_cancel",
  input: TasksCancelRequest,
 },
]
