/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { TasksListRequest } from '@elastic/es-schemas/tasks_list.js'
import type { EsApiDefinition } from '../types.ts'

export const tasksListApis: EsApiDefinition[] = [
 {
  name: "list",
  namespace: "tasks",
  description: "Get all tasks.",
  method: "GET",
  path: "/_tasks",
  input: TasksListRequest,
 },
]
