/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { TermvectorsRequest } from '@elastic/es-schemas/_global.js'
import type { EsApiDefinition } from '../types.ts'

export const termvectorsApis: EsApiDefinition[] = [
  {
    name: 'termvectors',
    description: 'Get term vector information.',
    method: 'GET',
    path: '/{index}/_termvectors/{id}',
    input: TermvectorsRequest
  }
]
