/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { TermvectorsRequest } from './schemas/termvectors.ts'
import type { EsApiDefinition } from '../types.ts'

export const termvectorsApis: EsApiDefinition[] = [
 {
   name: "termvectors",
   description: "Get term vector information.",
   method: "GET",
   path: "/{index}/_termvectors/{id}",
   input: TermvectorsRequest,
 },
]
