/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { TermsEnumRequest } from './schemas/terms_enum.ts'
import type { EsApiDefinition } from '../types.ts'

export const termsEnumApis: EsApiDefinition[] = [
 {
   name: "terms-enum",
   description: "Get terms in an index.",
   method: "GET",
   path: "/{index}/_terms_enum",
   input: TermsEnumRequest,
 },
]
