/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { z } from 'zod'
import { TextStructureFindStructureRequest } from '@elastic/es-schemas/text_structure_find_structure.js'
import type { EsApiDefinition } from '../types.ts'

const TextStructureFindStructureRequestPassthrough = TextStructureFindStructureRequest.extend({
  text_files: z.array(z.any()).optional().meta({ found_in: 'body' })
})

export const textStructureFindStructureApis: EsApiDefinition[] = [
 {
  name: "find-structure",
  namespace: "text-structure",
  description: "Find the structure of a text file.",
  method: "POST",
  path: "/_text_structure/find_structure",
  input: TextStructureFindStructureRequestPassthrough,
  bodyFormat: 'ndjson',
 },
]
