/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { TextStructureTestGrokPatternRequest } from '@elastic/es-schemas/text_structure_test_grok_pattern.js'
import type { EsApiDefinition } from '../types.ts'

export const textStructureTestGrokPatternApis: EsApiDefinition[] = [
 {
  name: "test-grok-pattern",
  namespace: "text-structure",
  description: "Test a Grok pattern.",
  method: "GET",
  path: "/_text_structure/test_grok_pattern",
  input: TextStructureTestGrokPatternRequest,
 },
]
