/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { TextStructureFindMessageStructureRequest } from '@elastic/es-schemas/text_structure_find_message_structure.js'
import type { EsApiDefinition } from '../types.ts'

export const textStructureFindMessageStructureApis: EsApiDefinition[] = [
 {
  name: "find-message-structure",
  namespace: "text-structure",
  description: "Find the structure of text messages.",
  method: "GET",
  path: "/_text_structure/find_message_structure",
  input: TextStructureFindMessageStructureRequest,
 },
]
