/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { TextStructureFindFieldStructureRequest } from '@elastic/es-schemas/text_structure_find_field_structure.js'
import type { EsApiDefinition } from '../types.ts'

export const textStructureFindFieldStructureApis: EsApiDefinition[] = [
 {
  name: "find-field-structure",
  namespace: "text-structure",
  description: "Find the structure of a text field.",
  method: "GET",
  path: "/_text_structure/find_field_structure",
  input: TextStructureFindFieldStructureRequest,
 },
]
