/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { TransformDeleteTransformRequest } from './schemas/transform_delete_transform.ts'
import type { EsApiDefinition } from '../types.ts'

export const transformDeleteTransformApis: EsApiDefinition[] = [
 {
   name: "delete-transform",
   namespace: "transform",
   description: "Delete a transform.",
   method: "DELETE",
   path: "/_transform/{transform_id}",
   input: TransformDeleteTransformRequest,
 },
]
