/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { TransformUpgradeTransformsRequest } from '@elastic/es-schemas/transform_upgrade_transforms.js'
import type { EsApiDefinition } from '../types.ts'

export const transformUpgradeTransformsApis: EsApiDefinition[] = [
 {
  name: "upgrade-transforms",
  namespace: "transform",
  description: "Upgrade all transforms.",
  method: "POST",
  path: "/_transform/_upgrade",
  input: TransformUpgradeTransformsRequest,
 },
]
