/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { TransformDeleteTransformRequest, TransformGetNodeStatsRequest, TransformGetTransformRequest, TransformGetTransformStatsRequest, TransformPreviewTransformRequest, TransformPutTransformRequest, TransformResetTransformRequest, TransformScheduleNowTransformRequest, TransformStartTransformRequest, TransformStopTransformRequest, TransformUpdateTransformRequest } from '@elastic/es-schemas/transform.js'
import type { EsApiDefinition } from '../types.ts'

export const transformApis: EsApiDefinition[] = [
  {
    name: 'delete-transform',
    namespace: 'transform',
    description: 'Delete a transform.',
    method: 'DELETE',
    path: '/_transform/{transform_id}',
    input: TransformDeleteTransformRequest
  },
  {
    name: 'get-node-stats',
    namespace: 'transform',
    description: 'Get node stats.',
    method: 'GET',
    path: '/_transform/_node_stats',
    input: TransformGetNodeStatsRequest
  },
  {
    name: 'get-transform',
    namespace: 'transform',
    description: 'Get transforms.',
    method: 'GET',
    path: '/_transform/{transform_id}',
    input: TransformGetTransformRequest
  },
  {
    name: 'get-transform-stats',
    namespace: 'transform',
    description: 'Get transform stats.',
    method: 'GET',
    path: '/_transform/{transform_id}/_stats',
    input: TransformGetTransformStatsRequest
  },
  {
    name: 'preview-transform',
    namespace: 'transform',
    description: 'Preview a transform.',
    method: 'GET',
    path: '/_transform/{transform_id}/_preview',
    input: TransformPreviewTransformRequest
  },
  {
    name: 'put-transform',
    namespace: 'transform',
    description: 'Create a transform.',
    method: 'PUT',
    path: '/_transform/{transform_id}',
    input: TransformPutTransformRequest
  },
  {
    name: 'reset-transform',
    namespace: 'transform',
    description: 'Reset a transform.',
    method: 'POST',
    path: '/_transform/{transform_id}/_reset',
    input: TransformResetTransformRequest
  },
  {
    name: 'schedule-now-transform',
    namespace: 'transform',
    description: 'Schedule a transform to start now.',
    method: 'POST',
    path: '/_transform/{transform_id}/_schedule_now',
    input: TransformScheduleNowTransformRequest
  },
  {
    name: 'start-transform',
    namespace: 'transform',
    description: 'Start a transform.',
    method: 'POST',
    path: '/_transform/{transform_id}/_start',
    input: TransformStartTransformRequest
  },
  {
    name: 'stop-transform',
    namespace: 'transform',
    description: 'Stop transforms.',
    method: 'POST',
    path: '/_transform/{transform_id}/_stop',
    input: TransformStopTransformRequest
  },
  {
    name: 'update-transform',
    namespace: 'transform',
    description: 'Update a transform.',
    method: 'POST',
    path: '/_transform/{transform_id}/_update',
    input: TransformUpdateTransformRequest
  }
]
