/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { TransformStopTransformRequest } from './schemas/transform_stop_transform.ts'
import type { EsApiDefinition } from '../types.ts'

export const transformStopTransformApis: EsApiDefinition[] = [
 {
   name: "stop-transform",
   namespace: "transform",
   description: "Stop transforms.",
   method: "POST",
   path: "/_transform/{transform_id}/_stop",
   input: TransformStopTransformRequest,
 },
]
