/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { TransformGetTransformStatsRequest } from '@elastic/es-schemas/transform_get_transform_stats.js'
import type { EsApiDefinition } from '../types.ts'

export const transformGetTransformStatsApis: EsApiDefinition[] = [
 {
  name: "get-transform-stats",
  namespace: "transform",
  description: "Get transform stats.",
  method: "GET",
  path: "/_transform/{transform_id}/_stats",
  input: TransformGetTransformStatsRequest,
 },
]
