/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { TransformGetTransformRequest } from './schemas/transform_get_transform.ts'
import type { EsApiDefinition } from '../types.ts'

export const transformGetTransformApis: EsApiDefinition[] = [
 {
   name: "get-transform",
   namespace: "transform",
   description: "Get transforms.",
   method: "GET",
   path: "/_transform/{transform_id}",
   input: TransformGetTransformRequest,
 },
]
