/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { TransformUpdateTransformRequest } from './schemas/transform_update_transform.ts'
import type { EsApiDefinition } from '../types.ts'

export const transformUpdateTransformApis: EsApiDefinition[] = [
 {
   name: "update-transform",
   namespace: "transform",
   description: "Update a transform.",
   method: "POST",
   path: "/_transform/{transform_id}/_update",
   input: TransformUpdateTransformRequest,
 },
]
