/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { TransformScheduleNowTransformRequest } from './schemas/transform_schedule_now_transform.ts'
import type { EsApiDefinition } from '../types.ts'

export const transformScheduleNowTransformApis: EsApiDefinition[] = [
 {
   name: "schedule-now-transform",
   namespace: "transform",
   description: "Schedule a transform to start now.",
   method: "POST",
   path: "/_transform/{transform_id}/_schedule_now",
   input: TransformScheduleNowTransformRequest,
 },
]
