/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { TransformResetTransformRequest } from './schemas/transform_reset_transform.ts'
import type { EsApiDefinition } from '../types.ts'

export const transformResetTransformApis: EsApiDefinition[] = [
 {
   name: "reset-transform",
   namespace: "transform",
   description: "Reset a transform.",
   method: "POST",
   path: "/_transform/{transform_id}/_reset",
   input: TransformResetTransformRequest,
 },
]
