/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { TransformPutTransformRequest } from './schemas/transform_put_transform.ts'
import type { EsApiDefinition } from '../types.ts'

export const transformPutTransformApis: EsApiDefinition[] = [
 {
   name: "put-transform",
   namespace: "transform",
   description: "Create a transform.",
   method: "PUT",
   path: "/_transform/{transform_id}",
   input: TransformPutTransformRequest,
 },
]
