/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { TransformStopTransformRequest } from '@elastic/es-schemas/transform_stop_transform.js'
import type { EsApiDefinition } from '../types.ts'

export const transformStopTransformApis: EsApiDefinition[] = [
 {
  name: "stop-transform",
  namespace: "transform",
  description: "Stop transforms.",
  method: "POST",
  path: "/_transform/{transform_id}/_stop",
  input: TransformStopTransformRequest,
 },
]
