/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { TransformGetNodeStatsRequest } from './schemas/transform_get_node_stats.ts'
import type { EsApiDefinition } from '../types.ts'

export const transformGetNodeStatsApis: EsApiDefinition[] = [
 {
   name: "get-node-stats",
   namespace: "transform",
   description: "Get node stats.",
   method: "GET",
   path: "/_transform/_node_stats",
   input: TransformGetNodeStatsRequest,
 },
]
