/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { TransformStartTransformRequest } from '@elastic/es-schemas/transform_start_transform.js'
import type { EsApiDefinition } from '../types.ts'

export const transformStartTransformApis: EsApiDefinition[] = [
 {
  name: "start-transform",
  namespace: "transform",
  description: "Start a transform.",
  method: "POST",
  path: "/_transform/{transform_id}/_start",
  input: TransformStartTransformRequest,
 },
]
