/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { TransformGetNodeStatsRequest } from '@elastic/es-schemas/transform_get_node_stats.js'
import type { EsApiDefinition } from '../types.ts'

export const transformGetNodeStatsApis: EsApiDefinition[] = [
 {
  name: "get-node-stats",
  namespace: "transform",
  description: "Get node stats.",
  method: "GET",
  path: "/_transform/_node_stats",
  input: TransformGetNodeStatsRequest,
 },
]
