/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { TransformPreviewTransformRequest } from './schemas/transform_preview_transform.ts'
import type { EsApiDefinition } from '../types.ts'

export const transformPreviewTransformApis: EsApiDefinition[] = [
 {
   name: "preview-transform",
   namespace: "transform",
   description: "Preview a transform.",
   method: "GET",
   path: "/_transform/{transform_id}/_preview",
   input: TransformPreviewTransformRequest,
 },
]
