/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { UpdateByQueryRethrottleRequest } from '@elastic/es-schemas/update_by_query_rethrottle.js'
import type { EsApiDefinition } from '../types.ts'

export const updateByQueryRethrottleApis: EsApiDefinition[] = [
 {
  name: "update-by-query-rethrottle",
  description: "Throttle an update by query operation.",
  method: "POST",
  path: "/_update_by_query/{task_id}/_rethrottle",
  input: UpdateByQueryRethrottleRequest,
 },
]
