/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { UpdateRequest } from './schemas/update.ts'
import type { EsApiDefinition } from '../types.ts'

export const updateApis: EsApiDefinition[] = [
 {
   name: "update",
   description: "Update a document.",
   method: "POST",
   path: "/{index}/_update/{id}",
   input: UpdateRequest,
 },
]
