/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js
 * and then split per-endpoint by scripts/split-api-files.mjs.
 * DO NOT MODIFY IT BY HAND.
 */

import { UpdateByQueryRequest } from './schemas/update_by_query.ts'
import type { EsApiDefinition } from '../types.ts'

export const updateByQueryApis: EsApiDefinition[] = [
 {
   name: "update-by-query",
   description: "Update documents.",
   method: "POST",
   path: "/{index}/_update_by_query",
   input: UpdateByQueryRequest,
 },
]
