/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { WatcherDeactivateWatchRequest } from '@elastic/es-schemas/watcher_deactivate_watch.js'
import type { EsApiDefinition } from '../types.ts'

export const watcherDeactivateWatchApis: EsApiDefinition[] = [
 {
  name: "deactivate-watch",
  namespace: "watcher",
  description: "Deactivate a watch.",
  method: "PUT",
  path: "/_watcher/watch/{watch_id}/_deactivate",
  input: WatcherDeactivateWatchRequest,
 },
]
