/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { WatcherStopRequest } from '@elastic/es-schemas/watcher_stop.js'
import type { EsApiDefinition } from '../types.ts'

export const watcherStopApis: EsApiDefinition[] = [
 {
  name: "stop",
  namespace: "watcher",
  description: "Stop the watch service.",
  method: "POST",
  path: "/_watcher/_stop",
  input: WatcherStopRequest,
 },
]
