/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { CloudApiDefinition } from '../types.ts'

export const accountsApis: CloudApiDefinition[] = [
  {
    name: "get-current-account",
    namespace: "accounts",
    description: "Fetch current account information",
    method: "GET",
    path: "/api/v1/account",
  },
  {
    name: "update-current-account",
    namespace: "accounts",
    description: "Updates the current account",
    method: "PUT",
    path: "/api/v1/account",
  },
  {
    name: "patch-current-account",
    namespace: "accounts",
    description: "Updates the current account",
    method: "PATCH",
    path: "/api/v1/account",
  },
]
