/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { CloudApiDefinition } from '../types.ts'

export const authenticationApis: CloudApiDefinition[] = [
  {
    name: "get-api-keys",
    namespace: "authentication",
    description: "Get all API keys",
    method: "GET",
    path: "/api/v1/users/auth/keys",
    queryParams: [
    { name: "next_page", type: "string", description: "Pagination cursor to get the next page of records" },
    ],
  },
  {
    name: "create-api-key",
    namespace: "authentication",
    description: "Create API key",
    method: "POST",
    path: "/api/v1/users/auth/keys",
  },
  {
    name: "delete-api-keys",
    namespace: "authentication",
    description: "Delete API keys",
    method: "DELETE",
    path: "/api/v1/users/auth/keys",
  },
  {
    name: "get-api-key",
    namespace: "authentication",
    description: "Get API key",
    method: "GET",
    path: "/api/v1/users/auth/keys/{api_key_id}",
    pathParams: [
    { name: "api_key_id", description: "The API Key ID.", required: true },
    ],
  },
  {
    name: "delete-api-key",
    namespace: "authentication",
    description: "Delete API key",
    method: "DELETE",
    path: "/api/v1/users/auth/keys/{api_key_id}",
    pathParams: [
    { name: "api_key_id", description: "The API Key ID.", required: true },
    ],
  },
]
