/**
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { CloudApiDefinition } from '../types.ts'

export const billingCostsAnalysisApis: CloudApiDefinition[] = [
  {
    name: "get-costs-overview",
    namespace: "billing-costs-analysis",
    description: "Get costs overview for the organization. Currently unavailable in self-hosted ECE.",
    method: "GET",
    path: "/api/v1/billing/costs/{organization_id}",
    pathParams: [
    { name: "organization_id", description: "Identifier for the organization", required: true },
    ],
    queryParams: [
    { name: "from", type: "string", description: "A datetime for the beginning of the desired range for which to fetch costs. Defaults to start of current month." },
    { name: "to", type: "string", description: "A datetime for the end of the desired range for which to fetch costs. Defaults to the current date." },
    ],
  },
  {
    name: "get-costs-charts",
    namespace: "billing-costs-analysis",
    description: "Get charts for the organization. Currently unavailable in self-hosted ECE.",
    method: "GET",
    path: "/api/v1/billing/costs/{organization_id}/charts",
    pathParams: [
    { name: "organization_id", description: "Identifier for the organization", required: true },
    ],
    queryParams: [
    { name: "from", type: "string", description: "A datetime for the beginning of the desired range for which to fetch costs. Defaults to start of current month." },
    { name: "to", type: "string", description: "A datetime for the end of the desired range for which to fetch costs. Defaults to the current date." },
    { name: "bucketing_strategy", type: "string", description: "The desired bucketing strategy for the charts. Defaults to `daily`." },
    ],
  },
  {
    name: "get-costs-deployments",
    namespace: "billing-costs-analysis",
    description: "Get deployments costs for the organization. Currently unavailable in self-hosted ECE.",
    method: "GET",
    path: "/api/v1/billing/costs/{organization_id}/deployments",
    pathParams: [
    { name: "organization_id", description: "Identifier for the organization", required: true },
    ],
    queryParams: [
    { name: "from", type: "string", description: "A datetime for the beginning of the desired range for which to fetch activity. Defaults to start of current month." },
    { name: "to", type: "string", description: "A datetime for the end of the desired range for which to fetch activity. Defaults to the current date." },
    ],
  },
  {
    name: "get-costs-charts-by-deployment",
    namespace: "billing-costs-analysis",
    description: "Get charts by deployment. Currently unavailable in self-hosted ECE.",
    method: "GET",
    path: "/api/v1/billing/costs/{organization_id}/deployments/{deployment_id}/charts",
    pathParams: [
    { name: "organization_id", description: "Identifier for the organization", required: true },
    { name: "deployment_id", description: "Id of a Deployment", required: true },
    ],
    queryParams: [
    { name: "from", type: "string", description: "A datetime for the beginning of the desired range for which to fetch costs. Defaults to start of current month." },
    { name: "to", type: "string", description: "A datetime for the end of the desired range for which to fetch costs. Defaults to the current date." },
    { name: "bucketing_strategy", type: "string", description: "The desired bucketing strategy for the charts. Defaults to `daily`." },
    ],
  },
  {
    name: "get-costs-items-by-deployment",
    namespace: "billing-costs-analysis",
    description: "Get itemized costs by deployments. Currently unavailable in self-hosted ECE.",
    method: "GET",
    path: "/api/v1/billing/costs/{organization_id}/deployments/{deployment_id}/items",
    pathParams: [
    { name: "organization_id", description: "Identifier for the organization", required: true },
    { name: "deployment_id", description: "Id of a Deployment", required: true },
    ],
    queryParams: [
    { name: "from", type: "string", description: "A datetime for the beginning of the desired range for which to fetch costs. Defaults to start of current month." },
    { name: "to", type: "string", description: "A datetime for the end of the desired range for which to fetch costs. Defaults to the current date." },
    ],
  },
  {
    name: "get-costs-items",
    namespace: "billing-costs-analysis",
    description: "Get itemized costs for the organization. Currently unavailable in self-hosted ECE.",
    method: "GET",
    path: "/api/v1/billing/costs/{organization_id}/items",
    pathParams: [
    { name: "organization_id", description: "Identifier for the organization", required: true },
    ],
    queryParams: [
    { name: "from", type: "string", description: "A datetime for the beginning of the desired range for which to fetch costs. Defaults to start of current month." },
    { name: "to", type: "string", description: "A datetime for the end of the desired range for which to fetch costs. Defaults to the current date." },
    ],
  },
]
