/**
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { CloudApiDefinition } from '../types.ts'

export const deploymentTemplatesApis: CloudApiDefinition[] = [
  {
    name: "get-deployment-templates-v2",
    namespace: "deployment-templates",
    description: "Get deployment templates",
    method: "GET",
    path: "/api/v1/deployments/templates",
    queryParams: [
    { name: "metadata", type: "string", description: "An optional key/value pair in the form of (key:value) that will act as a filter and exclude any templates that do not have a matching metadata item associated." },
    { name: "show_instance_configurations", type: "boolean", description: "If true, will return details for each instance configuration referenced by the template." },
    { name: "show_max_zones", type: "boolean", description: "If true, will populate the max_zones field in the instance configurations. Only relevant if show_instance_configurations=true." },
    { name: "stack_version", type: "string", description: "If present, it will cause the returned deployment templates to be adapted to return only the elements allowed in that version." },
    { name: "hide_deprecated", type: "boolean", description: "If true, templates flagged as deprecated will NOT be returned." },
    { name: "region", type: "string", description: "Region of the deployment templates", required: true },
    ],
  },
  {
    name: "get-deployment-template-v2",
    namespace: "deployment-templates",
    description: "Get deployment template",
    method: "GET",
    path: "/api/v1/deployments/templates/{template_id}",
    pathParams: [
    { name: "template_id", description: "The identifier for the deployment template.", required: true },
    ],
    queryParams: [
    { name: "show_instance_configurations", type: "boolean", description: "If true, will return details for each instance configuration referenced by the template." },
    { name: "show_max_zones", type: "boolean", description: "If true, will populate the max_zones field in the instance configurations. Only relevant if show_instance_configurations=true." },
    { name: "stack_version", type: "string", description: "If present, it will cause the returned deployment template to be adapted to return only the elements allowed in that version." },
    { name: "region", type: "string", description: "Region of the deployment template", required: true },
    ],
  },
]
