/**
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { CloudApiDefinition } from '../types.ts'

export const deploymentsTrafficFilterApis: CloudApiDefinition[] = [
  {
    name: "get-traffic-filter-deployment-ruleset-associations",
    namespace: "deployments-traffic-filter",
    description: "Get associated rulesets",
    method: "GET",
    path: "/api/v1/deployments/traffic-filter/associations/{association_type}/{associated_entity_id}/rulesets",
    pathParams: [
    { name: "association_type", description: "Association type", required: true },
    { name: "associated_entity_id", description: "Associated entity ID", required: true },
    ],
  },
  {
    name: "get-traffic-filter-claimed-link-ids",
    namespace: "deployments-traffic-filter",
    description: "List traffic filter claimed link id",
    method: "GET",
    path: "/api/v1/deployments/traffic-filter/link-ids",
    queryParams: [
    { name: "region", type: "string", description: "If provided limits the claimed id to that region only." },
    { name: "organization_id", type: "string", description: "Retrieves a list of resources that are associated to the specified organization ID. It only takes effect if the user is an admin." },
    ],
  },
  {
    name: "claim-traffic-filter-link-id",
    namespace: "deployments-traffic-filter",
    description: "Claim a link id",
    method: "POST",
    path: "/api/v1/deployments/traffic-filter/link-ids/_claim",
  },
  {
    name: "unclaim-traffic-filter-link-id",
    namespace: "deployments-traffic-filter",
    description: "Unclaims a link id",
    method: "POST",
    path: "/api/v1/deployments/traffic-filter/link-ids/_unclaim",
  },
  {
    name: "get-traffic-filter-rulesets",
    namespace: "deployments-traffic-filter",
    description: "List traffic filter rulesets",
    method: "GET",
    path: "/api/v1/deployments/traffic-filter/rulesets",
    queryParams: [
    { name: "include_associations", type: "boolean", description: "Retrieves a list of resources that are associated to the specified ruleset." },
    { name: "region", type: "string", description: "If provided limits the rulesets to that region only." },
    { name: "organization_id", type: "string", description: "Retrieves a list of resources that are associated to the specified organization ID. It only takes effect if the user is an admin." },
    ],
  },
  {
    name: "create-traffic-filter-ruleset",
    namespace: "deployments-traffic-filter",
    description: "Create a ruleset",
    method: "POST",
    path: "/api/v1/deployments/traffic-filter/rulesets",
  },
  {
    name: "get-traffic-filter-ruleset",
    namespace: "deployments-traffic-filter",
    description: "Retrieves the ruleset by ID.",
    method: "GET",
    path: "/api/v1/deployments/traffic-filter/rulesets/{ruleset_id}",
    pathParams: [
    { name: "ruleset_id", description: "The mandatory ruleset ID.", required: true },
    ],
    queryParams: [
    { name: "include_associations", type: "boolean", description: "Retrieves a list of resources that are associated to the specified ruleset." },
    ],
  },
  {
    name: "update-traffic-filter-ruleset",
    namespace: "deployments-traffic-filter",
    description: "Updates a ruleset",
    method: "PUT",
    path: "/api/v1/deployments/traffic-filter/rulesets/{ruleset_id}",
    pathParams: [
    { name: "ruleset_id", description: "The mandatory ruleset ID.", required: true },
    ],
  },
  {
    name: "delete-traffic-filter-ruleset",
    namespace: "deployments-traffic-filter",
    description: "Delete a ruleset",
    method: "DELETE",
    path: "/api/v1/deployments/traffic-filter/rulesets/{ruleset_id}",
    pathParams: [
    { name: "ruleset_id", description: "The mandatory ruleset ID.", required: true },
    ],
    queryParams: [
    { name: "ignore_associations", type: "boolean", description: "When true, ignores the associations and deletes the ruleset. When false, recognizes the associations, which prevents the deletion of the rule set." },
    ],
  },
  {
    name: "get-traffic-filter-ruleset-deployment-associations",
    namespace: "deployments-traffic-filter",
    description: "Get associated deployments",
    method: "GET",
    path: "/api/v1/deployments/traffic-filter/rulesets/{ruleset_id}/associations",
    pathParams: [
    { name: "ruleset_id", description: "The mandatory ruleset ID.", required: true },
    ],
  },
  {
    name: "create-traffic-filter-ruleset-association",
    namespace: "deployments-traffic-filter",
    description: "Create ruleset association",
    method: "POST",
    path: "/api/v1/deployments/traffic-filter/rulesets/{ruleset_id}/associations",
    pathParams: [
    { name: "ruleset_id", description: "The mandatory ruleset ID.", required: true },
    ],
  },
  {
    name: "delete-traffic-filter-ruleset-association",
    namespace: "deployments-traffic-filter",
    description: "Delete ruleset association",
    method: "DELETE",
    path: "/api/v1/deployments/traffic-filter/rulesets/{ruleset_id}/associations/{association_type}/{associated_entity_id}",
    pathParams: [
    { name: "ruleset_id", description: "The mandatory ruleset ID.", required: true },
    { name: "association_type", description: "Association type", required: true },
    { name: "associated_entity_id", description: "Associated entity ID", required: true },
    ],
  },
]
