/**
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { CloudApiDefinition } from '../types.ts'

export const elasticsearchProjectsApis: CloudApiDefinition[] = [
  {
    name: "list-elasticsearch-projects",
    namespace: "elasticsearch-projects",
    description: "Get Elasticsearch projects",
    method: "GET",
    path: "/api/v1/serverless/projects/elasticsearch",
    queryParams: [
    { name: "traffic_filter", type: "string", description: "Filters the returned list of projects. Only projects associated with the provided traffic_filter will be returned." },
    { name: "linked", type: "string", description: "Contains a project ID. If specified, the result will be filtered to only those origin projects that are linked to the specified project ID in a cross-project search configuration." },
    ],
  },
  {
    name: "create-elasticsearch-project",
    namespace: "elasticsearch-projects",
    description: "Create an Elasticsearch project",
    method: "POST",
    path: "/api/v1/serverless/projects/elasticsearch",
  },
  {
    name: "get-elasticsearch-project",
    namespace: "elasticsearch-projects",
    description: "Get an Elasticsearch project",
    method: "GET",
    path: "/api/v1/serverless/projects/elasticsearch/{id}",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
  },
  {
    name: "delete-elasticsearch-project",
    namespace: "elasticsearch-projects",
    description: "Delete an Elasticsearch project",
    method: "DELETE",
    path: "/api/v1/serverless/projects/elasticsearch/{id}",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
  },
  {
    name: "patch-elasticsearch-project",
    namespace: "elasticsearch-projects",
    description: "Update an Elasticsearch project",
    method: "PATCH",
    path: "/api/v1/serverless/projects/elasticsearch/{id}",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
  },
  {
    name: "reset-elasticsearch-project-credentials",
    namespace: "elasticsearch-projects",
    description: "Reset the project credentials",
    method: "POST",
    path: "/api/v1/serverless/projects/elasticsearch/{id}/_reset-credentials",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
  },
  {
    name: "resume-elasticsearch-project",
    namespace: "elasticsearch-projects",
    description: "Resume Elasticsearch project",
    method: "POST",
    path: "/api/v1/serverless/projects/elasticsearch/{id}/_resume",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
  },
  {
    name: "get-elasticsearch-project-roles",
    namespace: "elasticsearch-projects",
    description: "Get roles for an Elasticsearch project",
    method: "GET",
    path: "/api/v1/serverless/projects/elasticsearch/{id}/roles",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
  },
  {
    name: "get-elasticsearch-project-status",
    namespace: "elasticsearch-projects",
    description: "Get the status of an Elasticsearch project",
    method: "GET",
    path: "/api/v1/serverless/projects/elasticsearch/{id}/status",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
  },
]
