/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { CloudApiDefinition } from '../types.ts'

export const extensionsApis: CloudApiDefinition[] = [
  {
    name: "list-extensions",
    namespace: "extensions",
    description: "List Extensions",
    method: "GET",
    path: "/api/v1/deployments/extensions",
  },
  {
    name: "create-extension",
    namespace: "extensions",
    description: "Create an extension",
    method: "POST",
    path: "/api/v1/deployments/extensions",
  },
  {
    name: "get-extension",
    namespace: "extensions",
    description: "Get Extension",
    method: "GET",
    path: "/api/v1/deployments/extensions/{extension_id}",
    pathParams: [
    { name: "extension_id", description: "Id of an extension", required: true },
    ],
    queryParams: [
    { name: "include_deployments", type: "boolean", description: "Include deployments referencing this extension. Up to only 10000 deployments will be included." },
    ],
  },
  {
    name: "update-extension",
    namespace: "extensions",
    description: "Update Extension",
    method: "POST",
    path: "/api/v1/deployments/extensions/{extension_id}",
    pathParams: [
    { name: "extension_id", description: "Id of an extension", required: true },
    ],
  },
  {
    name: "upload-extension",
    namespace: "extensions",
    description: "Uploads the Extension",
    method: "PUT",
    path: "/api/v1/deployments/extensions/{extension_id}",
    pathParams: [
    { name: "extension_id", description: "Id of an extension", required: true },
    ],
  },
  {
    name: "delete-extension",
    namespace: "extensions",
    description: "Delete Extension",
    method: "DELETE",
    path: "/api/v1/deployments/extensions/{extension_id}",
    pathParams: [
    { name: "extension_id", description: "Id of an extension", required: true },
    ],
  },
]
