/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { CloudApiDefinition } from '../types.ts'

export const linkedProjectsApis: CloudApiDefinition[] = [
  {
    name: "get-elasticsearch-project-can-delete",
    namespace: "linked-projects",
    description: "Get Elasticsearch project delete status",
    method: "GET",
    path: "/api/v1/serverless/projects/elasticsearch/{id}/_can-delete",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
  },
  {
    name: "get-observability-project-can-delete",
    namespace: "linked-projects",
    description: "Get Observability project delete status",
    method: "GET",
    path: "/api/v1/serverless/projects/observability/{id}/_can-delete",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
  },
  {
    name: "get-security-project-can-delete",
    namespace: "linked-projects",
    description: "Get Security project delete status",
    method: "GET",
    path: "/api/v1/serverless/projects/security/{id}/_can-delete",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
  },
]
