/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { CloudApiDefinition } from '../types.ts'

export const linkedCandidateProjectsApis: CloudApiDefinition[] = [
  {
    name: "get-elasticsearch-project-link-candidates",
    namespace: "linked-candidate-projects",
    description: "Get Elasticsearch project link candidates",
    method: "GET",
    path: "/api/v1/serverless/projects/elasticsearch/{id}/link-candidates",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
    queryParams: [
    { name: "types", type: "string", description: "One or more types of projects to return as link candidates." },
    { name: "csp", type: "string", description: "The Cloud Service Provider to filter the link candidate projects by." },
    { name: "region", type: "string", description: "The region to filter the link candidate projects by." },
    { name: "name", type: "string", description: "The project name to filter the link candidates by." },
    { name: "alias", type: "string", description: "The project alias to filter the link candidates by." },
    ],
  },
  {
    name: "get-observability-project-link-candidates",
    namespace: "linked-candidate-projects",
    description: "Get Observability project link candidates",
    method: "GET",
    path: "/api/v1/serverless/projects/observability/{id}/link-candidates",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
    queryParams: [
    { name: "types", type: "string", description: "One or more types of projects to return as link candidates." },
    { name: "csp", type: "string", description: "The Cloud Service Provider to filter the link candidate projects by." },
    { name: "region", type: "string", description: "The region to filter the link candidate projects by." },
    { name: "name", type: "string", description: "The project name to filter the link candidates by." },
    { name: "alias", type: "string", description: "The project alias to filter the link candidates by." },
    ],
  },
  {
    name: "get-security-project-link-candidates",
    namespace: "linked-candidate-projects",
    description: "Get Security project link candidates",
    method: "GET",
    path: "/api/v1/serverless/projects/security/{id}/link-candidates",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
    queryParams: [
    { name: "types", type: "string", description: "One or more types of projects to return as link candidates." },
    { name: "csp", type: "string", description: "The Cloud Service Provider to filter the link candidate projects by." },
    { name: "region", type: "string", description: "The region to filter the link candidate projects by." },
    { name: "name", type: "string", description: "The project name to filter the link candidates by." },
    { name: "alias", type: "string", description: "The project alias to filter the link candidates by." },
    ],
  },
]
