/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { CloudApiDefinition } from '../types.ts'

export const observabilityProjectsApis: CloudApiDefinition[] = [
  {
    name: "list-observability-projects",
    namespace: "observability-projects",
    description: "Get Observability projects",
    method: "GET",
    path: "/api/v1/serverless/projects/observability",
    queryParams: [
    { name: "traffic_filter", type: "string", description: "traffic filters associated with this project" },
    { name: "linked", type: "string", description: "Contains a project ID. If specified, the result will be filtered to only those origin projects that are linked to the specified project ID in a cross-project search configuration." },
    ],
  },
  {
    name: "create-observability-project",
    namespace: "observability-projects",
    description: "Create an observability project",
    method: "POST",
    path: "/api/v1/serverless/projects/observability",
  },
  {
    name: "get-observability-project",
    namespace: "observability-projects",
    description: "Get an Observability project",
    method: "GET",
    path: "/api/v1/serverless/projects/observability/{id}",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
  },
  {
    name: "delete-observability-project",
    namespace: "observability-projects",
    description: "Delete an Observability project",
    method: "DELETE",
    path: "/api/v1/serverless/projects/observability/{id}",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
  },
  {
    name: "patch-observability-project",
    namespace: "observability-projects",
    description: "Update an Observability project",
    method: "PATCH",
    path: "/api/v1/serverless/projects/observability/{id}",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
  },
  {
    name: "reset-observability-project-credentials",
    namespace: "observability-projects",
    description: "Reset the project credentials",
    method: "POST",
    path: "/api/v1/serverless/projects/observability/{id}/_reset-credentials",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
  },
  {
    name: "resume-observability-project",
    namespace: "observability-projects",
    description: "Resume Observability project",
    method: "POST",
    path: "/api/v1/serverless/projects/observability/{id}/_resume",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
  },
  {
    name: "get-observability-project-roles",
    namespace: "observability-projects",
    description: "Get roles for an Observability project",
    method: "GET",
    path: "/api/v1/serverless/projects/observability/{id}/roles",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
  },
  {
    name: "get-observability-project-status",
    namespace: "observability-projects",
    description: "Get the status of an Observability project",
    method: "GET",
    path: "/api/v1/serverless/projects/observability/{id}/status",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
  },
]
