/**
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { CloudApiDefinition } from '../types.ts'

export const organizationsApis: CloudApiDefinition[] = [
  {
    name: "list-organizations",
    namespace: "organizations",
    description: "List organizations",
    method: "GET",
    path: "/api/v1/organizations",
  },
  {
    name: "get-organization-invitation",
    namespace: "organizations",
    description: "Get organization invitation",
    method: "GET",
    path: "/api/v1/organizations/invitations/{invitation_token}",
    pathParams: [
    { name: "invitation_token", description: "Organization invitation token", required: true },
    ],
  },
  {
    name: "accept-organization-invitation",
    namespace: "organizations",
    description: "Accept an organization invitation",
    method: "POST",
    path: "/api/v1/organizations/invitations/{invitation_token}/_accept",
    pathParams: [
    { name: "invitation_token", description: "Organization invitation token", required: true },
    ],
  },
  {
    name: "get-organization",
    namespace: "organizations",
    description: "Fetch organization information",
    method: "GET",
    path: "/api/v1/organizations/{organization_id}",
    pathParams: [
    { name: "organization_id", description: "Identifier for the Organization", required: true },
    ],
  },
  {
    name: "update-organization",
    namespace: "organizations",
    description: "Update organization",
    method: "PUT",
    path: "/api/v1/organizations/{organization_id}",
    pathParams: [
    { name: "organization_id", description: "Identifier for the Organization", required: true },
    ],
  },
  {
    name: "domain-claim-get-domain-claims",
    namespace: "organizations",
    description: "Get domain claims",
    method: "GET",
    path: "/api/v1/organizations/{organization_id}/domains",
    pathParams: [
    { name: "organization_id", description: "Identifier for the Organization", required: true },
    ],
  },
  {
    name: "domain-claim-delete",
    namespace: "organizations",
    description: "Delete domain claim",
    method: "DELETE",
    path: "/api/v1/organizations/{organization_id}/domains",
    pathParams: [
    { name: "organization_id", description: "Identifier for the Organization", required: true },
    ],
  },
  {
    name: "domain-claim-generate-verification-code",
    namespace: "organizations",
    description: "Generate verification code",
    method: "POST",
    path: "/api/v1/organizations/{organization_id}/domains/_generate_verification_code",
    pathParams: [
    { name: "organization_id", description: "Identifier for the Organization", required: true },
    ],
  },
  {
    name: "domain-claim-verify-domain",
    namespace: "organizations",
    description: "Verify domain claim",
    method: "POST",
    path: "/api/v1/organizations/{organization_id}/domains/_verify",
    pathParams: [
    { name: "organization_id", description: "Identifier for the Organization", required: true },
    ],
  },
  {
    name: "get-organization-idp",
    namespace: "organizations",
    description: "Get organization IdP",
    method: "GET",
    path: "/api/v1/organizations/{organization_id}/idp",
    pathParams: [
    { name: "organization_id", description: "Identifier for the Organization", required: true },
    ],
  },
  {
    name: "setup-organization-idp",
    namespace: "organizations",
    description: "Setup organization IdP",
    method: "PUT",
    path: "/api/v1/organizations/{organization_id}/idp",
    pathParams: [
    { name: "organization_id", description: "Identifier for the Organization", required: true },
    ],
  },
  {
    name: "teardown-organization-idp",
    namespace: "organizations",
    description: "Tear down organization IdP",
    method: "DELETE",
    path: "/api/v1/organizations/{organization_id}/idp",
    pathParams: [
    { name: "organization_id", description: "Identifier for the Organization", required: true },
    ],
  },
  {
    name: "get-organization-idp-metadata",
    namespace: "organizations",
    description: "Get organization service provider SAML2 metadata.xml for configuring the identity provider",
    method: "GET",
    path: "/api/v1/organizations/{organization_id}/idp/metadata.xml",
    pathParams: [
    { name: "organization_id", description: "Identifier for the Organization", required: true },
    ],
  },
  {
    name: "list-organization-invitations",
    namespace: "organizations",
    description: "List organization invitations",
    method: "GET",
    path: "/api/v1/organizations/{organization_id}/invitations",
    pathParams: [
    { name: "organization_id", description: "Identifier for the Organization", required: true },
    ],
  },
  {
    name: "create-organization-invitations",
    namespace: "organizations",
    description: "Create organization invitations",
    method: "POST",
    path: "/api/v1/organizations/{organization_id}/invitations",
    pathParams: [
    { name: "organization_id", description: "Identifier for the Organization", required: true },
    ],
  },
  {
    name: "delete-organization-invitations",
    namespace: "organizations",
    description: "Delete organization invitations",
    method: "DELETE",
    path: "/api/v1/organizations/{organization_id}/invitations/{invitation_tokens}",
    pathParams: [
    { name: "organization_id", description: "Identifier for the Organization", required: true },
    { name: "invitation_tokens", description: "CSV list of Invitation tokens", required: true },
    ],
  },
  {
    name: "list-organization-members",
    namespace: "organizations",
    description: "List organization members",
    method: "GET",
    path: "/api/v1/organizations/{organization_id}/members",
    pathParams: [
    { name: "organization_id", description: "Identifier for the Organization", required: true },
    ],
  },
  {
    name: "delete-organization-memberships",
    namespace: "organizations",
    description: "Delete organization memberships",
    method: "DELETE",
    path: "/api/v1/organizations/{organization_id}/members/{user_ids}",
    pathParams: [
    { name: "organization_id", description: "Identifier for the Organization", required: true },
    { name: "user_ids", description: "CSV list of User identifiers", required: true },
    ],
    queryParams: [
    { name: "force", type: "boolean", description: "Whether or not to force the removal of Org memberships (effective only for Platform Admins)" },
    ],
  },
  {
    name: "get-role-mappings",
    namespace: "organizations",
    description: "Get role mappings",
    method: "GET",
    path: "/api/v1/organizations/{organization_id}/role_mappings",
    pathParams: [
    { name: "organization_id", description: "Identifier for the Organization", required: true },
    ],
  },
  {
    name: "update-role-mappings",
    namespace: "organizations",
    description: "Updates role mappings",
    method: "PUT",
    path: "/api/v1/organizations/{organization_id}/role_mappings",
    pathParams: [
    { name: "organization_id", description: "Identifier for the Organization", required: true },
    ],
  },
  {
    name: "delete-role-mappings",
    namespace: "organizations",
    description: "Delete role mappings",
    method: "DELETE",
    path: "/api/v1/organizations/{organization_id}/role_mappings",
    pathParams: [
    { name: "organization_id", description: "Identifier for the Organization", required: true },
    ],
  },
]
