/**
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { CloudApiDefinition } from '../types.ts'

export const regionsApis: CloudApiDefinition[] = [
  {
    name: "list-regions",
    namespace: "regions",
    description: "Get regions",
    method: "GET",
    path: "/api/v1/serverless/regions",
  },
  {
    name: "get-region",
    namespace: "regions",
    description: "Get a region",
    method: "GET",
    path: "/api/v1/serverless/regions/{id}",
    pathParams: [
    { name: "id", description: "ID of the region", required: true },
    ],
  },
]
