/**
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { CloudApiDefinition } from '../types.ts'

export const securityProjectsApis: CloudApiDefinition[] = [
  {
    name: "list-security-projects",
    namespace: "security-projects",
    description: "Get Security projects",
    method: "GET",
    path: "/api/v1/serverless/projects/security",
    queryParams: [
    { name: "traffic_filter", type: "string", description: "traffic filters associated with this project" },
    { name: "linked", type: "string", description: "Contains a project ID. If specified, the result will be filtered to only those origin projects that are linked to the specified project ID in a cross-project search configuration." },
    ],
  },
  {
    name: "create-security-project",
    namespace: "security-projects",
    description: "Create a security project",
    method: "POST",
    path: "/api/v1/serverless/projects/security",
  },
  {
    name: "get-security-project",
    namespace: "security-projects",
    description: "Get a Security project",
    method: "GET",
    path: "/api/v1/serverless/projects/security/{id}",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
  },
  {
    name: "delete-security-project",
    namespace: "security-projects",
    description: "Delete a Security project",
    method: "DELETE",
    path: "/api/v1/serverless/projects/security/{id}",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
  },
  {
    name: "patch-security-project",
    namespace: "security-projects",
    description: "Update a Security project",
    method: "PATCH",
    path: "/api/v1/serverless/projects/security/{id}",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
  },
  {
    name: "reset-security-project-credentials",
    namespace: "security-projects",
    description: "Reset the project credentials",
    method: "POST",
    path: "/api/v1/serverless/projects/security/{id}/_reset-credentials",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
  },
  {
    name: "resume-security-project",
    namespace: "security-projects",
    description: "Resume Security project",
    method: "POST",
    path: "/api/v1/serverless/projects/security/{id}/_resume",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
  },
  {
    name: "get-security-project-roles",
    namespace: "security-projects",
    description: "Get roles for a Security project",
    method: "GET",
    path: "/api/v1/serverless/projects/security/{id}/roles",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
  },
  {
    name: "get-security-project-status",
    namespace: "security-projects",
    description: "Get the status of a Security project",
    method: "GET",
    path: "/api/v1/serverless/projects/security/{id}/status",
    pathParams: [
    { name: "id", description: "The ID of the project", required: true },
    ],
  },
]
