/**
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { CloudApiDefinition } from '../types.ts'

export const stackApis: CloudApiDefinition[] = [
  {
    name: "get-version-stacks",
    namespace: "stack",
    description: "Get stack versions",
    method: "GET",
    path: "/api/v1/stack/versions",
    queryParams: [
    { name: "show_deleted", type: "boolean", description: "Whether to show deleted stack versions or not" },
    { name: "show_unusable", type: "boolean", description: "Whether to show versions that are unusable by the authenticated user" },
    ],
  },
]
