/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { CloudApiDefinition } from '../types.ts'

export const trafficFiltersApis: CloudApiDefinition[] = [
  {
    name: "list-traffic-filters",
    namespace: "traffic-filters",
    description: "List traffic filters",
    method: "GET",
    path: "/api/v1/serverless/traffic-filters",
    queryParams: [
    { name: "include_by_default", type: "boolean", description: "Retrieves a list of resources that have include_by_default set or not set" },
    { name: "region", type: "string", description: "If provided limits the traffic filters to that region only." },
    ],
  },
  {
    name: "create-traffic-filter",
    namespace: "traffic-filters",
    description: "Create a traffic filter",
    method: "POST",
    path: "/api/v1/serverless/traffic-filters",
  },
  {
    name: "get-traffic-filter-metadata",
    namespace: "traffic-filters",
    description: "List PrivateLink region metadata",
    method: "GET",
    path: "/api/v1/serverless/traffic-filters/metadata",
    queryParams: [
    { name: "region", type: "string", description: "Filter metadata to a specific region (e.g. aws-eu-west-1, azure-australiaeast)." },
    { name: "csp", type: "string", description: "Filter metadata to a specific cloud service provider (aws, azure, gcp)." },
    ],
  },
  {
    name: "get-traffic-filter",
    namespace: "traffic-filters",
    description: "Retrieves the traffic filter by ID.",
    method: "GET",
    path: "/api/v1/serverless/traffic-filters/{id}",
    pathParams: [
    { name: "id", description: "The traffic filter ID.", required: true },
    ],
  },
  {
    name: "delete-traffic-filter",
    namespace: "traffic-filters",
    description: "Delete a traffic filter",
    method: "DELETE",
    path: "/api/v1/serverless/traffic-filters/{id}",
    pathParams: [
    { name: "id", description: "The traffic filter ID.", required: true },
    ],
  },
  {
    name: "patch-traffic-filter",
    namespace: "traffic-filters",
    description: "Updates a traffic filter",
    method: "PATCH",
    path: "/api/v1/serverless/traffic-filters/{id}",
    pathParams: [
    { name: "id", description: "The traffic filter ID.", required: true },
    ],
  },
]
