/**
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { CloudApiDefinition } from '../types.ts'

export const trustedEnvironmentsApis: CloudApiDefinition[] = [
  {
    name: "get-trusted-envs",
    namespace: "trusted-environments",
    description: "Get trusted environments",
    method: "GET",
    path: "/api/v1/trusted-environments",
  },
]
