/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { CloudApiDefinition } from '../types.ts'

export const userRoleAssignmentsApis: CloudApiDefinition[] = [
  {
    name: "add-role-assignments",
    namespace: "user-role-assignments",
    description: "Add Role Assignments",
    method: "POST",
    path: "/api/v1/users/{user_id}/role_assignments",
    pathParams: [
    { name: "user_id", description: "Identifier for the user; include realm name and id if required", required: true },
    ],
  },
  {
    name: "remove-role-assignments",
    namespace: "user-role-assignments",
    description: "Remove Role Assignments",
    method: "DELETE",
    path: "/api/v1/users/{user_id}/role_assignments",
    pathParams: [
    { name: "user_id", description: "Identifier for the user; include realm name and id if required", required: true },
    ],
  },
]
