/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { KbApiDefinition } from '../types.ts'

export const elasticAgentStatusApis: KbApiDefinition[] = [
  {
    name: "get-fleet-agent-status",
    namespace: "elastic-agent-status",
    description: "Get an agent status summary",
    method: "GET",
    path: "/api/fleet/agent_status",
    queryParams: [
    { name: "policyId", type: "string", description: "" },
    { name: "policyIds", type: "string", description: "" },
    { name: "kuery", type: "string", description: "" },
    ],
  },
]
