/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { KbApiDefinition } from '../types.ts'

export const elasticAgentBinaryDownloadSourcesApis: KbApiDefinition[] = [
  {
    name: "get-fleet-agent-download-sources",
    namespace: "elastic-agent-binary-download-sources",
    description: "Get agent binary download sources",
    method: "GET",
    path: "/api/fleet/agent_download_sources",
  },
  {
    name: "post-fleet-agent-download-sources",
    namespace: "elastic-agent-binary-download-sources",
    description: "Create an agent binary download source",
    method: "POST",
    path: "/api/fleet/agent_download_sources",
    bodyParams: [
    { name: "auth", type: "object", description: "" },
    { name: "host", type: "string", description: "", required: true },
    { name: "id", type: "string", description: "" },
    { name: "is_default", type: "boolean", description: "" },
    { name: "name", type: "string", description: "", required: true },
    { name: "proxy_id", type: "string", description: "The ID of the proxy to use for this download source. See the proxies API for more information." },
    { name: "secrets", type: "object", description: "" },
    { name: "ssl", type: "object", description: "" },
    ],
  },
  {
    name: "delete-fleet-agent-download-sources-sourceid",
    namespace: "elastic-agent-binary-download-sources",
    description: "Delete an agent binary download source",
    method: "DELETE",
    path: "/api/fleet/agent_download_sources/{sourceId}",
    pathParams: [
    { name: "sourceId", description: "The sourceId parameter", required: true },
    ],
  },
  {
    name: "get-fleet-agent-download-sources-sourceid",
    namespace: "elastic-agent-binary-download-sources",
    description: "Get an agent binary download source",
    method: "GET",
    path: "/api/fleet/agent_download_sources/{sourceId}",
    pathParams: [
    { name: "sourceId", description: "The sourceId parameter", required: true },
    ],
  },
  {
    name: "put-fleet-agent-download-sources-sourceid",
    namespace: "elastic-agent-binary-download-sources",
    description: "Update an agent binary download source",
    method: "PUT",
    path: "/api/fleet/agent_download_sources/{sourceId}",
    pathParams: [
    { name: "sourceId", description: "The sourceId parameter", required: true },
    ],
    bodyParams: [
    { name: "auth", type: "object", description: "" },
    { name: "host", type: "string", description: "", required: true },
    { name: "id", type: "string", description: "" },
    { name: "is_default", type: "boolean", description: "" },
    { name: "name", type: "string", description: "", required: true },
    { name: "proxy_id", type: "string", description: "The ID of the proxy to use for this download source. See the proxies API for more information." },
    { name: "secrets", type: "object", description: "" },
    { name: "ssl", type: "object", description: "" },
    ],
  },
]
