/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { KbApiDefinition } from '../types.ts'

export const elasticAgentActionsApis: KbApiDefinition[] = [
  {
    name: "post-fleet-agents-agentid-actions",
    namespace: "elastic-agent-actions",
    description: "Create an agent action",
    method: "POST",
    path: "/api/fleet/agents/{agentId}/actions",
    pathParams: [
    { name: "agentId", description: "The agentId parameter", required: true },
    ],
    bodyParams: [
    { name: "action", type: "string", description: "", required: true },
    ],
  },
  {
    name: "post-fleet-agents-agentid-reassign",
    namespace: "elastic-agent-actions",
    description: "Reassign an agent",
    method: "POST",
    path: "/api/fleet/agents/{agentId}/reassign",
    pathParams: [
    { name: "agentId", description: "The agentId parameter", required: true },
    ],
    bodyParams: [
    { name: "policy_id", type: "string", description: "", required: true },
    ],
  },
  {
    name: "post-fleet-agents-agentid-request-diagnostics",
    namespace: "elastic-agent-actions",
    description: "Request agent diagnostics",
    method: "POST",
    path: "/api/fleet/agents/{agentId}/request_diagnostics",
    pathParams: [
    { name: "agentId", description: "The agentId parameter", required: true },
    ],
    bodyParams: [
    { name: "additional_metrics", type: "array", description: "" },
    ],
  },
  {
    name: "post-fleet-agents-agentid-rollback",
    namespace: "elastic-agent-actions",
    description: "Rollback an agent",
    method: "POST",
    path: "/api/fleet/agents/{agentId}/rollback",
    pathParams: [
    { name: "agentId", description: "The agent ID to rollback", required: true },
    ],
  },
  {
    name: "post-fleet-agents-agentid-unenroll",
    namespace: "elastic-agent-actions",
    description: "Unenroll an agent",
    method: "POST",
    path: "/api/fleet/agents/{agentId}/unenroll",
    pathParams: [
    { name: "agentId", description: "The agentId parameter", required: true },
    ],
    bodyParams: [
    { name: "force", type: "boolean", description: "" },
    { name: "revoke", type: "boolean", description: "" },
    ],
  },
  {
    name: "post-fleet-agents-agentid-upgrade",
    namespace: "elastic-agent-actions",
    description: "Upgrade an agent",
    method: "POST",
    path: "/api/fleet/agents/{agentId}/upgrade",
    pathParams: [
    { name: "agentId", description: "The agentId parameter", required: true },
    ],
    bodyParams: [
    { name: "force", type: "boolean", description: "" },
    { name: "skipRateLimitCheck", type: "boolean", description: "" },
    { name: "source_uri", type: "string", description: "" },
    { name: "version", cliFlag: "kb-version", type: "string", description: "", required: true },
    ],
  },
  {
    name: "get-fleet-agents-action-status",
    namespace: "elastic-agent-actions",
    description: "Get an agent action status",
    method: "GET",
    path: "/api/fleet/agents/action_status",
    queryParams: [
    { name: "page", type: "number", description: "" },
    { name: "perPage", type: "number", description: "" },
    { name: "date", type: "string", description: "" },
    { name: "latest", type: "number", description: "" },
    { name: "errorSize", type: "number", description: "" },
    ],
  },
  {
    name: "post-fleet-agents-actions-actionid-cancel",
    namespace: "elastic-agent-actions",
    description: "Cancel an agent action",
    method: "POST",
    path: "/api/fleet/agents/actions/{actionId}/cancel",
    pathParams: [
    { name: "actionId", description: "The actionId parameter", required: true },
    ],
  },
  {
    name: "post-fleet-agents-bulk-reassign",
    namespace: "elastic-agent-actions",
    description: "Bulk reassign agents",
    method: "POST",
    path: "/api/fleet/agents/bulk_reassign",
    bodyParams: [
    { name: "agents", type: "string", description: "", required: true },
    { name: "batchSize", type: "number", description: "" },
    { name: "includeInactive", type: "boolean", description: "" },
    { name: "policy_id", type: "string", description: "", required: true },
    ],
  },
  {
    name: "post-fleet-agents-bulk-request-diagnostics",
    namespace: "elastic-agent-actions",
    description: "Bulk request diagnostics from agents",
    method: "POST",
    path: "/api/fleet/agents/bulk_request_diagnostics",
    bodyParams: [
    { name: "additional_metrics", type: "array", description: "" },
    { name: "agents", type: "string", description: "", required: true },
    { name: "batchSize", type: "number", description: "" },
    ],
  },
  {
    name: "post-fleet-agents-bulk-rollback",
    namespace: "elastic-agent-actions",
    description: "Bulk rollback agents",
    method: "POST",
    path: "/api/fleet/agents/bulk_rollback",
    bodyParams: [
    { name: "agents", type: "string", description: "", required: true },
    { name: "batchSize", type: "number", description: "" },
    { name: "includeInactive", type: "boolean", description: "" },
    ],
  },
  {
    name: "post-fleet-agents-bulk-unenroll",
    namespace: "elastic-agent-actions",
    description: "Bulk unenroll agents",
    method: "POST",
    path: "/api/fleet/agents/bulk_unenroll",
    bodyParams: [
    { name: "agents", type: "string", description: "", required: true },
    { name: "batchSize", type: "number", description: "" },
    { name: "force", type: "boolean", description: "Unenrolls hosted agents too" },
    { name: "includeInactive", type: "boolean", description: "When passing agents by KQL query, unenrolls inactive agents too" },
    { name: "revoke", type: "boolean", description: "Revokes API keys of agents" },
    ],
  },
  {
    name: "post-fleet-agents-bulk-update-agent-tags",
    namespace: "elastic-agent-actions",
    description: "Bulk update agent tags",
    method: "POST",
    path: "/api/fleet/agents/bulk_update_agent_tags",
    bodyParams: [
    { name: "agents", type: "string", description: "", required: true },
    { name: "batchSize", type: "number", description: "" },
    { name: "includeInactive", type: "boolean", description: "" },
    { name: "tagsToAdd", type: "array", description: "" },
    { name: "tagsToRemove", type: "array", description: "" },
    ],
  },
  {
    name: "post-fleet-agents-bulk-upgrade",
    namespace: "elastic-agent-actions",
    description: "Bulk upgrade agents",
    method: "POST",
    path: "/api/fleet/agents/bulk_upgrade",
    bodyParams: [
    { name: "agents", type: "string", description: "", required: true },
    { name: "batchSize", type: "number", description: "" },
    { name: "force", type: "boolean", description: "" },
    { name: "includeInactive", type: "boolean", description: "" },
    { name: "rollout_duration_seconds", type: "number", description: "" },
    { name: "skipRateLimitCheck", type: "boolean", description: "" },
    { name: "source_uri", type: "string", description: "" },
    { name: "start_time", type: "string", description: "" },
    { name: "version", cliFlag: "kb-version", type: "string", description: "", required: true },
    ],
  },
]
