/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { KbApiDefinition } from '../types.ts'

export const fleetServerHostsApis: KbApiDefinition[] = [
  {
    name: "get-fleet-fleet-server-hosts",
    namespace: "fleet-server-hosts",
    description: "Get Fleet Server hosts",
    method: "GET",
    path: "/api/fleet/fleet_server_hosts",
  },
  {
    name: "post-fleet-fleet-server-hosts",
    namespace: "fleet-server-hosts",
    description: "Create a Fleet Server host",
    method: "POST",
    path: "/api/fleet/fleet_server_hosts",
    bodyParams: [
    { name: "host_urls", type: "array", description: "", required: true },
    { name: "id", type: "string", description: "" },
    { name: "is_default", type: "boolean", description: "" },
    { name: "is_internal", type: "boolean", description: "" },
    { name: "is_preconfigured", type: "boolean", description: "" },
    { name: "name", type: "string", description: "", required: true },
    { name: "proxy_id", type: "string", description: "" },
    { name: "secrets", type: "object", description: "" },
    { name: "ssl", type: "object", description: "" },
    ],
  },
  {
    name: "delete-fleet-fleet-server-hosts-itemid",
    namespace: "fleet-server-hosts",
    description: "Delete a Fleet Server host",
    method: "DELETE",
    path: "/api/fleet/fleet_server_hosts/{itemId}",
    pathParams: [
    { name: "itemId", description: "The itemId parameter", required: true },
    ],
  },
  {
    name: "get-fleet-fleet-server-hosts-itemid",
    namespace: "fleet-server-hosts",
    description: "Get a Fleet Server host",
    method: "GET",
    path: "/api/fleet/fleet_server_hosts/{itemId}",
    pathParams: [
    { name: "itemId", description: "The itemId parameter", required: true },
    ],
  },
  {
    name: "put-fleet-fleet-server-hosts-itemid",
    namespace: "fleet-server-hosts",
    description: "Update a Fleet Server host",
    method: "PUT",
    path: "/api/fleet/fleet_server_hosts/{itemId}",
    pathParams: [
    { name: "itemId", description: "The itemId parameter", required: true },
    ],
    bodyParams: [
    { name: "host_urls", type: "array", description: "" },
    { name: "is_default", type: "boolean", description: "" },
    { name: "is_internal", type: "boolean", description: "" },
    { name: "name", type: "string", description: "" },
    { name: "proxy_id", type: "string", description: "", required: true },
    { name: "secrets", type: "object", description: "" },
    { name: "ssl", type: "object", description: "" },
    ],
  },
]
