/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { KbApiDefinition } from '../types.ts'

export const savedObjectsApis: KbApiDefinition[] = [
  {
    name: "post-saved-objects-export",
    namespace: "saved-objects",
    description: "Export saved objects",
    method: "POST",
    path: "/api/saved_objects/_export",
    bodyParams: [
    { name: "excludeExportDetails", type: "boolean", description: "Do not add export details entry at the end of the stream." },
    { name: "hasReference", type: "string", description: "" },
    { name: "includeReferencesDeep", type: "boolean", description: "Includes all of the referenced objects in the exported objects." },
    { name: "objects", type: "array", description: "A list of objects to export. NOTE: this optional parameter cannot be combined with the `types` option" },
    { name: "search", type: "string", description: "Search for documents to export using the Elasticsearch Simple Query String syntax." },
    { name: "type", type: "string", description: "The saved object types to include in the export. Use `*` to export all the types. Valid options depend on enabled plugins, but may include `visualization`, `dashboard`, `search`, `index-pattern`, `tag`, `config`, `config-global`, `lens`, `map`, `event-annotation-group`, `query`, `url`, `action`, `alert`, `alerting_rule_template`, `apm-indices`, `cases-user-actions`, `cases`, `cases-comments`, `infrastructure-monitoring-log-view`, `ml-trained-model`, `osquery-saved-query`, `osquery-pack`, `osquery-pack-asset`." },
    ],
  },
  {
    name: "post-saved-objects-import",
    namespace: "saved-objects",
    description: "Import saved objects",
    method: "POST",
    path: "/api/saved_objects/_import",
    queryParams: [
    { name: "overwrite", type: "boolean", description: "Overwrites saved objects when they already exist. When used, potential conflict errors are automatically resolved by overwriting the destination object. NOTE: This option cannot be used with the `createNewCopies` option." },
    { name: "createNewCopies", type: "boolean", description: "Creates copies of saved objects, regenerates each object ID, and resets the origin. When used, potential conflict errors are avoided. NOTE: This option cannot be used with the `overwrite` and `compatibilityMode` options." },
    { name: "compatibilityMode", type: "boolean", description: "Applies various adjustments to the saved objects that are being imported to maintain compatibility between different Kibana versions. Use this option only if you encounter issues with imported saved objects. NOTE: This option cannot be used with the `createNewCopies` option." },
    ],
  },
]
