/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was auto generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open API file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { asyncSearchApis } from './apis/async_search.ts'
import { bulkApis } from './apis/bulk.ts'
import { catApis } from './apis/cat.ts'
import { clearScrollApis } from './apis/clear_scroll.ts'
import { closePointInTimeApis } from './apis/close_point_in_time.ts'
import { clusterApis } from './apis/cluster.ts'
import { connectorApis } from './apis/connector.ts'
import { countApis } from './apis/count.ts'
import { createApis } from './apis/create.ts'
import { deleteApis } from './apis/delete.ts'
import { deleteByQueryApis } from './apis/delete_by_query.ts'
import { deleteScriptApis } from './apis/delete_script.ts'
import { enrichApis } from './apis/enrich.ts'
import { eqlApis } from './apis/eql.ts'
import { esqlApis } from './apis/esql.ts'
import { existsApis } from './apis/exists.ts'
import { existsSourceApis } from './apis/exists_source.ts'
import { explainApis } from './apis/explain.ts'
import { fieldCapsApis } from './apis/field_caps.ts'
import { getApis } from './apis/get.ts'
import { getScriptApis } from './apis/get_script.ts'
import { getSourceApis } from './apis/get_source.ts'
import { indexApis } from './apis/index.ts'
import { indicesApis } from './apis/indices.ts'
import { inferenceApis } from './apis/inference.ts'
import { infoApis } from './apis/info.ts'
import { ingestApis } from './apis/ingest.ts'
import { licenseApis } from './apis/license.ts'
import { logstashApis } from './apis/logstash.ts'
import { mgetApis } from './apis/mget.ts'
import { mlApis } from './apis/ml.ts'
import { msearchApis } from './apis/msearch.ts'
import { msearchTemplateApis } from './apis/msearch_template.ts'
import { mtermvectorsApis } from './apis/mtermvectors.ts'
import { openPointInTimeApis } from './apis/open_point_in_time.ts'
import { pingApis } from './apis/ping.ts'
import { projectApis } from './apis/project.ts'
import { putScriptApis } from './apis/put_script.ts'
import { queryRulesApis } from './apis/query_rules.ts'
import { rankEvalApis } from './apis/rank_eval.ts'
import { reindexApis } from './apis/reindex.ts'
import { renderSearchTemplateApis } from './apis/render_search_template.ts'
import { scriptsPainlessExecuteApis } from './apis/scripts_painless_execute.ts'
import { scrollApis } from './apis/scroll.ts'
import { searchApis } from './apis/search.ts'
import { searchApplicationApis } from './apis/search_application.ts'
import { searchMvtApis } from './apis/search_mvt.ts'
import { searchTemplateApis } from './apis/search_template.ts'
import { securityApis } from './apis/security.ts'
import { sqlApis } from './apis/sql.ts'
import { synonymsApis } from './apis/synonyms.ts'
import { tasksApis } from './apis/tasks.ts'
import { termsEnumApis } from './apis/terms_enum.ts'
import { termvectorsApis } from './apis/termvectors.ts'
import { transformApis } from './apis/transform.ts'
import { updateApis } from './apis/update.ts'
import { updateByQueryApis } from './apis/update_by_query.ts'
import type { EsApiDefinition } from './types.ts'

/** All Elasticsearch Serverless public API definitions. */
export const allApis: EsApiDefinition[] = [
  ...asyncSearchApis,
  ...bulkApis,
  ...catApis,
  ...clearScrollApis,
  ...closePointInTimeApis,
  ...clusterApis,
  ...connectorApis,
  ...countApis,
  ...createApis,
  ...deleteApis,
  ...deleteByQueryApis,
  ...deleteScriptApis,
  ...enrichApis,
  ...eqlApis,
  ...esqlApis,
  ...existsApis,
  ...existsSourceApis,
  ...explainApis,
  ...fieldCapsApis,
  ...getApis,
  ...getScriptApis,
  ...getSourceApis,
  ...indexApis,
  ...indicesApis,
  ...inferenceApis,
  ...infoApis,
  ...ingestApis,
  ...licenseApis,
  ...logstashApis,
  ...mgetApis,
  ...mlApis,
  ...msearchApis,
  ...msearchTemplateApis,
  ...mtermvectorsApis,
  ...openPointInTimeApis,
  ...pingApis,
  ...projectApis,
  ...putScriptApis,
  ...queryRulesApis,
  ...rankEvalApis,
  ...reindexApis,
  ...renderSearchTemplateApis,
  ...scriptsPainlessExecuteApis,
  ...scrollApis,
  ...searchApis,
  ...searchApplicationApis,
  ...searchMvtApis,
  ...searchTemplateApis,
  ...securityApis,
  ...sqlApis,
  ...synonymsApis,
  ...tasksApis,
  ...termsEnumApis,
  ...termvectorsApis,
  ...transformApis,
  ...updateApis,
  ...updateByQueryApis,
]
