name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-node:
    name: Test Node.js
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [20.x, 22.x, 24.x, 25.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Run unit tests
        run: npm test
        shell: bash

  license-header:
    name: Check SPDX license header
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      - name: Install
        run: npm install
      - name: License header check
        run: npm run test:spdx

  test-bun:
    name: Test Bun
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install
        run: bun install
      - name: Build
        run: bun run build
      - name: Run unit tests
        run: bun test

  validate-pr-title:
    if: github.event_name == 'pull_request'
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: PR Conventional Commit Validation
        uses: ytanikin/pr-conventional-commits@639145d78959c53c43112365837e3abd21ed67c1 # v1.5.2
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
          add_label: "false"
