---
name: docs-build

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  merge_group: ~

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    uses: elastic/docs-actions/.github/workflows/docs-build.yml@67a2f08b5b237e0f333d23c357b2f6cb6860ecf9 # v1
    with:
      enable-vale-linting: true
